services:
     bot:
          container_name: rhenium_bot
          build:
               context: .
               dockerfile: backend/Dockerfile
          env_file:
               - ./backend/.env
          volumes:
               - ./backend/cfg.global.yml:/app/cfg.global.yml
               - lmdb:/app/.cache

     dashboard:
          container_name: rhenium_dashboard
          build:
               context: .
               dockerfile: ./dashboard/Dockerfile
          env_file:
               - ./dashboard/.env
          ports:
               - "${HOST_PORT:-3000}:3000"

volumes:
     lmdb:
          name: rhenium_lmdb_data
          driver: local
