services:
     bot:
          container_name: rhenium_bot
          build:
               context: .
               dockerfile: ./applications/bot/Dockerfile
          env_file:
               - ./applications/bot/.env
          volumes:
               - ./applications/bot/cfg.global.yml:/rhenium/applications/bot/cfg.global.yml
               - lmdb:/rhenium/applications/bot/.cache

     dashboard:
          container_name: rhenium_dashboard
          build:
               context: .
               dockerfile: ./applications/dashboard/Dockerfile
          env_file:
               - ./applications/dashboard/.env
          ports:
               - "${HOST_PORT:-3000}:3000"

volumes:
     lmdb:
          name: rhenium_lmdb_data
          driver: local
