/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from "./internal/prismaNamespaceBrowser.js";
export { Prisma };
export * as $Enums from "./enums.js";
export * from "./enums.js";
/**
 * Model Guild
 *
 */
export type Guild = Prisma.GuildModel;
/**
 * Model Whitelist
 *
 */
export type Whitelist = Prisma.WhitelistModel;
/**
 * Model MessageReportConfig
 *
 */
export type MessageReportConfig = Prisma.MessageReportConfigModel;
/**
 * Model BanRequestConfig
 *
 */
export type BanRequestConfig = Prisma.BanRequestConfigModel;
/**
 * Model ContentFilterConfig
 *
 */
export type ContentFilterConfig = Prisma.ContentFilterConfigModel;
/**
 * Model BanRequest
 *
 */
export type BanRequest = Prisma.BanRequestModel;
/**
 * Model TemporaryBan
 *
 */
export type TemporaryBan = Prisma.TemporaryBanModel;
/**
 * Model MessageReport
 *
 */
export type MessageReport = Prisma.MessageReportModel;
/**
 * Model HighlightConfig
 *
 */
export type HighlightConfig = Prisma.HighlightConfigModel;
/**
 * Model Highlight
 *
 */
export type Highlight = Prisma.HighlightModel;
/**
 * Model HighlightPattern
 *
 */
export type HighlightPattern = Prisma.HighlightPatternModel;
/**
 * Model HighlightChannelScoping
 *
 */
export type HighlightChannelScoping = Prisma.HighlightChannelScopingModel;
/**
 * Model HighlightUserBlacklist
 *
 */
export type HighlightUserBlacklist = Prisma.HighlightUserBlacklistModel;
