import { GatewayIntentBits, Options, Partials } from "discord.js";
import { z } from "zod";

/**
 * Gateway intents used by Rhenium.
 * Among these intents are privileged ones. You'll need to enable `Server Members Intent` and `Message Content Intent`.
 *
 * @see https://discord.com/developers/docs/topics/gateway#gateway-intents
 */

export const CLIENT_INTENTS: readonly GatewayIntentBits[] = [
	GatewayIntentBits.Guilds,
	GatewayIntentBits.GuildMembers,
	GatewayIntentBits.GuildMessages,
	GatewayIntentBits.MessageContent,
	GatewayIntentBits.GuildMessageReactions,
	GatewayIntentBits.GuildExpressions,
	GatewayIntentBits.GuildModeration
];

/**
 * Partials used by Rhenium.
 * These explicitly define which partial structures the client will receive.
 */

export const CLIENT_PARTIALS: readonly Partials[] = [
	Partials.User,
	Partials.Message,
	Partials.Channel,
	Partials.Reaction,
	Partials.GuildMember
];

/**
 * Cache options for Rhenium.
 */
export const CLIENT_CACHE_OPTIONS = Options.cacheWithLimits({
	GuildBanManager: 0,
	GuildEmojiManager: Infinity,
	GuildStickerManager: 0,
	GuildMemberManager: Infinity,
	GuildTextThreadManager: 0,
	GuildForumThreadManager: 0,
	GuildInviteManager: 0,
	GuildScheduledEventManager: 0,

	ThreadMemberManager: 0,
	VoiceStateManager: 0,
	StageInstanceManager: 0,
	ThreadManager: 0,
	ReactionManager: 0,
	ReactionUserManager: 0,
	MessageManager: 0,
	GuildMessageManager: 0,

	UserManager: Infinity,
	ApplicationCommandManager: Infinity,
	BaseGuildEmojiManager: Infinity
});

/**
 * Regex patterns for matching Discord emojis.
 */

export const DISCORD_EMOJI_REGEX: Readonly<RegExp> = /<a?:(?<name>[a-zA-Z0-9_]+):(?<id>\d{17,19})>/;
export const DISCORD_EMOJI_REGEX_GLOBAL: Readonly<RegExp> =
	/<a?:(?<name>[a-zA-Z0-9_]+):(?<id>\d{17,19})>/g;

/**
 * Regex pattern for matching Unicode emojis.
 */

export const UNICODE_EMOJI_REGEX: Readonly<RegExp> =
	/(?:\p{Extended_Pictographic}(?:\uFE0F|\uFE0E)?(?:\u200D(?:\p{Extended_Pictographic}(?:\uFE0F|\uFE0E)?))*)/gu;

/** Zod regex schema for validating cron expressions. */
// Format: "*/5 * * * *" (every 5 minutes) */

export const ZOD_CRON_REGEX = z
	.string()
	.regex(
		/^(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|([\d*]+[/-]\d+)|\d+|\*) ?){5,7})$/gm
	);

/** Date format options for log entries. */
export const LOG_DATE_FORMAT: Intl.DateTimeFormatOptions = {
	month: "2-digit",
	day: "2-digit",
	year: "numeric",
	hour: "2-digit",
	minute: "2-digit",
	second: "2-digit",
	timeZone: "GMT",
	hour12: false
};

/** Process events that will trigger a message store and exit the process. */
export const PROCESS_EXIT_EVENTS: readonly NodeJS.Signals[] = [
	"SIGHUP",
	"SIGINT",
	"SIGQUIT",
	"SIGILL",
	"SIGTRAP",
	"SIGABRT",
	"SIGBUS",
	"SIGFPE",
	"SIGUSR1",
	"SIGSEGV",
	"SIGUSR2",
	"SIGTERM"
];

/** Default message content used when a message has no content. */
export const EMPTY_MESSAGE_CONTENT: string = "Unknown message content.";

/** Supported sentry metrics counters. */
export const SENTRY_METRICS_COUNTERS = {
	GatewayPayloadReceived: "gateway_payload_received",
	BanRequestSubmitted: "ban_request_submitted",
	BanRequestHandled: "ban_request_handled",
	MessageReportSubmitted: "message_report_submitted",
	MessageReportHandled: "message_report_handled",
	QuickMuteExecuted: "quick_mute_executed",
	QuickPurgeExecuted: "quick_purge_executed",
	CommandExecuted: "command_executed",
	CommandFailed: "command_failed",
	ComponentExecuted: "component_executed",
	ComponentFailed: "component_failed",
	ActionLogged: "action_logged"
};

const HEURISTIC_LOGGING_SMOOTH_ALPHA: Readonly<number> = 0.25;

const HEURISTIC_WINDOW_SIZE = 30;
const MESSAGE_QUEUE_TIME_RANGE = 5000;
const MESSAGE_DISTANCE_THRESHOLD = 2;
const MESSAGE_PACE_INCREASE_THRESHOLD = 5;

const HEURISTIC_MEDIUM_SCORE = 0.7;
const HEURISTIC_LENIENT_SCORE = 0.8;
const HEURISTIC_STRICT_SCORE = 0.6;

const HEURISTIC_BASE_RISK = 0.05;
const HEURISTIC_LENIENT_RISK_INCREASE = 0.3;
const HEURISTIC_MEDIUM_RISK_INCREASE = 0.4;
const HEURISTIC_STRICT_RISK_INCREASE = 0.5;

const HEURISTIC_BASE_SCAN_RATE = 10;
const HEURISTIC_MAX_SCAN_RATE = 60;
const HEURISTIC_MIN_SCAN_RATE = 1;
const HEURISTIC_SCAN_WINDOW = 60 * 1000;

const HEURISTIC_RATE_INCREASE_STEP = 10;
const HEURISTIC_RATE_INCREASE_DURATION = 5 * 60 * 1000;
const HEURISTIC_RATE_CHANGE_INTERVAL = 10 * 60 * 1000;

const HEURISTIC_SCORE_THRESHOLD = 7;
const HEURISTIC_DEFAULT_TRAFFIC_ESTIMATE = 60;
const HEURISTIC_SMOOTHED_FP_ALPHA = 0.1;
const HEURISTIC_MIN_SAMPLING_FACTOR = 0.01;

const HEURISTIC_MAX_BETA_INCREMENT_PER_CALL = 5;
const HEURISTIC_BETA_MEAN_MIN = 0.01;
const HEURISTIC_BETA_MEAN_MAX = 0.99;
const HEURISTIC_BETA_DECAY_HALF_LIFE_MS = 3 * 60 * 60 * 1000;

const HEURISTIC_SCORE_FP_INFLUENCE = 0.15;
const HEURISTIC_USER_RECENT_ALERT_WINDOW_MS = 5 * 60 * 1000;
const HEURISTIC_SCORE_USER_ALERT_INFLUENCE = 0.12;
const HEURISTIC_SCORE_PRUNE_EPSILON = 0.1;

const HEURISTIC_PRIORITY_USER_FLAG_THRESHOLD = 2;

const HEURISTIC_EWMA_MPM_ALPHA = 0.15;
const HEURISTIC_EWMA_ALPHA = 0.2;

const HEURISTIC_PID_BASE_KP = 2.0;
const HEURISTIC_PID_BASE_KI = 0.08;
const HEURISTIC_PID_BASE_KD = 0.8;
const HEURISTIC_PID_KP_MIN = 0.5;
const HEURISTIC_PID_KP_MAX = 10;
const HEURISTIC_PID_KI_MIN = 0.001;
const HEURISTIC_PID_KI_MAX = 1;
const HEURISTIC_PID_KD_MIN = 0.01;
const HEURISTIC_PID_KD_MAX = 5;

const HEURISTIC_K_TRAFFIC = 0.6;
const HEURISTIC_K_CONF = 0.4;

const HEURISTIC_DECAY_BASE = 0.92;
const HEURISTIC_DECAY_FP_INFLUENCE_FACTOR = 0.5;
const HEURISTIC_DECAY_FP_INFLUENCE_MAX = 0.35;
const HEURISTIC_DECAY_ALERT_INFLUENCE_PER_ALERT = 0.02;
const HEURISTIC_DECAY_ALERT_INFLUENCE_MAX = 0.2;
const HEURISTIC_DECAY_MIN = 0.55;
const HEURISTIC_DECAY_MAX = 0.98;

const HEURISTIC_PRIORITY_MULT_FACTOR = 3;
const HEURISTIC_PRIORITY_MULT_MAX = 2;
const HEURISTIC_RECENT_ALERTS_CAP = 50;

const HEURISTIC_DYNAMIC_WEIGHT_BASE = 0.6;
const HEURISTIC_DYNAMIC_WEIGHT_SEVERITY_MULT = 1.2;
const HEURISTIC_DYNAMIC_WEIGHT_MIN = 0.5;
const HEURISTIC_DYNAMIC_WEIGHT_MAX = 5;

const HEURISTIC_RISK_MULTIPLIER_MIN = 0.2;
const HEURISTIC_RISK_MULTIPLIER_MAX = 1.0;
const HEURISTIC_JITTER_PCT = 0.1;
const HEURISTIC_MIN_SCHEDULE_DELAY = 100;

const HEURISTIC_WINDOW_BASE_MS = 120_000;
const HEURISTIC_WINDOW_MIN_MS = 30_000;
const HEURISTIC_WINDOW_MAX_MS = 300_000;
const HEURISTIC_CHANNEL_SCAN_COOLDOWN_MS = 90_000;

const HEURISTIC_ADAPTIVE_P95_WINDOWS = 10;
const HEURISTIC_ADAPTIVE_DECAY_ALPHA = 0.6;
const HEURISTIC_TICK_INTERVAL_MS = 100;

const HEURISTIC_DYNAMIC_WINDOW_MULT_MAX = 4;
const HEURISTIC_DYNAMIC_WINDOW_MIN = 10;
const HEURISTIC_MIN_SIGNAL_SCORE = 4;

const HEURISTIC_MIN_CANDIDATES = 2;
const HEURISTIC_CANDIDATE_TRAFFIC_DIVISOR = 10;
const HEURISTIC_MAX_CANDIDATES_PER_SCAN = 3;

const HEURISTIC_MATCH_MAX_LENGTH = 48;
const HEURISTIC_MATCH_MAX_WORDS = 8;
const HEURISTIC_REACTION_MAX_LENGTH = 40;
const HEURISTIC_REACTION_MAX_WORDS = 6;

const HEURISTIC_RATE_DECAY_A = 0.6;
const HEURISTIC_RATE_DECAY_B = 0.4;
const HEURISTIC_MIN_ABS_CHANGE_FOR_LOG = 10;

const HEURISTIC_SCAN_DEBOUNCE_MIN = 10_000;
const HEURISTIC_SCAN_DEBOUNCE_MAX = 60_000;
const HEURISTIC_SCAN_DEBOUNCE_MIN_DELAY = 10_000;

const HEURISTIC_USER_SCORES_MAX_SIZE = 1000;

const HEURISTIC_REACTION_REGEX: Readonly<RegExp> = /(?:^|\s)\p{Lu}{4,11}(?:$|\s)/u;

const DEFAULT_STANDARD_MESSAGE_SCORE = 1;
const DEFAULT_REPLY_MESSAGE_SCORE = 1;

const DEFAULT_INITIAL_DELAY = 2.5 * 60 * 1000;
const DEFAULT_RETRY_JITTER = 0.3;
const DEFAULT_MAX_RETRIES = 2;
const DEFAULT_BACKOFF_FACTOR = 2;
const DEFAULT_MAX_DELAY = 5 * 60 * 1000;
const DEFAULT_FINAL_DELAY = 10 * 60 * 1000;

// TTL for content filter alerts and logs (24 hours default)
const CONTENT_FILTER_ALERT_TTL = 24 * 60 * 60 * 1000;
const CONTENT_FILTER_LOG_TTL = 7 * 24 * 60 * 60 * 1000;

export const CF_CONSTANTS = {
	HEURISTIC_LOGGING_SMOOTH_ALPHA,
	HEURISTIC_WINDOW_SIZE,
	MESSAGE_QUEUE_TIME_RANGE,
	MESSAGE_DISTANCE_THRESHOLD,
	MESSAGE_PACE_INCREASE_THRESHOLD,

	HEURISTIC_MEDIUM_SCORE,
	HEURISTIC_LENIENT_SCORE,
	HEURISTIC_STRICT_SCORE,

	HEURISTIC_BASE_RISK,
	HEURISTIC_LENIENT_RISK_INCREASE,
	HEURISTIC_MEDIUM_RISK_INCREASE,
	HEURISTIC_STRICT_RISK_INCREASE,

	HEURISTIC_BASE_SCAN_RATE,
	HEURISTIC_MAX_SCAN_RATE,
	HEURISTIC_MIN_SCAN_RATE,
	HEURISTIC_SCAN_WINDOW,

	HEURISTIC_RATE_INCREASE_STEP,
	HEURISTIC_RATE_INCREASE_DURATION,
	HEURISTIC_RATE_CHANGE_INTERVAL,

	HEURISTIC_SCORE_THRESHOLD,
	HEURISTIC_DEFAULT_TRAFFIC_ESTIMATE,
	HEURISTIC_SMOOTHED_FP_ALPHA,
	HEURISTIC_MIN_SAMPLING_FACTOR,

	HEURISTIC_MAX_BETA_INCREMENT_PER_CALL,
	HEURISTIC_BETA_MEAN_MIN,
	HEURISTIC_BETA_MEAN_MAX,
	HEURISTIC_BETA_DECAY_HALF_LIFE_MS,

	HEURISTIC_SCORE_FP_INFLUENCE,
	HEURISTIC_USER_RECENT_ALERT_WINDOW_MS,
	HEURISTIC_SCORE_USER_ALERT_INFLUENCE,
	HEURISTIC_SCORE_PRUNE_EPSILON,

	HEURISTIC_PRIORITY_USER_FLAG_THRESHOLD,

	HEURISTIC_EWMA_MPM_ALPHA,
	HEURISTIC_EWMA_ALPHA,

	HEURISTIC_PID_BASE_KP,
	HEURISTIC_PID_BASE_KI,
	HEURISTIC_PID_BASE_KD,

	HEURISTIC_PID_KP_MIN,
	HEURISTIC_PID_KP_MAX,
	HEURISTIC_PID_KI_MIN,
	HEURISTIC_PID_KI_MAX,
	HEURISTIC_PID_KD_MIN,
	HEURISTIC_PID_KD_MAX,

	HEURISTIC_K_TRAFFIC,
	HEURISTIC_K_CONF,

	HEURISTIC_DECAY_BASE,
	HEURISTIC_DECAY_FP_INFLUENCE_FACTOR,
	HEURISTIC_DECAY_FP_INFLUENCE_MAX,

	HEURISTIC_DECAY_ALERT_INFLUENCE_PER_ALERT,
	HEURISTIC_DECAY_ALERT_INFLUENCE_MAX,
	HEURISTIC_DECAY_MIN,
	HEURISTIC_DECAY_MAX,

	HEURISTIC_PRIORITY_MULT_FACTOR,
	HEURISTIC_PRIORITY_MULT_MAX,
	HEURISTIC_RECENT_ALERTS_CAP,

	HEURISTIC_DYNAMIC_WEIGHT_BASE,
	HEURISTIC_DYNAMIC_WEIGHT_SEVERITY_MULT,
	HEURISTIC_DYNAMIC_WEIGHT_MIN,
	HEURISTIC_DYNAMIC_WEIGHT_MAX,

	HEURISTIC_RISK_MULTIPLIER_MIN,
	HEURISTIC_RISK_MULTIPLIER_MAX,
	HEURISTIC_JITTER_PCT,
	HEURISTIC_MIN_SCHEDULE_DELAY,

	HEURISTIC_WINDOW_BASE_MS,
	HEURISTIC_WINDOW_MIN_MS,
	HEURISTIC_WINDOW_MAX_MS,
	HEURISTIC_CHANNEL_SCAN_COOLDOWN_MS,

	HEURISTIC_ADAPTIVE_P95_WINDOWS,
	HEURISTIC_ADAPTIVE_DECAY_ALPHA,
	HEURISTIC_TICK_INTERVAL_MS,
	HEURISTIC_DYNAMIC_WINDOW_MULT_MAX,
	HEURISTIC_DYNAMIC_WINDOW_MIN,
	HEURISTIC_MIN_SIGNAL_SCORE,
	HEURISTIC_MIN_CANDIDATES,
	HEURISTIC_CANDIDATE_TRAFFIC_DIVISOR,
	HEURISTIC_MAX_CANDIDATES_PER_SCAN,

	HEURISTIC_MATCH_MAX_LENGTH,
	HEURISTIC_MATCH_MAX_WORDS,
	HEURISTIC_REACTION_MAX_LENGTH,
	HEURISTIC_REACTION_MAX_WORDS,

	HEURISTIC_RATE_DECAY_A,
	HEURISTIC_RATE_DECAY_B,
	HEURISTIC_MIN_ABS_CHANGE_FOR_LOG,
	HEURISTIC_SCAN_DEBOUNCE_MIN,
	HEURISTIC_SCAN_DEBOUNCE_MAX,
	HEURISTIC_SCAN_DEBOUNCE_MIN_DELAY,
	HEURISTIC_USER_SCORES_MAX_SIZE,
	HEURISTIC_REACTION_REGEX,

	DEFAULT_STANDARD_MESSAGE_SCORE,
	DEFAULT_REPLY_MESSAGE_SCORE,
	DEFAULT_INITIAL_DELAY,
	DEFAULT_RETRY_JITTER,
	DEFAULT_MAX_RETRIES,
	DEFAULT_BACKOFF_FACTOR,
	DEFAULT_MAX_DELAY,
	DEFAULT_FINAL_DELAY,
	CONTENT_FILTER_ALERT_TTL,
	CONTENT_FILTER_LOG_TTL
};
