/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ContentFilterChannelScoping` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model ContentFilterChannelScoping
 *
 */
export type ContentFilterChannelScopingModel =
	runtime.Types.Result.DefaultSelection<Prisma.$ContentFilterChannelScopingPayload>;

export type AggregateContentFilterChannelScoping = {
	_count: ContentFilterChannelScopingCountAggregateOutputType | null;
	_avg: ContentFilterChannelScopingAvgAggregateOutputType | null;
	_sum: ContentFilterChannelScopingSumAggregateOutputType | null;
	_min: ContentFilterChannelScopingMinAggregateOutputType | null;
	_max: ContentFilterChannelScopingMaxAggregateOutputType | null;
};

export type ContentFilterChannelScopingAvgAggregateOutputType = {
	type: number | null;
};

export type ContentFilterChannelScopingSumAggregateOutputType = {
	type: number | null;
};

export type ContentFilterChannelScopingMinAggregateOutputType = {
	guild_id: string | null;
	channel_id: string | null;
	type: number | null;
};

export type ContentFilterChannelScopingMaxAggregateOutputType = {
	guild_id: string | null;
	channel_id: string | null;
	type: number | null;
};

export type ContentFilterChannelScopingCountAggregateOutputType = {
	guild_id: number;
	channel_id: number;
	type: number;
	_all: number;
};

export type ContentFilterChannelScopingAvgAggregateInputType = {
	type?: true;
};

export type ContentFilterChannelScopingSumAggregateInputType = {
	type?: true;
};

export type ContentFilterChannelScopingMinAggregateInputType = {
	guild_id?: true;
	channel_id?: true;
	type?: true;
};

export type ContentFilterChannelScopingMaxAggregateInputType = {
	guild_id?: true;
	channel_id?: true;
	type?: true;
};

export type ContentFilterChannelScopingCountAggregateInputType = {
	guild_id?: true;
	channel_id?: true;
	type?: true;
	_all?: true;
};

export type ContentFilterChannelScopingAggregateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which ContentFilterChannelScoping to aggregate.
	 */
	where?: Prisma.ContentFilterChannelScopingWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of ContentFilterChannelScopings to fetch.
	 */
	orderBy?:
		| Prisma.ContentFilterChannelScopingOrderByWithRelationInput
		| Prisma.ContentFilterChannelScopingOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.ContentFilterChannelScopingWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` ContentFilterChannelScopings from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` ContentFilterChannelScopings.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned ContentFilterChannelScopings
	 **/
	_count?: true | ContentFilterChannelScopingCountAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to average
	 **/
	_avg?: ContentFilterChannelScopingAvgAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to sum
	 **/
	_sum?: ContentFilterChannelScopingSumAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: ContentFilterChannelScopingMinAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: ContentFilterChannelScopingMaxAggregateInputType;
};

export type GetContentFilterChannelScopingAggregateType<T extends ContentFilterChannelScopingAggregateArgs> = {
	[P in keyof T & keyof AggregateContentFilterChannelScoping]: P extends "_count" | "count"
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateContentFilterChannelScoping[P]>
		: Prisma.GetScalarType<T[P], AggregateContentFilterChannelScoping[P]>;
};

export type ContentFilterChannelScopingGroupByArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.ContentFilterChannelScopingWhereInput;
	orderBy?:
		| Prisma.ContentFilterChannelScopingOrderByWithAggregationInput
		| Prisma.ContentFilterChannelScopingOrderByWithAggregationInput[];
	by: Prisma.ContentFilterChannelScopingScalarFieldEnum[] | Prisma.ContentFilterChannelScopingScalarFieldEnum;
	having?: Prisma.ContentFilterChannelScopingScalarWhereWithAggregatesInput;
	take?: number;
	skip?: number;
	_count?: ContentFilterChannelScopingCountAggregateInputType | true;
	_avg?: ContentFilterChannelScopingAvgAggregateInputType;
	_sum?: ContentFilterChannelScopingSumAggregateInputType;
	_min?: ContentFilterChannelScopingMinAggregateInputType;
	_max?: ContentFilterChannelScopingMaxAggregateInputType;
};

export type ContentFilterChannelScopingGroupByOutputType = {
	guild_id: string;
	channel_id: string;
	type: number;
	_count: ContentFilterChannelScopingCountAggregateOutputType | null;
	_avg: ContentFilterChannelScopingAvgAggregateOutputType | null;
	_sum: ContentFilterChannelScopingSumAggregateOutputType | null;
	_min: ContentFilterChannelScopingMinAggregateOutputType | null;
	_max: ContentFilterChannelScopingMaxAggregateOutputType | null;
};

type GetContentFilterChannelScopingGroupByPayload<T extends ContentFilterChannelScopingGroupByArgs> =
	Prisma.PrismaPromise<
		Array<
			Prisma.PickEnumerable<ContentFilterChannelScopingGroupByOutputType, T["by"]> & {
				[P in keyof T & keyof ContentFilterChannelScopingGroupByOutputType]: P extends "_count"
					? T[P] extends boolean
						? number
						: Prisma.GetScalarType<T[P], ContentFilterChannelScopingGroupByOutputType[P]>
					: Prisma.GetScalarType<T[P], ContentFilterChannelScopingGroupByOutputType[P]>;
			}
		>
	>;

export type ContentFilterChannelScopingWhereInput = {
	AND?: Prisma.ContentFilterChannelScopingWhereInput | Prisma.ContentFilterChannelScopingWhereInput[];
	OR?: Prisma.ContentFilterChannelScopingWhereInput[];
	NOT?: Prisma.ContentFilterChannelScopingWhereInput | Prisma.ContentFilterChannelScopingWhereInput[];
	guild_id?: Prisma.StringFilter<"ContentFilterChannelScoping"> | string;
	channel_id?: Prisma.StringFilter<"ContentFilterChannelScoping"> | string;
	type?: Prisma.IntFilter<"ContentFilterChannelScoping"> | number;
	content_filter_config?: Prisma.XOR<
		Prisma.ContentFilterConfigScalarRelationFilter,
		Prisma.ContentFilterConfigWhereInput
	>;
};

export type ContentFilterChannelScopingOrderByWithRelationInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
	content_filter_config?: Prisma.ContentFilterConfigOrderByWithRelationInput;
};

export type ContentFilterChannelScopingWhereUniqueInput = Prisma.AtLeast<
	{
		guild_id_channel_id?: Prisma.ContentFilterChannelScopingGuild_idChannel_idCompoundUniqueInput;
		AND?: Prisma.ContentFilterChannelScopingWhereInput | Prisma.ContentFilterChannelScopingWhereInput[];
		OR?: Prisma.ContentFilterChannelScopingWhereInput[];
		NOT?: Prisma.ContentFilterChannelScopingWhereInput | Prisma.ContentFilterChannelScopingWhereInput[];
		guild_id?: Prisma.StringFilter<"ContentFilterChannelScoping"> | string;
		channel_id?: Prisma.StringFilter<"ContentFilterChannelScoping"> | string;
		type?: Prisma.IntFilter<"ContentFilterChannelScoping"> | number;
		content_filter_config?: Prisma.XOR<
			Prisma.ContentFilterConfigScalarRelationFilter,
			Prisma.ContentFilterConfigWhereInput
		>;
	},
	"guild_id_channel_id"
>;

export type ContentFilterChannelScopingOrderByWithAggregationInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
	_count?: Prisma.ContentFilterChannelScopingCountOrderByAggregateInput;
	_avg?: Prisma.ContentFilterChannelScopingAvgOrderByAggregateInput;
	_max?: Prisma.ContentFilterChannelScopingMaxOrderByAggregateInput;
	_min?: Prisma.ContentFilterChannelScopingMinOrderByAggregateInput;
	_sum?: Prisma.ContentFilterChannelScopingSumOrderByAggregateInput;
};

export type ContentFilterChannelScopingScalarWhereWithAggregatesInput = {
	AND?:
		| Prisma.ContentFilterChannelScopingScalarWhereWithAggregatesInput
		| Prisma.ContentFilterChannelScopingScalarWhereWithAggregatesInput[];
	OR?: Prisma.ContentFilterChannelScopingScalarWhereWithAggregatesInput[];
	NOT?:
		| Prisma.ContentFilterChannelScopingScalarWhereWithAggregatesInput
		| Prisma.ContentFilterChannelScopingScalarWhereWithAggregatesInput[];
	guild_id?: Prisma.StringWithAggregatesFilter<"ContentFilterChannelScoping"> | string;
	channel_id?: Prisma.StringWithAggregatesFilter<"ContentFilterChannelScoping"> | string;
	type?: Prisma.IntWithAggregatesFilter<"ContentFilterChannelScoping"> | number;
};

export type ContentFilterChannelScopingCreateInput = {
	channel_id: string;
	type: number;
	content_filter_config: Prisma.ContentFilterConfigCreateNestedOneWithoutChannel_scopingInput;
};

export type ContentFilterChannelScopingUncheckedCreateInput = {
	guild_id: string;
	channel_id: string;
	type: number;
};

export type ContentFilterChannelScopingUpdateInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
	content_filter_config?: Prisma.ContentFilterConfigUpdateOneRequiredWithoutChannel_scopingNestedInput;
};

export type ContentFilterChannelScopingUncheckedUpdateInput = {
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ContentFilterChannelScopingCreateManyInput = {
	guild_id: string;
	channel_id: string;
	type: number;
};

export type ContentFilterChannelScopingUpdateManyMutationInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ContentFilterChannelScopingUncheckedUpdateManyInput = {
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ContentFilterChannelScopingListRelationFilter = {
	every?: Prisma.ContentFilterChannelScopingWhereInput;
	some?: Prisma.ContentFilterChannelScopingWhereInput;
	none?: Prisma.ContentFilterChannelScopingWhereInput;
};

export type ContentFilterChannelScopingOrderByRelationAggregateInput = {
	_count?: Prisma.SortOrder;
};

export type ContentFilterChannelScopingGuild_idChannel_idCompoundUniqueInput = {
	guild_id: string;
	channel_id: string;
};

export type ContentFilterChannelScopingCountOrderByAggregateInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
};

export type ContentFilterChannelScopingAvgOrderByAggregateInput = {
	type?: Prisma.SortOrder;
};

export type ContentFilterChannelScopingMaxOrderByAggregateInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
};

export type ContentFilterChannelScopingMinOrderByAggregateInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
};

export type ContentFilterChannelScopingSumOrderByAggregateInput = {
	type?: Prisma.SortOrder;
};

export type ContentFilterChannelScopingCreateNestedManyWithoutContent_filter_configInput = {
	create?:
		| Prisma.XOR<
				Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput,
				Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput
		  >
		| Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput[]
		| Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput[];
	connectOrCreate?:
		| Prisma.ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput[];
	createMany?: Prisma.ContentFilterChannelScopingCreateManyContent_filter_configInputEnvelope;
	connect?:
		| Prisma.ContentFilterChannelScopingWhereUniqueInput
		| Prisma.ContentFilterChannelScopingWhereUniqueInput[];
};

export type ContentFilterChannelScopingUncheckedCreateNestedManyWithoutContent_filter_configInput = {
	create?:
		| Prisma.XOR<
				Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput,
				Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput
		  >
		| Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput[]
		| Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput[];
	connectOrCreate?:
		| Prisma.ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput[];
	createMany?: Prisma.ContentFilterChannelScopingCreateManyContent_filter_configInputEnvelope;
	connect?:
		| Prisma.ContentFilterChannelScopingWhereUniqueInput
		| Prisma.ContentFilterChannelScopingWhereUniqueInput[];
};

export type ContentFilterChannelScopingUpdateManyWithoutContent_filter_configNestedInput = {
	create?:
		| Prisma.XOR<
				Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput,
				Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput
		  >
		| Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput[]
		| Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput[];
	connectOrCreate?:
		| Prisma.ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput[];
	upsert?:
		| Prisma.ContentFilterChannelScopingUpsertWithWhereUniqueWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingUpsertWithWhereUniqueWithoutContent_filter_configInput[];
	createMany?: Prisma.ContentFilterChannelScopingCreateManyContent_filter_configInputEnvelope;
	set?: Prisma.ContentFilterChannelScopingWhereUniqueInput | Prisma.ContentFilterChannelScopingWhereUniqueInput[];
	disconnect?:
		| Prisma.ContentFilterChannelScopingWhereUniqueInput
		| Prisma.ContentFilterChannelScopingWhereUniqueInput[];
	delete?: Prisma.ContentFilterChannelScopingWhereUniqueInput | Prisma.ContentFilterChannelScopingWhereUniqueInput[];
	connect?:
		| Prisma.ContentFilterChannelScopingWhereUniqueInput
		| Prisma.ContentFilterChannelScopingWhereUniqueInput[];
	update?:
		| Prisma.ContentFilterChannelScopingUpdateWithWhereUniqueWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingUpdateWithWhereUniqueWithoutContent_filter_configInput[];
	updateMany?:
		| Prisma.ContentFilterChannelScopingUpdateManyWithWhereWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingUpdateManyWithWhereWithoutContent_filter_configInput[];
	deleteMany?:
		| Prisma.ContentFilterChannelScopingScalarWhereInput
		| Prisma.ContentFilterChannelScopingScalarWhereInput[];
};

export type ContentFilterChannelScopingUncheckedUpdateManyWithoutContent_filter_configNestedInput = {
	create?:
		| Prisma.XOR<
				Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput,
				Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput
		  >
		| Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput[]
		| Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput[];
	connectOrCreate?:
		| Prisma.ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput[];
	upsert?:
		| Prisma.ContentFilterChannelScopingUpsertWithWhereUniqueWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingUpsertWithWhereUniqueWithoutContent_filter_configInput[];
	createMany?: Prisma.ContentFilterChannelScopingCreateManyContent_filter_configInputEnvelope;
	set?: Prisma.ContentFilterChannelScopingWhereUniqueInput | Prisma.ContentFilterChannelScopingWhereUniqueInput[];
	disconnect?:
		| Prisma.ContentFilterChannelScopingWhereUniqueInput
		| Prisma.ContentFilterChannelScopingWhereUniqueInput[];
	delete?: Prisma.ContentFilterChannelScopingWhereUniqueInput | Prisma.ContentFilterChannelScopingWhereUniqueInput[];
	connect?:
		| Prisma.ContentFilterChannelScopingWhereUniqueInput
		| Prisma.ContentFilterChannelScopingWhereUniqueInput[];
	update?:
		| Prisma.ContentFilterChannelScopingUpdateWithWhereUniqueWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingUpdateWithWhereUniqueWithoutContent_filter_configInput[];
	updateMany?:
		| Prisma.ContentFilterChannelScopingUpdateManyWithWhereWithoutContent_filter_configInput
		| Prisma.ContentFilterChannelScopingUpdateManyWithWhereWithoutContent_filter_configInput[];
	deleteMany?:
		| Prisma.ContentFilterChannelScopingScalarWhereInput
		| Prisma.ContentFilterChannelScopingScalarWhereInput[];
};

export type IntFieldUpdateOperationsInput = {
	set?: number;
	increment?: number;
	decrement?: number;
	multiply?: number;
	divide?: number;
};

export type ContentFilterChannelScopingCreateWithoutContent_filter_configInput = {
	channel_id: string;
	type: number;
};

export type ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput = {
	channel_id: string;
	type: number;
};

export type ContentFilterChannelScopingCreateOrConnectWithoutContent_filter_configInput = {
	where: Prisma.ContentFilterChannelScopingWhereUniqueInput;
	create: Prisma.XOR<
		Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput,
		Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput
	>;
};

export type ContentFilterChannelScopingCreateManyContent_filter_configInputEnvelope = {
	data:
		| Prisma.ContentFilterChannelScopingCreateManyContent_filter_configInput
		| Prisma.ContentFilterChannelScopingCreateManyContent_filter_configInput[];
	skipDuplicates?: boolean;
};

export type ContentFilterChannelScopingUpsertWithWhereUniqueWithoutContent_filter_configInput = {
	where: Prisma.ContentFilterChannelScopingWhereUniqueInput;
	update: Prisma.XOR<
		Prisma.ContentFilterChannelScopingUpdateWithoutContent_filter_configInput,
		Prisma.ContentFilterChannelScopingUncheckedUpdateWithoutContent_filter_configInput
	>;
	create: Prisma.XOR<
		Prisma.ContentFilterChannelScopingCreateWithoutContent_filter_configInput,
		Prisma.ContentFilterChannelScopingUncheckedCreateWithoutContent_filter_configInput
	>;
};

export type ContentFilterChannelScopingUpdateWithWhereUniqueWithoutContent_filter_configInput = {
	where: Prisma.ContentFilterChannelScopingWhereUniqueInput;
	data: Prisma.XOR<
		Prisma.ContentFilterChannelScopingUpdateWithoutContent_filter_configInput,
		Prisma.ContentFilterChannelScopingUncheckedUpdateWithoutContent_filter_configInput
	>;
};

export type ContentFilterChannelScopingUpdateManyWithWhereWithoutContent_filter_configInput = {
	where: Prisma.ContentFilterChannelScopingScalarWhereInput;
	data: Prisma.XOR<
		Prisma.ContentFilterChannelScopingUpdateManyMutationInput,
		Prisma.ContentFilterChannelScopingUncheckedUpdateManyWithoutContent_filter_configInput
	>;
};

export type ContentFilterChannelScopingScalarWhereInput = {
	AND?: Prisma.ContentFilterChannelScopingScalarWhereInput | Prisma.ContentFilterChannelScopingScalarWhereInput[];
	OR?: Prisma.ContentFilterChannelScopingScalarWhereInput[];
	NOT?: Prisma.ContentFilterChannelScopingScalarWhereInput | Prisma.ContentFilterChannelScopingScalarWhereInput[];
	guild_id?: Prisma.StringFilter<"ContentFilterChannelScoping"> | string;
	channel_id?: Prisma.StringFilter<"ContentFilterChannelScoping"> | string;
	type?: Prisma.IntFilter<"ContentFilterChannelScoping"> | number;
};

export type ContentFilterChannelScopingCreateManyContent_filter_configInput = {
	channel_id: string;
	type: number;
};

export type ContentFilterChannelScopingUpdateWithoutContent_filter_configInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ContentFilterChannelScopingUncheckedUpdateWithoutContent_filter_configInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ContentFilterChannelScopingUncheckedUpdateManyWithoutContent_filter_configInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ContentFilterChannelScopingSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		guild_id?: boolean;
		channel_id?: boolean;
		type?: boolean;
		content_filter_config?: boolean | Prisma.ContentFilterConfigDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["contentFilterChannelScoping"]
>;

export type ContentFilterChannelScopingSelectCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		guild_id?: boolean;
		channel_id?: boolean;
		type?: boolean;
		content_filter_config?: boolean | Prisma.ContentFilterConfigDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["contentFilterChannelScoping"]
>;

export type ContentFilterChannelScopingSelectUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		guild_id?: boolean;
		channel_id?: boolean;
		type?: boolean;
		content_filter_config?: boolean | Prisma.ContentFilterConfigDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["contentFilterChannelScoping"]
>;

export type ContentFilterChannelScopingSelectScalar = {
	guild_id?: boolean;
	channel_id?: boolean;
	type?: boolean;
};

export type ContentFilterChannelScopingOmit<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<
	"guild_id" | "channel_id" | "type",
	ExtArgs["result"]["contentFilterChannelScoping"]
>;
export type ContentFilterChannelScopingInclude<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	content_filter_config?: boolean | Prisma.ContentFilterConfigDefaultArgs<ExtArgs>;
};
export type ContentFilterChannelScopingIncludeCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	content_filter_config?: boolean | Prisma.ContentFilterConfigDefaultArgs<ExtArgs>;
};
export type ContentFilterChannelScopingIncludeUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	content_filter_config?: boolean | Prisma.ContentFilterConfigDefaultArgs<ExtArgs>;
};

export type $ContentFilterChannelScopingPayload<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	name: "ContentFilterChannelScoping";
	objects: {
		content_filter_config: Prisma.$ContentFilterConfigPayload<ExtArgs>;
	};
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			guild_id: string;
			channel_id: string;
			/**
			 * Include [`0`] or Exclude [`1`]
			 */
			type: number;
		},
		ExtArgs["result"]["contentFilterChannelScoping"]
	>;
	composites: {};
};

export type ContentFilterChannelScopingGetPayload<
	S extends boolean | null | undefined | ContentFilterChannelScopingDefaultArgs
> = runtime.Types.Result.GetResult<Prisma.$ContentFilterChannelScopingPayload, S>;

export type ContentFilterChannelScopingCountArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<ContentFilterChannelScopingFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
	select?: ContentFilterChannelScopingCountAggregateInputType | true;
};

export interface ContentFilterChannelScopingDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> {
	[K: symbol]: {
		types: Prisma.TypeMap<ExtArgs>["model"]["ContentFilterChannelScoping"];
		meta: { name: "ContentFilterChannelScoping" };
	};
	/**
	 * Find zero or one ContentFilterChannelScoping that matches the filter.
	 * @param {ContentFilterChannelScopingFindUniqueArgs} args - Arguments to find a ContentFilterChannelScoping
	 * @example
	 * // Get one ContentFilterChannelScoping
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends ContentFilterChannelScopingFindUniqueArgs>(
		args: Prisma.SelectSubset<T, ContentFilterChannelScopingFindUniqueArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"findUnique",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find one ContentFilterChannelScoping that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {ContentFilterChannelScopingFindUniqueOrThrowArgs} args - Arguments to find a ContentFilterChannelScoping
	 * @example
	 * // Get one ContentFilterChannelScoping
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends ContentFilterChannelScopingFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, ContentFilterChannelScopingFindUniqueOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"findUniqueOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first ContentFilterChannelScoping that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterChannelScopingFindFirstArgs} args - Arguments to find a ContentFilterChannelScoping
	 * @example
	 * // Get one ContentFilterChannelScoping
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends ContentFilterChannelScopingFindFirstArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterChannelScopingFindFirstArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"findFirst",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first ContentFilterChannelScoping that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterChannelScopingFindFirstOrThrowArgs} args - Arguments to find a ContentFilterChannelScoping
	 * @example
	 * // Get one ContentFilterChannelScoping
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends ContentFilterChannelScopingFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterChannelScopingFindFirstOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"findFirstOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find zero or more ContentFilterChannelScopings that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterChannelScopingFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all ContentFilterChannelScopings
	 * const contentFilterChannelScopings = await prisma.contentFilterChannelScoping.findMany()
	 *
	 * // Get first 10 ContentFilterChannelScopings
	 * const contentFilterChannelScopings = await prisma.contentFilterChannelScoping.findMany({ take: 10 })
	 *
	 * // Only select the `guild_id`
	 * const contentFilterChannelScopingWithGuild_idOnly = await prisma.contentFilterChannelScoping.findMany({ select: { guild_id: true } })
	 *
	 */
	findMany<T extends ContentFilterChannelScopingFindManyArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterChannelScopingFindManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"findMany",
			GlobalOmitOptions
		>
	>;

	/**
	 * Create a ContentFilterChannelScoping.
	 * @param {ContentFilterChannelScopingCreateArgs} args - Arguments to create a ContentFilterChannelScoping.
	 * @example
	 * // Create one ContentFilterChannelScoping
	 * const ContentFilterChannelScoping = await prisma.contentFilterChannelScoping.create({
	 *   data: {
	 *     // ... data to create a ContentFilterChannelScoping
	 *   }
	 * })
	 *
	 */
	create<T extends ContentFilterChannelScopingCreateArgs>(
		args: Prisma.SelectSubset<T, ContentFilterChannelScopingCreateArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"create",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Create many ContentFilterChannelScopings.
	 * @param {ContentFilterChannelScopingCreateManyArgs} args - Arguments to create many ContentFilterChannelScopings.
	 * @example
	 * // Create many ContentFilterChannelScopings
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends ContentFilterChannelScopingCreateManyArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterChannelScopingCreateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Create many ContentFilterChannelScopings and returns the data saved in the database.
	 * @param {ContentFilterChannelScopingCreateManyAndReturnArgs} args - Arguments to create many ContentFilterChannelScopings.
	 * @example
	 * // Create many ContentFilterChannelScopings
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.createManyAndReturn({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Create many ContentFilterChannelScopings and only return the `guild_id`
	 * const contentFilterChannelScopingWithGuild_idOnly = await prisma.contentFilterChannelScoping.createManyAndReturn({
	 *   select: { guild_id: true },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	createManyAndReturn<T extends ContentFilterChannelScopingCreateManyAndReturnArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterChannelScopingCreateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"createManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Delete a ContentFilterChannelScoping.
	 * @param {ContentFilterChannelScopingDeleteArgs} args - Arguments to delete one ContentFilterChannelScoping.
	 * @example
	 * // Delete one ContentFilterChannelScoping
	 * const ContentFilterChannelScoping = await prisma.contentFilterChannelScoping.delete({
	 *   where: {
	 *     // ... filter to delete one ContentFilterChannelScoping
	 *   }
	 * })
	 *
	 */
	delete<T extends ContentFilterChannelScopingDeleteArgs>(
		args: Prisma.SelectSubset<T, ContentFilterChannelScopingDeleteArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"delete",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Update one ContentFilterChannelScoping.
	 * @param {ContentFilterChannelScopingUpdateArgs} args - Arguments to update one ContentFilterChannelScoping.
	 * @example
	 * // Update one ContentFilterChannelScoping
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends ContentFilterChannelScopingUpdateArgs>(
		args: Prisma.SelectSubset<T, ContentFilterChannelScopingUpdateArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"update",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Delete zero or more ContentFilterChannelScopings.
	 * @param {ContentFilterChannelScopingDeleteManyArgs} args - Arguments to filter ContentFilterChannelScopings to delete.
	 * @example
	 * // Delete a few ContentFilterChannelScopings
	 * const { count } = await prisma.contentFilterChannelScoping.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends ContentFilterChannelScopingDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterChannelScopingDeleteManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more ContentFilterChannelScopings.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterChannelScopingUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many ContentFilterChannelScopings
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends ContentFilterChannelScopingUpdateManyArgs>(
		args: Prisma.SelectSubset<T, ContentFilterChannelScopingUpdateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more ContentFilterChannelScopings and returns the data updated in the database.
	 * @param {ContentFilterChannelScopingUpdateManyAndReturnArgs} args - Arguments to update many ContentFilterChannelScopings.
	 * @example
	 * // Update many ContentFilterChannelScopings
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.updateManyAndReturn({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Update zero or more ContentFilterChannelScopings and only return the `guild_id`
	 * const contentFilterChannelScopingWithGuild_idOnly = await prisma.contentFilterChannelScoping.updateManyAndReturn({
	 *   select: { guild_id: true },
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	updateManyAndReturn<T extends ContentFilterChannelScopingUpdateManyAndReturnArgs>(
		args: Prisma.SelectSubset<T, ContentFilterChannelScopingUpdateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"updateManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Create or update one ContentFilterChannelScoping.
	 * @param {ContentFilterChannelScopingUpsertArgs} args - Arguments to update or create a ContentFilterChannelScoping.
	 * @example
	 * // Update or create a ContentFilterChannelScoping
	 * const contentFilterChannelScoping = await prisma.contentFilterChannelScoping.upsert({
	 *   create: {
	 *     // ... data to create a ContentFilterChannelScoping
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the ContentFilterChannelScoping we want to update
	 *   }
	 * })
	 */
	upsert<T extends ContentFilterChannelScopingUpsertArgs>(
		args: Prisma.SelectSubset<T, ContentFilterChannelScopingUpsertArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterChannelScopingPayload<ExtArgs>,
			T,
			"upsert",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Count the number of ContentFilterChannelScopings.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterChannelScopingCountArgs} args - Arguments to filter ContentFilterChannelScopings to count.
	 * @example
	 * // Count the number of ContentFilterChannelScopings
	 * const count = await prisma.contentFilterChannelScoping.count({
	 *   where: {
	 *     // ... the filter for the ContentFilterChannelScopings we want to count
	 *   }
	 * })
	 **/
	count<T extends ContentFilterChannelScopingCountArgs>(
		args?: Prisma.Subset<T, ContentFilterChannelScopingCountArgs>
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<"select", any>
			? T["select"] extends true
				? number
				: Prisma.GetScalarType<T["select"], ContentFilterChannelScopingCountAggregateOutputType>
			: number
	>;

	/**
	 * Allows you to perform aggregations operations on a ContentFilterChannelScoping.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterChannelScopingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends ContentFilterChannelScopingAggregateArgs>(
		args: Prisma.Subset<T, ContentFilterChannelScopingAggregateArgs>
	): Prisma.PrismaPromise<GetContentFilterChannelScopingAggregateType<T>>;

	/**
	 * Group by ContentFilterChannelScoping.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterChannelScopingGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends ContentFilterChannelScopingGroupByArgs,
		HasSelectOrTake extends Prisma.Or<
			Prisma.Extends<"skip", Prisma.Keys<T>>,
			Prisma.Extends<"take", Prisma.Keys<T>>
		>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: ContentFilterChannelScopingGroupByArgs["orderBy"] }
			: { orderBy?: ContentFilterChannelScopingGroupByArgs["orderBy"] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T["having"]>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
					}[HavingFields]
				: "take" extends Prisma.Keys<T>
					? "orderBy" extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: "skip" extends Prisma.Keys<T>
						? "orderBy" extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields
											? never
											: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
	>(
		args: Prisma.SubsetIntersection<T, ContentFilterChannelScopingGroupByArgs, OrderByArg> & InputErrors
	): {} extends InputErrors ? GetContentFilterChannelScopingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
	/**
	 * Fields of the ContentFilterChannelScoping model
	 */
	readonly fields: ContentFilterChannelScopingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ContentFilterChannelScoping.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContentFilterChannelScopingClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: "PrismaPromise";
	content_filter_config<T extends Prisma.ContentFilterConfigDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.ContentFilterConfigDefaultArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterConfigClient<
		| runtime.Types.Result.GetResult<
				Prisma.$ContentFilterConfigPayload<ExtArgs>,
				T,
				"findUniqueOrThrow",
				GlobalOmitOptions
		  >
		| Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>;
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
	): runtime.Types.Utils.JsPromise<T | TResult>;
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ContentFilterChannelScoping model
 */
export interface ContentFilterChannelScopingFieldRefs {
	readonly guild_id: Prisma.FieldRef<"ContentFilterChannelScoping", "String">;
	readonly channel_id: Prisma.FieldRef<"ContentFilterChannelScoping", "String">;
	readonly type: Prisma.FieldRef<"ContentFilterChannelScoping", "Int">;
}

// Custom InputTypes
/**
 * ContentFilterChannelScoping findUnique
 */
export type ContentFilterChannelScopingFindUniqueArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterChannelScoping to fetch.
	 */
	where: Prisma.ContentFilterChannelScopingWhereUniqueInput;
};

/**
 * ContentFilterChannelScoping findUniqueOrThrow
 */
export type ContentFilterChannelScopingFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterChannelScoping to fetch.
	 */
	where: Prisma.ContentFilterChannelScopingWhereUniqueInput;
};

/**
 * ContentFilterChannelScoping findFirst
 */
export type ContentFilterChannelScopingFindFirstArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterChannelScoping to fetch.
	 */
	where?: Prisma.ContentFilterChannelScopingWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of ContentFilterChannelScopings to fetch.
	 */
	orderBy?:
		| Prisma.ContentFilterChannelScopingOrderByWithRelationInput
		| Prisma.ContentFilterChannelScopingOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for ContentFilterChannelScopings.
	 */
	cursor?: Prisma.ContentFilterChannelScopingWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` ContentFilterChannelScopings from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` ContentFilterChannelScopings.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of ContentFilterChannelScopings.
	 */
	distinct?: Prisma.ContentFilterChannelScopingScalarFieldEnum | Prisma.ContentFilterChannelScopingScalarFieldEnum[];
};

/**
 * ContentFilterChannelScoping findFirstOrThrow
 */
export type ContentFilterChannelScopingFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterChannelScoping to fetch.
	 */
	where?: Prisma.ContentFilterChannelScopingWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of ContentFilterChannelScopings to fetch.
	 */
	orderBy?:
		| Prisma.ContentFilterChannelScopingOrderByWithRelationInput
		| Prisma.ContentFilterChannelScopingOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for ContentFilterChannelScopings.
	 */
	cursor?: Prisma.ContentFilterChannelScopingWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` ContentFilterChannelScopings from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` ContentFilterChannelScopings.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of ContentFilterChannelScopings.
	 */
	distinct?: Prisma.ContentFilterChannelScopingScalarFieldEnum | Prisma.ContentFilterChannelScopingScalarFieldEnum[];
};

/**
 * ContentFilterChannelScoping findMany
 */
export type ContentFilterChannelScopingFindManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterChannelScopings to fetch.
	 */
	where?: Prisma.ContentFilterChannelScopingWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of ContentFilterChannelScopings to fetch.
	 */
	orderBy?:
		| Prisma.ContentFilterChannelScopingOrderByWithRelationInput
		| Prisma.ContentFilterChannelScopingOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing ContentFilterChannelScopings.
	 */
	cursor?: Prisma.ContentFilterChannelScopingWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` ContentFilterChannelScopings from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` ContentFilterChannelScopings.
	 */
	skip?: number;
	distinct?: Prisma.ContentFilterChannelScopingScalarFieldEnum | Prisma.ContentFilterChannelScopingScalarFieldEnum[];
};

/**
 * ContentFilterChannelScoping create
 */
export type ContentFilterChannelScopingCreateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * The data needed to create a ContentFilterChannelScoping.
	 */
	data: Prisma.XOR<
		Prisma.ContentFilterChannelScopingCreateInput,
		Prisma.ContentFilterChannelScopingUncheckedCreateInput
	>;
};

/**
 * ContentFilterChannelScoping createMany
 */
export type ContentFilterChannelScopingCreateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to create many ContentFilterChannelScopings.
	 */
	data: Prisma.ContentFilterChannelScopingCreateManyInput | Prisma.ContentFilterChannelScopingCreateManyInput[];
	skipDuplicates?: boolean;
};

/**
 * ContentFilterChannelScoping createManyAndReturn
 */
export type ContentFilterChannelScopingCreateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelectCreateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * The data used to create many ContentFilterChannelScopings.
	 */
	data: Prisma.ContentFilterChannelScopingCreateManyInput | Prisma.ContentFilterChannelScopingCreateManyInput[];
	skipDuplicates?: boolean;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * ContentFilterChannelScoping update
 */
export type ContentFilterChannelScopingUpdateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * The data needed to update a ContentFilterChannelScoping.
	 */
	data: Prisma.XOR<
		Prisma.ContentFilterChannelScopingUpdateInput,
		Prisma.ContentFilterChannelScopingUncheckedUpdateInput
	>;
	/**
	 * Choose, which ContentFilterChannelScoping to update.
	 */
	where: Prisma.ContentFilterChannelScopingWhereUniqueInput;
};

/**
 * ContentFilterChannelScoping updateMany
 */
export type ContentFilterChannelScopingUpdateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to update ContentFilterChannelScopings.
	 */
	data: Prisma.XOR<
		Prisma.ContentFilterChannelScopingUpdateManyMutationInput,
		Prisma.ContentFilterChannelScopingUncheckedUpdateManyInput
	>;
	/**
	 * Filter which ContentFilterChannelScopings to update
	 */
	where?: Prisma.ContentFilterChannelScopingWhereInput;
	/**
	 * Limit how many ContentFilterChannelScopings to update.
	 */
	limit?: number;
};

/**
 * ContentFilterChannelScoping updateManyAndReturn
 */
export type ContentFilterChannelScopingUpdateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelectUpdateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * The data used to update ContentFilterChannelScopings.
	 */
	data: Prisma.XOR<
		Prisma.ContentFilterChannelScopingUpdateManyMutationInput,
		Prisma.ContentFilterChannelScopingUncheckedUpdateManyInput
	>;
	/**
	 * Filter which ContentFilterChannelScopings to update
	 */
	where?: Prisma.ContentFilterChannelScopingWhereInput;
	/**
	 * Limit how many ContentFilterChannelScopings to update.
	 */
	limit?: number;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * ContentFilterChannelScoping upsert
 */
export type ContentFilterChannelScopingUpsertArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * The filter to search for the ContentFilterChannelScoping to update in case it exists.
	 */
	where: Prisma.ContentFilterChannelScopingWhereUniqueInput;
	/**
	 * In case the ContentFilterChannelScoping found by the `where` argument doesn't exist, create a new ContentFilterChannelScoping with this data.
	 */
	create: Prisma.XOR<
		Prisma.ContentFilterChannelScopingCreateInput,
		Prisma.ContentFilterChannelScopingUncheckedCreateInput
	>;
	/**
	 * In case the ContentFilterChannelScoping was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<
		Prisma.ContentFilterChannelScopingUpdateInput,
		Prisma.ContentFilterChannelScopingUncheckedUpdateInput
	>;
};

/**
 * ContentFilterChannelScoping delete
 */
export type ContentFilterChannelScopingDeleteArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter which ContentFilterChannelScoping to delete.
	 */
	where: Prisma.ContentFilterChannelScopingWhereUniqueInput;
};

/**
 * ContentFilterChannelScoping deleteMany
 */
export type ContentFilterChannelScopingDeleteManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which ContentFilterChannelScopings to delete
	 */
	where?: Prisma.ContentFilterChannelScopingWhereInput;
	/**
	 * Limit how many ContentFilterChannelScopings to delete.
	 */
	limit?: number;
};

/**
 * ContentFilterChannelScoping without action
 */
export type ContentFilterChannelScopingDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterChannelScoping
	 */
	select?: Prisma.ContentFilterChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterChannelScoping
	 */
	omit?: Prisma.ContentFilterChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterChannelScopingInclude<ExtArgs> | null;
};
