/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ContentFilterLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model ContentFilterLog
 *
 */
export type ContentFilterLogModel = runtime.Types.Result.DefaultSelection<Prisma.$ContentFilterLogPayload>;

export type AggregateContentFilterLog = {
	_count: ContentFilterLogCountAggregateOutputType | null;
	_min: ContentFilterLogMinAggregateOutputType | null;
	_max: ContentFilterLogMaxAggregateOutputType | null;
};

export type ContentFilterLogMinAggregateOutputType = {
	id: string | null;
	guild_id: string | null;
	alert_id: string | null;
	content: string | null;
	created_at: Date | null;
};

export type ContentFilterLogMaxAggregateOutputType = {
	id: string | null;
	guild_id: string | null;
	alert_id: string | null;
	content: string | null;
	created_at: Date | null;
};

export type ContentFilterLogCountAggregateOutputType = {
	id: number;
	guild_id: number;
	alert_id: number;
	content: number;
	created_at: number;
	_all: number;
};

export type ContentFilterLogMinAggregateInputType = {
	id?: true;
	guild_id?: true;
	alert_id?: true;
	content?: true;
	created_at?: true;
};

export type ContentFilterLogMaxAggregateInputType = {
	id?: true;
	guild_id?: true;
	alert_id?: true;
	content?: true;
	created_at?: true;
};

export type ContentFilterLogCountAggregateInputType = {
	id?: true;
	guild_id?: true;
	alert_id?: true;
	content?: true;
	created_at?: true;
	_all?: true;
};

export type ContentFilterLogAggregateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which ContentFilterLog to aggregate.
	 */
	where?: Prisma.ContentFilterLogWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of ContentFilterLogs to fetch.
	 */
	orderBy?: Prisma.ContentFilterLogOrderByWithRelationInput | Prisma.ContentFilterLogOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.ContentFilterLogWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` ContentFilterLogs from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` ContentFilterLogs.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned ContentFilterLogs
	 **/
	_count?: true | ContentFilterLogCountAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: ContentFilterLogMinAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: ContentFilterLogMaxAggregateInputType;
};

export type GetContentFilterLogAggregateType<T extends ContentFilterLogAggregateArgs> = {
	[P in keyof T & keyof AggregateContentFilterLog]: P extends "_count" | "count"
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateContentFilterLog[P]>
		: Prisma.GetScalarType<T[P], AggregateContentFilterLog[P]>;
};

export type ContentFilterLogGroupByArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.ContentFilterLogWhereInput;
	orderBy?:
		| Prisma.ContentFilterLogOrderByWithAggregationInput
		| Prisma.ContentFilterLogOrderByWithAggregationInput[];
	by: Prisma.ContentFilterLogScalarFieldEnum[] | Prisma.ContentFilterLogScalarFieldEnum;
	having?: Prisma.ContentFilterLogScalarWhereWithAggregatesInput;
	take?: number;
	skip?: number;
	_count?: ContentFilterLogCountAggregateInputType | true;
	_min?: ContentFilterLogMinAggregateInputType;
	_max?: ContentFilterLogMaxAggregateInputType;
};

export type ContentFilterLogGroupByOutputType = {
	id: string;
	guild_id: string;
	alert_id: string;
	content: string;
	created_at: Date;
	_count: ContentFilterLogCountAggregateOutputType | null;
	_min: ContentFilterLogMinAggregateOutputType | null;
	_max: ContentFilterLogMaxAggregateOutputType | null;
};

type GetContentFilterLogGroupByPayload<T extends ContentFilterLogGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<ContentFilterLogGroupByOutputType, T["by"]> & {
			[P in keyof T & keyof ContentFilterLogGroupByOutputType]: P extends "_count"
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], ContentFilterLogGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], ContentFilterLogGroupByOutputType[P]>;
		}
	>
>;

export type ContentFilterLogWhereInput = {
	AND?: Prisma.ContentFilterLogWhereInput | Prisma.ContentFilterLogWhereInput[];
	OR?: Prisma.ContentFilterLogWhereInput[];
	NOT?: Prisma.ContentFilterLogWhereInput | Prisma.ContentFilterLogWhereInput[];
	id?: Prisma.StringFilter<"ContentFilterLog"> | string;
	guild_id?: Prisma.StringFilter<"ContentFilterLog"> | string;
	alert_id?: Prisma.StringFilter<"ContentFilterLog"> | string;
	content?: Prisma.StringFilter<"ContentFilterLog"> | string;
	created_at?: Prisma.DateTimeFilter<"ContentFilterLog"> | Date | string;
	guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>;
};

export type ContentFilterLogOrderByWithRelationInput = {
	id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	alert_id?: Prisma.SortOrder;
	content?: Prisma.SortOrder;
	created_at?: Prisma.SortOrder;
	guild?: Prisma.GuildOrderByWithRelationInput;
};

export type ContentFilterLogWhereUniqueInput = Prisma.AtLeast<
	{
		id?: string;
		AND?: Prisma.ContentFilterLogWhereInput | Prisma.ContentFilterLogWhereInput[];
		OR?: Prisma.ContentFilterLogWhereInput[];
		NOT?: Prisma.ContentFilterLogWhereInput | Prisma.ContentFilterLogWhereInput[];
		guild_id?: Prisma.StringFilter<"ContentFilterLog"> | string;
		alert_id?: Prisma.StringFilter<"ContentFilterLog"> | string;
		content?: Prisma.StringFilter<"ContentFilterLog"> | string;
		created_at?: Prisma.DateTimeFilter<"ContentFilterLog"> | Date | string;
		guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>;
	},
	"id"
>;

export type ContentFilterLogOrderByWithAggregationInput = {
	id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	alert_id?: Prisma.SortOrder;
	content?: Prisma.SortOrder;
	created_at?: Prisma.SortOrder;
	_count?: Prisma.ContentFilterLogCountOrderByAggregateInput;
	_max?: Prisma.ContentFilterLogMaxOrderByAggregateInput;
	_min?: Prisma.ContentFilterLogMinOrderByAggregateInput;
};

export type ContentFilterLogScalarWhereWithAggregatesInput = {
	AND?:
		| Prisma.ContentFilterLogScalarWhereWithAggregatesInput
		| Prisma.ContentFilterLogScalarWhereWithAggregatesInput[];
	OR?: Prisma.ContentFilterLogScalarWhereWithAggregatesInput[];
	NOT?:
		| Prisma.ContentFilterLogScalarWhereWithAggregatesInput
		| Prisma.ContentFilterLogScalarWhereWithAggregatesInput[];
	id?: Prisma.StringWithAggregatesFilter<"ContentFilterLog"> | string;
	guild_id?: Prisma.StringWithAggregatesFilter<"ContentFilterLog"> | string;
	alert_id?: Prisma.StringWithAggregatesFilter<"ContentFilterLog"> | string;
	content?: Prisma.StringWithAggregatesFilter<"ContentFilterLog"> | string;
	created_at?: Prisma.DateTimeWithAggregatesFilter<"ContentFilterLog"> | Date | string;
};

export type ContentFilterLogCreateInput = {
	id?: string;
	alert_id: string;
	content: string;
	created_at?: Date | string;
	guild: Prisma.GuildCreateNestedOneWithoutContent_filter_logsInput;
};

export type ContentFilterLogUncheckedCreateInput = {
	id?: string;
	guild_id: string;
	alert_id: string;
	content: string;
	created_at?: Date | string;
};

export type ContentFilterLogUpdateInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	alert_id?: Prisma.StringFieldUpdateOperationsInput | string;
	content?: Prisma.StringFieldUpdateOperationsInput | string;
	created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
	guild?: Prisma.GuildUpdateOneRequiredWithoutContent_filter_logsNestedInput;
};

export type ContentFilterLogUncheckedUpdateInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	alert_id?: Prisma.StringFieldUpdateOperationsInput | string;
	content?: Prisma.StringFieldUpdateOperationsInput | string;
	created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ContentFilterLogCreateManyInput = {
	id?: string;
	guild_id: string;
	alert_id: string;
	content: string;
	created_at?: Date | string;
};

export type ContentFilterLogUpdateManyMutationInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	alert_id?: Prisma.StringFieldUpdateOperationsInput | string;
	content?: Prisma.StringFieldUpdateOperationsInput | string;
	created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ContentFilterLogUncheckedUpdateManyInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	alert_id?: Prisma.StringFieldUpdateOperationsInput | string;
	content?: Prisma.StringFieldUpdateOperationsInput | string;
	created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ContentFilterLogListRelationFilter = {
	every?: Prisma.ContentFilterLogWhereInput;
	some?: Prisma.ContentFilterLogWhereInput;
	none?: Prisma.ContentFilterLogWhereInput;
};

export type ContentFilterLogOrderByRelationAggregateInput = {
	_count?: Prisma.SortOrder;
};

export type ContentFilterLogCountOrderByAggregateInput = {
	id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	alert_id?: Prisma.SortOrder;
	content?: Prisma.SortOrder;
	created_at?: Prisma.SortOrder;
};

export type ContentFilterLogMaxOrderByAggregateInput = {
	id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	alert_id?: Prisma.SortOrder;
	content?: Prisma.SortOrder;
	created_at?: Prisma.SortOrder;
};

export type ContentFilterLogMinOrderByAggregateInput = {
	id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	alert_id?: Prisma.SortOrder;
	content?: Prisma.SortOrder;
	created_at?: Prisma.SortOrder;
};

export type ContentFilterLogCreateNestedManyWithoutGuildInput = {
	create?:
		| Prisma.XOR<
				Prisma.ContentFilterLogCreateWithoutGuildInput,
				Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput
		  >
		| Prisma.ContentFilterLogCreateWithoutGuildInput[]
		| Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.ContentFilterLogCreateOrConnectWithoutGuildInput
		| Prisma.ContentFilterLogCreateOrConnectWithoutGuildInput[];
	createMany?: Prisma.ContentFilterLogCreateManyGuildInputEnvelope;
	connect?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
};

export type ContentFilterLogUncheckedCreateNestedManyWithoutGuildInput = {
	create?:
		| Prisma.XOR<
				Prisma.ContentFilterLogCreateWithoutGuildInput,
				Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput
		  >
		| Prisma.ContentFilterLogCreateWithoutGuildInput[]
		| Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.ContentFilterLogCreateOrConnectWithoutGuildInput
		| Prisma.ContentFilterLogCreateOrConnectWithoutGuildInput[];
	createMany?: Prisma.ContentFilterLogCreateManyGuildInputEnvelope;
	connect?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
};

export type ContentFilterLogUpdateManyWithoutGuildNestedInput = {
	create?:
		| Prisma.XOR<
				Prisma.ContentFilterLogCreateWithoutGuildInput,
				Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput
		  >
		| Prisma.ContentFilterLogCreateWithoutGuildInput[]
		| Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.ContentFilterLogCreateOrConnectWithoutGuildInput
		| Prisma.ContentFilterLogCreateOrConnectWithoutGuildInput[];
	upsert?:
		| Prisma.ContentFilterLogUpsertWithWhereUniqueWithoutGuildInput
		| Prisma.ContentFilterLogUpsertWithWhereUniqueWithoutGuildInput[];
	createMany?: Prisma.ContentFilterLogCreateManyGuildInputEnvelope;
	set?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
	disconnect?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
	delete?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
	connect?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
	update?:
		| Prisma.ContentFilterLogUpdateWithWhereUniqueWithoutGuildInput
		| Prisma.ContentFilterLogUpdateWithWhereUniqueWithoutGuildInput[];
	updateMany?:
		| Prisma.ContentFilterLogUpdateManyWithWhereWithoutGuildInput
		| Prisma.ContentFilterLogUpdateManyWithWhereWithoutGuildInput[];
	deleteMany?: Prisma.ContentFilterLogScalarWhereInput | Prisma.ContentFilterLogScalarWhereInput[];
};

export type ContentFilterLogUncheckedUpdateManyWithoutGuildNestedInput = {
	create?:
		| Prisma.XOR<
				Prisma.ContentFilterLogCreateWithoutGuildInput,
				Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput
		  >
		| Prisma.ContentFilterLogCreateWithoutGuildInput[]
		| Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.ContentFilterLogCreateOrConnectWithoutGuildInput
		| Prisma.ContentFilterLogCreateOrConnectWithoutGuildInput[];
	upsert?:
		| Prisma.ContentFilterLogUpsertWithWhereUniqueWithoutGuildInput
		| Prisma.ContentFilterLogUpsertWithWhereUniqueWithoutGuildInput[];
	createMany?: Prisma.ContentFilterLogCreateManyGuildInputEnvelope;
	set?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
	disconnect?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
	delete?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
	connect?: Prisma.ContentFilterLogWhereUniqueInput | Prisma.ContentFilterLogWhereUniqueInput[];
	update?:
		| Prisma.ContentFilterLogUpdateWithWhereUniqueWithoutGuildInput
		| Prisma.ContentFilterLogUpdateWithWhereUniqueWithoutGuildInput[];
	updateMany?:
		| Prisma.ContentFilterLogUpdateManyWithWhereWithoutGuildInput
		| Prisma.ContentFilterLogUpdateManyWithWhereWithoutGuildInput[];
	deleteMany?: Prisma.ContentFilterLogScalarWhereInput | Prisma.ContentFilterLogScalarWhereInput[];
};

export type ContentFilterLogCreateWithoutGuildInput = {
	id?: string;
	alert_id: string;
	content: string;
	created_at?: Date | string;
};

export type ContentFilterLogUncheckedCreateWithoutGuildInput = {
	id?: string;
	alert_id: string;
	content: string;
	created_at?: Date | string;
};

export type ContentFilterLogCreateOrConnectWithoutGuildInput = {
	where: Prisma.ContentFilterLogWhereUniqueInput;
	create: Prisma.XOR<
		Prisma.ContentFilterLogCreateWithoutGuildInput,
		Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput
	>;
};

export type ContentFilterLogCreateManyGuildInputEnvelope = {
	data: Prisma.ContentFilterLogCreateManyGuildInput | Prisma.ContentFilterLogCreateManyGuildInput[];
	skipDuplicates?: boolean;
};

export type ContentFilterLogUpsertWithWhereUniqueWithoutGuildInput = {
	where: Prisma.ContentFilterLogWhereUniqueInput;
	update: Prisma.XOR<
		Prisma.ContentFilterLogUpdateWithoutGuildInput,
		Prisma.ContentFilterLogUncheckedUpdateWithoutGuildInput
	>;
	create: Prisma.XOR<
		Prisma.ContentFilterLogCreateWithoutGuildInput,
		Prisma.ContentFilterLogUncheckedCreateWithoutGuildInput
	>;
};

export type ContentFilterLogUpdateWithWhereUniqueWithoutGuildInput = {
	where: Prisma.ContentFilterLogWhereUniqueInput;
	data: Prisma.XOR<
		Prisma.ContentFilterLogUpdateWithoutGuildInput,
		Prisma.ContentFilterLogUncheckedUpdateWithoutGuildInput
	>;
};

export type ContentFilterLogUpdateManyWithWhereWithoutGuildInput = {
	where: Prisma.ContentFilterLogScalarWhereInput;
	data: Prisma.XOR<
		Prisma.ContentFilterLogUpdateManyMutationInput,
		Prisma.ContentFilterLogUncheckedUpdateManyWithoutGuildInput
	>;
};

export type ContentFilterLogScalarWhereInput = {
	AND?: Prisma.ContentFilterLogScalarWhereInput | Prisma.ContentFilterLogScalarWhereInput[];
	OR?: Prisma.ContentFilterLogScalarWhereInput[];
	NOT?: Prisma.ContentFilterLogScalarWhereInput | Prisma.ContentFilterLogScalarWhereInput[];
	id?: Prisma.StringFilter<"ContentFilterLog"> | string;
	guild_id?: Prisma.StringFilter<"ContentFilterLog"> | string;
	alert_id?: Prisma.StringFilter<"ContentFilterLog"> | string;
	content?: Prisma.StringFilter<"ContentFilterLog"> | string;
	created_at?: Prisma.DateTimeFilter<"ContentFilterLog"> | Date | string;
};

export type ContentFilterLogCreateManyGuildInput = {
	id?: string;
	alert_id: string;
	content: string;
	created_at?: Date | string;
};

export type ContentFilterLogUpdateWithoutGuildInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	alert_id?: Prisma.StringFieldUpdateOperationsInput | string;
	content?: Prisma.StringFieldUpdateOperationsInput | string;
	created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ContentFilterLogUncheckedUpdateWithoutGuildInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	alert_id?: Prisma.StringFieldUpdateOperationsInput | string;
	content?: Prisma.StringFieldUpdateOperationsInput | string;
	created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ContentFilterLogUncheckedUpdateManyWithoutGuildInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	alert_id?: Prisma.StringFieldUpdateOperationsInput | string;
	content?: Prisma.StringFieldUpdateOperationsInput | string;
	created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ContentFilterLogSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		id?: boolean;
		guild_id?: boolean;
		alert_id?: boolean;
		content?: boolean;
		created_at?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["contentFilterLog"]
>;

export type ContentFilterLogSelectCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		id?: boolean;
		guild_id?: boolean;
		alert_id?: boolean;
		content?: boolean;
		created_at?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["contentFilterLog"]
>;

export type ContentFilterLogSelectUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		id?: boolean;
		guild_id?: boolean;
		alert_id?: boolean;
		content?: boolean;
		created_at?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["contentFilterLog"]
>;

export type ContentFilterLogSelectScalar = {
	id?: boolean;
	guild_id?: boolean;
	alert_id?: boolean;
	content?: boolean;
	created_at?: boolean;
};

export type ContentFilterLogOmit<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<
	"id" | "guild_id" | "alert_id" | "content" | "created_at",
	ExtArgs["result"]["contentFilterLog"]
>;
export type ContentFilterLogInclude<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};
export type ContentFilterLogIncludeCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};
export type ContentFilterLogIncludeUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};

export type $ContentFilterLogPayload<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	name: "ContentFilterLog";
	objects: {
		guild: Prisma.$GuildPayload<ExtArgs>;
	};
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			id: string;
			guild_id: string;
			alert_id: string;
			content: string;
			created_at: Date;
		},
		ExtArgs["result"]["contentFilterLog"]
	>;
	composites: {};
};

export type ContentFilterLogGetPayload<S extends boolean | null | undefined | ContentFilterLogDefaultArgs> =
	runtime.Types.Result.GetResult<Prisma.$ContentFilterLogPayload, S>;

export type ContentFilterLogCountArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<ContentFilterLogFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
	select?: ContentFilterLogCountAggregateInputType | true;
};

export interface ContentFilterLogDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> {
	[K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["ContentFilterLog"]; meta: { name: "ContentFilterLog" } };
	/**
	 * Find zero or one ContentFilterLog that matches the filter.
	 * @param {ContentFilterLogFindUniqueArgs} args - Arguments to find a ContentFilterLog
	 * @example
	 * // Get one ContentFilterLog
	 * const contentFilterLog = await prisma.contentFilterLog.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends ContentFilterLogFindUniqueArgs>(
		args: Prisma.SelectSubset<T, ContentFilterLogFindUniqueArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterLogClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterLogPayload<ExtArgs>,
			T,
			"findUnique",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find one ContentFilterLog that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {ContentFilterLogFindUniqueOrThrowArgs} args - Arguments to find a ContentFilterLog
	 * @example
	 * // Get one ContentFilterLog
	 * const contentFilterLog = await prisma.contentFilterLog.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends ContentFilterLogFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, ContentFilterLogFindUniqueOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterLogClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterLogPayload<ExtArgs>,
			T,
			"findUniqueOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first ContentFilterLog that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterLogFindFirstArgs} args - Arguments to find a ContentFilterLog
	 * @example
	 * // Get one ContentFilterLog
	 * const contentFilterLog = await prisma.contentFilterLog.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends ContentFilterLogFindFirstArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterLogFindFirstArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterLogClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterLogPayload<ExtArgs>,
			T,
			"findFirst",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first ContentFilterLog that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterLogFindFirstOrThrowArgs} args - Arguments to find a ContentFilterLog
	 * @example
	 * // Get one ContentFilterLog
	 * const contentFilterLog = await prisma.contentFilterLog.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends ContentFilterLogFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterLogFindFirstOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterLogClient<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterLogPayload<ExtArgs>,
			T,
			"findFirstOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find zero or more ContentFilterLogs that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterLogFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all ContentFilterLogs
	 * const contentFilterLogs = await prisma.contentFilterLog.findMany()
	 *
	 * // Get first 10 ContentFilterLogs
	 * const contentFilterLogs = await prisma.contentFilterLog.findMany({ take: 10 })
	 *
	 * // Only select the `id`
	 * const contentFilterLogWithIdOnly = await prisma.contentFilterLog.findMany({ select: { id: true } })
	 *
	 */
	findMany<T extends ContentFilterLogFindManyArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterLogFindManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$ContentFilterLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>
	>;

	/**
	 * Create a ContentFilterLog.
	 * @param {ContentFilterLogCreateArgs} args - Arguments to create a ContentFilterLog.
	 * @example
	 * // Create one ContentFilterLog
	 * const ContentFilterLog = await prisma.contentFilterLog.create({
	 *   data: {
	 *     // ... data to create a ContentFilterLog
	 *   }
	 * })
	 *
	 */
	create<T extends ContentFilterLogCreateArgs>(
		args: Prisma.SelectSubset<T, ContentFilterLogCreateArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterLogClient<
		runtime.Types.Result.GetResult<Prisma.$ContentFilterLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Create many ContentFilterLogs.
	 * @param {ContentFilterLogCreateManyArgs} args - Arguments to create many ContentFilterLogs.
	 * @example
	 * // Create many ContentFilterLogs
	 * const contentFilterLog = await prisma.contentFilterLog.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends ContentFilterLogCreateManyArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterLogCreateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Create many ContentFilterLogs and returns the data saved in the database.
	 * @param {ContentFilterLogCreateManyAndReturnArgs} args - Arguments to create many ContentFilterLogs.
	 * @example
	 * // Create many ContentFilterLogs
	 * const contentFilterLog = await prisma.contentFilterLog.createManyAndReturn({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Create many ContentFilterLogs and only return the `id`
	 * const contentFilterLogWithIdOnly = await prisma.contentFilterLog.createManyAndReturn({
	 *   select: { id: true },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	createManyAndReturn<T extends ContentFilterLogCreateManyAndReturnArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterLogCreateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterLogPayload<ExtArgs>,
			T,
			"createManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Delete a ContentFilterLog.
	 * @param {ContentFilterLogDeleteArgs} args - Arguments to delete one ContentFilterLog.
	 * @example
	 * // Delete one ContentFilterLog
	 * const ContentFilterLog = await prisma.contentFilterLog.delete({
	 *   where: {
	 *     // ... filter to delete one ContentFilterLog
	 *   }
	 * })
	 *
	 */
	delete<T extends ContentFilterLogDeleteArgs>(
		args: Prisma.SelectSubset<T, ContentFilterLogDeleteArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterLogClient<
		runtime.Types.Result.GetResult<Prisma.$ContentFilterLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Update one ContentFilterLog.
	 * @param {ContentFilterLogUpdateArgs} args - Arguments to update one ContentFilterLog.
	 * @example
	 * // Update one ContentFilterLog
	 * const contentFilterLog = await prisma.contentFilterLog.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends ContentFilterLogUpdateArgs>(
		args: Prisma.SelectSubset<T, ContentFilterLogUpdateArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterLogClient<
		runtime.Types.Result.GetResult<Prisma.$ContentFilterLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Delete zero or more ContentFilterLogs.
	 * @param {ContentFilterLogDeleteManyArgs} args - Arguments to filter ContentFilterLogs to delete.
	 * @example
	 * // Delete a few ContentFilterLogs
	 * const { count } = await prisma.contentFilterLog.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends ContentFilterLogDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, ContentFilterLogDeleteManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more ContentFilterLogs.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterLogUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many ContentFilterLogs
	 * const contentFilterLog = await prisma.contentFilterLog.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends ContentFilterLogUpdateManyArgs>(
		args: Prisma.SelectSubset<T, ContentFilterLogUpdateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more ContentFilterLogs and returns the data updated in the database.
	 * @param {ContentFilterLogUpdateManyAndReturnArgs} args - Arguments to update many ContentFilterLogs.
	 * @example
	 * // Update many ContentFilterLogs
	 * const contentFilterLog = await prisma.contentFilterLog.updateManyAndReturn({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Update zero or more ContentFilterLogs and only return the `id`
	 * const contentFilterLogWithIdOnly = await prisma.contentFilterLog.updateManyAndReturn({
	 *   select: { id: true },
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	updateManyAndReturn<T extends ContentFilterLogUpdateManyAndReturnArgs>(
		args: Prisma.SelectSubset<T, ContentFilterLogUpdateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$ContentFilterLogPayload<ExtArgs>,
			T,
			"updateManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Create or update one ContentFilterLog.
	 * @param {ContentFilterLogUpsertArgs} args - Arguments to update or create a ContentFilterLog.
	 * @example
	 * // Update or create a ContentFilterLog
	 * const contentFilterLog = await prisma.contentFilterLog.upsert({
	 *   create: {
	 *     // ... data to create a ContentFilterLog
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the ContentFilterLog we want to update
	 *   }
	 * })
	 */
	upsert<T extends ContentFilterLogUpsertArgs>(
		args: Prisma.SelectSubset<T, ContentFilterLogUpsertArgs<ExtArgs>>
	): Prisma.Prisma__ContentFilterLogClient<
		runtime.Types.Result.GetResult<Prisma.$ContentFilterLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Count the number of ContentFilterLogs.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterLogCountArgs} args - Arguments to filter ContentFilterLogs to count.
	 * @example
	 * // Count the number of ContentFilterLogs
	 * const count = await prisma.contentFilterLog.count({
	 *   where: {
	 *     // ... the filter for the ContentFilterLogs we want to count
	 *   }
	 * })
	 **/
	count<T extends ContentFilterLogCountArgs>(
		args?: Prisma.Subset<T, ContentFilterLogCountArgs>
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<"select", any>
			? T["select"] extends true
				? number
				: Prisma.GetScalarType<T["select"], ContentFilterLogCountAggregateOutputType>
			: number
	>;

	/**
	 * Allows you to perform aggregations operations on a ContentFilterLog.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends ContentFilterLogAggregateArgs>(
		args: Prisma.Subset<T, ContentFilterLogAggregateArgs>
	): Prisma.PrismaPromise<GetContentFilterLogAggregateType<T>>;

	/**
	 * Group by ContentFilterLog.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {ContentFilterLogGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends ContentFilterLogGroupByArgs,
		HasSelectOrTake extends Prisma.Or<
			Prisma.Extends<"skip", Prisma.Keys<T>>,
			Prisma.Extends<"take", Prisma.Keys<T>>
		>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: ContentFilterLogGroupByArgs["orderBy"] }
			: { orderBy?: ContentFilterLogGroupByArgs["orderBy"] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T["having"]>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
					}[HavingFields]
				: "take" extends Prisma.Keys<T>
					? "orderBy" extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: "skip" extends Prisma.Keys<T>
						? "orderBy" extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields
											? never
											: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
	>(
		args: Prisma.SubsetIntersection<T, ContentFilterLogGroupByArgs, OrderByArg> & InputErrors
	): {} extends InputErrors ? GetContentFilterLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
	/**
	 * Fields of the ContentFilterLog model
	 */
	readonly fields: ContentFilterLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ContentFilterLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContentFilterLogClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: "PrismaPromise";
	guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>
	): Prisma.Prisma__GuildClient<
		| runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>
		| Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>;
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
	): runtime.Types.Utils.JsPromise<T | TResult>;
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ContentFilterLog model
 */
export interface ContentFilterLogFieldRefs {
	readonly id: Prisma.FieldRef<"ContentFilterLog", "String">;
	readonly guild_id: Prisma.FieldRef<"ContentFilterLog", "String">;
	readonly alert_id: Prisma.FieldRef<"ContentFilterLog", "String">;
	readonly content: Prisma.FieldRef<"ContentFilterLog", "String">;
	readonly created_at: Prisma.FieldRef<"ContentFilterLog", "DateTime">;
}

// Custom InputTypes
/**
 * ContentFilterLog findUnique
 */
export type ContentFilterLogFindUniqueArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterLog to fetch.
	 */
	where: Prisma.ContentFilterLogWhereUniqueInput;
};

/**
 * ContentFilterLog findUniqueOrThrow
 */
export type ContentFilterLogFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterLog to fetch.
	 */
	where: Prisma.ContentFilterLogWhereUniqueInput;
};

/**
 * ContentFilterLog findFirst
 */
export type ContentFilterLogFindFirstArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterLog to fetch.
	 */
	where?: Prisma.ContentFilterLogWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of ContentFilterLogs to fetch.
	 */
	orderBy?: Prisma.ContentFilterLogOrderByWithRelationInput | Prisma.ContentFilterLogOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for ContentFilterLogs.
	 */
	cursor?: Prisma.ContentFilterLogWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` ContentFilterLogs from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` ContentFilterLogs.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of ContentFilterLogs.
	 */
	distinct?: Prisma.ContentFilterLogScalarFieldEnum | Prisma.ContentFilterLogScalarFieldEnum[];
};

/**
 * ContentFilterLog findFirstOrThrow
 */
export type ContentFilterLogFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterLog to fetch.
	 */
	where?: Prisma.ContentFilterLogWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of ContentFilterLogs to fetch.
	 */
	orderBy?: Prisma.ContentFilterLogOrderByWithRelationInput | Prisma.ContentFilterLogOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for ContentFilterLogs.
	 */
	cursor?: Prisma.ContentFilterLogWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` ContentFilterLogs from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` ContentFilterLogs.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of ContentFilterLogs.
	 */
	distinct?: Prisma.ContentFilterLogScalarFieldEnum | Prisma.ContentFilterLogScalarFieldEnum[];
};

/**
 * ContentFilterLog findMany
 */
export type ContentFilterLogFindManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * Filter, which ContentFilterLogs to fetch.
	 */
	where?: Prisma.ContentFilterLogWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of ContentFilterLogs to fetch.
	 */
	orderBy?: Prisma.ContentFilterLogOrderByWithRelationInput | Prisma.ContentFilterLogOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing ContentFilterLogs.
	 */
	cursor?: Prisma.ContentFilterLogWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` ContentFilterLogs from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` ContentFilterLogs.
	 */
	skip?: number;
	distinct?: Prisma.ContentFilterLogScalarFieldEnum | Prisma.ContentFilterLogScalarFieldEnum[];
};

/**
 * ContentFilterLog create
 */
export type ContentFilterLogCreateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * The data needed to create a ContentFilterLog.
	 */
	data: Prisma.XOR<Prisma.ContentFilterLogCreateInput, Prisma.ContentFilterLogUncheckedCreateInput>;
};

/**
 * ContentFilterLog createMany
 */
export type ContentFilterLogCreateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to create many ContentFilterLogs.
	 */
	data: Prisma.ContentFilterLogCreateManyInput | Prisma.ContentFilterLogCreateManyInput[];
	skipDuplicates?: boolean;
};

/**
 * ContentFilterLog createManyAndReturn
 */
export type ContentFilterLogCreateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelectCreateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * The data used to create many ContentFilterLogs.
	 */
	data: Prisma.ContentFilterLogCreateManyInput | Prisma.ContentFilterLogCreateManyInput[];
	skipDuplicates?: boolean;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * ContentFilterLog update
 */
export type ContentFilterLogUpdateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * The data needed to update a ContentFilterLog.
	 */
	data: Prisma.XOR<Prisma.ContentFilterLogUpdateInput, Prisma.ContentFilterLogUncheckedUpdateInput>;
	/**
	 * Choose, which ContentFilterLog to update.
	 */
	where: Prisma.ContentFilterLogWhereUniqueInput;
};

/**
 * ContentFilterLog updateMany
 */
export type ContentFilterLogUpdateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to update ContentFilterLogs.
	 */
	data: Prisma.XOR<Prisma.ContentFilterLogUpdateManyMutationInput, Prisma.ContentFilterLogUncheckedUpdateManyInput>;
	/**
	 * Filter which ContentFilterLogs to update
	 */
	where?: Prisma.ContentFilterLogWhereInput;
	/**
	 * Limit how many ContentFilterLogs to update.
	 */
	limit?: number;
};

/**
 * ContentFilterLog updateManyAndReturn
 */
export type ContentFilterLogUpdateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelectUpdateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * The data used to update ContentFilterLogs.
	 */
	data: Prisma.XOR<Prisma.ContentFilterLogUpdateManyMutationInput, Prisma.ContentFilterLogUncheckedUpdateManyInput>;
	/**
	 * Filter which ContentFilterLogs to update
	 */
	where?: Prisma.ContentFilterLogWhereInput;
	/**
	 * Limit how many ContentFilterLogs to update.
	 */
	limit?: number;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * ContentFilterLog upsert
 */
export type ContentFilterLogUpsertArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * The filter to search for the ContentFilterLog to update in case it exists.
	 */
	where: Prisma.ContentFilterLogWhereUniqueInput;
	/**
	 * In case the ContentFilterLog found by the `where` argument doesn't exist, create a new ContentFilterLog with this data.
	 */
	create: Prisma.XOR<Prisma.ContentFilterLogCreateInput, Prisma.ContentFilterLogUncheckedCreateInput>;
	/**
	 * In case the ContentFilterLog was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.ContentFilterLogUpdateInput, Prisma.ContentFilterLogUncheckedUpdateInput>;
};

/**
 * ContentFilterLog delete
 */
export type ContentFilterLogDeleteArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
	/**
	 * Filter which ContentFilterLog to delete.
	 */
	where: Prisma.ContentFilterLogWhereUniqueInput;
};

/**
 * ContentFilterLog deleteMany
 */
export type ContentFilterLogDeleteManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which ContentFilterLogs to delete
	 */
	where?: Prisma.ContentFilterLogWhereInput;
	/**
	 * Limit how many ContentFilterLogs to delete.
	 */
	limit?: number;
};

/**
 * ContentFilterLog without action
 */
export type ContentFilterLogDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the ContentFilterLog
	 */
	select?: Prisma.ContentFilterLogSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the ContentFilterLog
	 */
	omit?: Prisma.ContentFilterLogOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ContentFilterLogInclude<ExtArgs> | null;
};
