/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `HighlightUserBlacklist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model HighlightUserBlacklist
 *
 */
export type HighlightUserBlacklistModel = runtime.Types.Result.DefaultSelection<Prisma.$HighlightUserBlacklistPayload>;

export type AggregateHighlightUserBlacklist = {
	_count: HighlightUserBlacklistCountAggregateOutputType | null;
	_min: HighlightUserBlacklistMinAggregateOutputType | null;
	_max: HighlightUserBlacklistMaxAggregateOutputType | null;
};

export type HighlightUserBlacklistMinAggregateOutputType = {
	user_id: string | null;
	guild_id: string | null;
	target_id: string | null;
};

export type HighlightUserBlacklistMaxAggregateOutputType = {
	user_id: string | null;
	guild_id: string | null;
	target_id: string | null;
};

export type HighlightUserBlacklistCountAggregateOutputType = {
	user_id: number;
	guild_id: number;
	target_id: number;
	_all: number;
};

export type HighlightUserBlacklistMinAggregateInputType = {
	user_id?: true;
	guild_id?: true;
	target_id?: true;
};

export type HighlightUserBlacklistMaxAggregateInputType = {
	user_id?: true;
	guild_id?: true;
	target_id?: true;
};

export type HighlightUserBlacklistCountAggregateInputType = {
	user_id?: true;
	guild_id?: true;
	target_id?: true;
	_all?: true;
};

export type HighlightUserBlacklistAggregateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which HighlightUserBlacklist to aggregate.
	 */
	where?: Prisma.HighlightUserBlacklistWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of HighlightUserBlacklists to fetch.
	 */
	orderBy?:
		| Prisma.HighlightUserBlacklistOrderByWithRelationInput
		| Prisma.HighlightUserBlacklistOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.HighlightUserBlacklistWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` HighlightUserBlacklists from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` HighlightUserBlacklists.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned HighlightUserBlacklists
	 **/
	_count?: true | HighlightUserBlacklistCountAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: HighlightUserBlacklistMinAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: HighlightUserBlacklistMaxAggregateInputType;
};

export type GetHighlightUserBlacklistAggregateType<T extends HighlightUserBlacklistAggregateArgs> = {
	[P in keyof T & keyof AggregateHighlightUserBlacklist]: P extends "_count" | "count"
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateHighlightUserBlacklist[P]>
		: Prisma.GetScalarType<T[P], AggregateHighlightUserBlacklist[P]>;
};

export type HighlightUserBlacklistGroupByArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.HighlightUserBlacklistWhereInput;
	orderBy?:
		| Prisma.HighlightUserBlacklistOrderByWithAggregationInput
		| Prisma.HighlightUserBlacklistOrderByWithAggregationInput[];
	by: Prisma.HighlightUserBlacklistScalarFieldEnum[] | Prisma.HighlightUserBlacklistScalarFieldEnum;
	having?: Prisma.HighlightUserBlacklistScalarWhereWithAggregatesInput;
	take?: number;
	skip?: number;
	_count?: HighlightUserBlacklistCountAggregateInputType | true;
	_min?: HighlightUserBlacklistMinAggregateInputType;
	_max?: HighlightUserBlacklistMaxAggregateInputType;
};

export type HighlightUserBlacklistGroupByOutputType = {
	user_id: string;
	guild_id: string;
	target_id: string;
	_count: HighlightUserBlacklistCountAggregateOutputType | null;
	_min: HighlightUserBlacklistMinAggregateOutputType | null;
	_max: HighlightUserBlacklistMaxAggregateOutputType | null;
};

type GetHighlightUserBlacklistGroupByPayload<T extends HighlightUserBlacklistGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<HighlightUserBlacklistGroupByOutputType, T["by"]> & {
			[P in keyof T & keyof HighlightUserBlacklistGroupByOutputType]: P extends "_count"
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], HighlightUserBlacklistGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], HighlightUserBlacklistGroupByOutputType[P]>;
		}
	>
>;

export type HighlightUserBlacklistWhereInput = {
	AND?: Prisma.HighlightUserBlacklistWhereInput | Prisma.HighlightUserBlacklistWhereInput[];
	OR?: Prisma.HighlightUserBlacklistWhereInput[];
	NOT?: Prisma.HighlightUserBlacklistWhereInput | Prisma.HighlightUserBlacklistWhereInput[];
	user_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
	guild_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
	target_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
	highlight?: Prisma.XOR<Prisma.HighlightScalarRelationFilter, Prisma.HighlightWhereInput>;
};

export type HighlightUserBlacklistOrderByWithRelationInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	target_id?: Prisma.SortOrder;
	highlight?: Prisma.HighlightOrderByWithRelationInput;
};

export type HighlightUserBlacklistWhereUniqueInput = Prisma.AtLeast<
	{
		user_id_guild_id_target_id?: Prisma.HighlightUserBlacklistUser_idGuild_idTarget_idCompoundUniqueInput;
		AND?: Prisma.HighlightUserBlacklistWhereInput | Prisma.HighlightUserBlacklistWhereInput[];
		OR?: Prisma.HighlightUserBlacklistWhereInput[];
		NOT?: Prisma.HighlightUserBlacklistWhereInput | Prisma.HighlightUserBlacklistWhereInput[];
		user_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
		guild_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
		target_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
		highlight?: Prisma.XOR<Prisma.HighlightScalarRelationFilter, Prisma.HighlightWhereInput>;
	},
	"user_id_guild_id_target_id"
>;

export type HighlightUserBlacklistOrderByWithAggregationInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	target_id?: Prisma.SortOrder;
	_count?: Prisma.HighlightUserBlacklistCountOrderByAggregateInput;
	_max?: Prisma.HighlightUserBlacklistMaxOrderByAggregateInput;
	_min?: Prisma.HighlightUserBlacklistMinOrderByAggregateInput;
};

export type HighlightUserBlacklistScalarWhereWithAggregatesInput = {
	AND?:
		| Prisma.HighlightUserBlacklistScalarWhereWithAggregatesInput
		| Prisma.HighlightUserBlacklistScalarWhereWithAggregatesInput[];
	OR?: Prisma.HighlightUserBlacklistScalarWhereWithAggregatesInput[];
	NOT?:
		| Prisma.HighlightUserBlacklistScalarWhereWithAggregatesInput
		| Prisma.HighlightUserBlacklistScalarWhereWithAggregatesInput[];
	user_id?: Prisma.StringWithAggregatesFilter<"HighlightUserBlacklist"> | string;
	guild_id?: Prisma.StringWithAggregatesFilter<"HighlightUserBlacklist"> | string;
	target_id?: Prisma.StringWithAggregatesFilter<"HighlightUserBlacklist"> | string;
};

export type HighlightUserBlacklistCreateInput = {
	target_id: string;
	highlight: Prisma.HighlightCreateNestedOneWithoutUser_blacklistInput;
};

export type HighlightUserBlacklistUncheckedCreateInput = {
	user_id: string;
	guild_id: string;
	target_id: string;
};

export type HighlightUserBlacklistUpdateInput = {
	target_id?: Prisma.StringFieldUpdateOperationsInput | string;
	highlight?: Prisma.HighlightUpdateOneRequiredWithoutUser_blacklistNestedInput;
};

export type HighlightUserBlacklistUncheckedUpdateInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	target_id?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type HighlightUserBlacklistCreateManyInput = {
	user_id: string;
	guild_id: string;
	target_id: string;
};

export type HighlightUserBlacklistUpdateManyMutationInput = {
	target_id?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type HighlightUserBlacklistUncheckedUpdateManyInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	target_id?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type HighlightUserBlacklistListRelationFilter = {
	every?: Prisma.HighlightUserBlacklistWhereInput;
	some?: Prisma.HighlightUserBlacklistWhereInput;
	none?: Prisma.HighlightUserBlacklistWhereInput;
};

export type HighlightUserBlacklistOrderByRelationAggregateInput = {
	_count?: Prisma.SortOrder;
};

export type HighlightUserBlacklistUser_idGuild_idTarget_idCompoundUniqueInput = {
	user_id: string;
	guild_id: string;
	target_id: string;
};

export type HighlightUserBlacklistCountOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	target_id?: Prisma.SortOrder;
};

export type HighlightUserBlacklistMaxOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	target_id?: Prisma.SortOrder;
};

export type HighlightUserBlacklistMinOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	target_id?: Prisma.SortOrder;
};

export type HighlightUserBlacklistCreateNestedManyWithoutHighlightInput = {
	create?:
		| Prisma.XOR<
				Prisma.HighlightUserBlacklistCreateWithoutHighlightInput,
				Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput
		  >
		| Prisma.HighlightUserBlacklistCreateWithoutHighlightInput[]
		| Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput[];
	connectOrCreate?:
		| Prisma.HighlightUserBlacklistCreateOrConnectWithoutHighlightInput
		| Prisma.HighlightUserBlacklistCreateOrConnectWithoutHighlightInput[];
	createMany?: Prisma.HighlightUserBlacklistCreateManyHighlightInputEnvelope;
	connect?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
};

export type HighlightUserBlacklistUncheckedCreateNestedManyWithoutHighlightInput = {
	create?:
		| Prisma.XOR<
				Prisma.HighlightUserBlacklistCreateWithoutHighlightInput,
				Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput
		  >
		| Prisma.HighlightUserBlacklistCreateWithoutHighlightInput[]
		| Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput[];
	connectOrCreate?:
		| Prisma.HighlightUserBlacklistCreateOrConnectWithoutHighlightInput
		| Prisma.HighlightUserBlacklistCreateOrConnectWithoutHighlightInput[];
	createMany?: Prisma.HighlightUserBlacklistCreateManyHighlightInputEnvelope;
	connect?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
};

export type HighlightUserBlacklistUpdateManyWithoutHighlightNestedInput = {
	create?:
		| Prisma.XOR<
				Prisma.HighlightUserBlacklistCreateWithoutHighlightInput,
				Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput
		  >
		| Prisma.HighlightUserBlacklistCreateWithoutHighlightInput[]
		| Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput[];
	connectOrCreate?:
		| Prisma.HighlightUserBlacklistCreateOrConnectWithoutHighlightInput
		| Prisma.HighlightUserBlacklistCreateOrConnectWithoutHighlightInput[];
	upsert?:
		| Prisma.HighlightUserBlacklistUpsertWithWhereUniqueWithoutHighlightInput
		| Prisma.HighlightUserBlacklistUpsertWithWhereUniqueWithoutHighlightInput[];
	createMany?: Prisma.HighlightUserBlacklistCreateManyHighlightInputEnvelope;
	set?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
	disconnect?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
	delete?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
	connect?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
	update?:
		| Prisma.HighlightUserBlacklistUpdateWithWhereUniqueWithoutHighlightInput
		| Prisma.HighlightUserBlacklistUpdateWithWhereUniqueWithoutHighlightInput[];
	updateMany?:
		| Prisma.HighlightUserBlacklistUpdateManyWithWhereWithoutHighlightInput
		| Prisma.HighlightUserBlacklistUpdateManyWithWhereWithoutHighlightInput[];
	deleteMany?: Prisma.HighlightUserBlacklistScalarWhereInput | Prisma.HighlightUserBlacklistScalarWhereInput[];
};

export type HighlightUserBlacklistUncheckedUpdateManyWithoutHighlightNestedInput = {
	create?:
		| Prisma.XOR<
				Prisma.HighlightUserBlacklistCreateWithoutHighlightInput,
				Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput
		  >
		| Prisma.HighlightUserBlacklistCreateWithoutHighlightInput[]
		| Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput[];
	connectOrCreate?:
		| Prisma.HighlightUserBlacklistCreateOrConnectWithoutHighlightInput
		| Prisma.HighlightUserBlacklistCreateOrConnectWithoutHighlightInput[];
	upsert?:
		| Prisma.HighlightUserBlacklistUpsertWithWhereUniqueWithoutHighlightInput
		| Prisma.HighlightUserBlacklistUpsertWithWhereUniqueWithoutHighlightInput[];
	createMany?: Prisma.HighlightUserBlacklistCreateManyHighlightInputEnvelope;
	set?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
	disconnect?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
	delete?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
	connect?: Prisma.HighlightUserBlacklistWhereUniqueInput | Prisma.HighlightUserBlacklistWhereUniqueInput[];
	update?:
		| Prisma.HighlightUserBlacklistUpdateWithWhereUniqueWithoutHighlightInput
		| Prisma.HighlightUserBlacklistUpdateWithWhereUniqueWithoutHighlightInput[];
	updateMany?:
		| Prisma.HighlightUserBlacklistUpdateManyWithWhereWithoutHighlightInput
		| Prisma.HighlightUserBlacklistUpdateManyWithWhereWithoutHighlightInput[];
	deleteMany?: Prisma.HighlightUserBlacklistScalarWhereInput | Prisma.HighlightUserBlacklistScalarWhereInput[];
};

export type HighlightUserBlacklistCreateWithoutHighlightInput = {
	target_id: string;
};

export type HighlightUserBlacklistUncheckedCreateWithoutHighlightInput = {
	target_id: string;
};

export type HighlightUserBlacklistCreateOrConnectWithoutHighlightInput = {
	where: Prisma.HighlightUserBlacklistWhereUniqueInput;
	create: Prisma.XOR<
		Prisma.HighlightUserBlacklistCreateWithoutHighlightInput,
		Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput
	>;
};

export type HighlightUserBlacklistCreateManyHighlightInputEnvelope = {
	data:
		| Prisma.HighlightUserBlacklistCreateManyHighlightInput
		| Prisma.HighlightUserBlacklistCreateManyHighlightInput[];
	skipDuplicates?: boolean;
};

export type HighlightUserBlacklistUpsertWithWhereUniqueWithoutHighlightInput = {
	where: Prisma.HighlightUserBlacklistWhereUniqueInput;
	update: Prisma.XOR<
		Prisma.HighlightUserBlacklistUpdateWithoutHighlightInput,
		Prisma.HighlightUserBlacklistUncheckedUpdateWithoutHighlightInput
	>;
	create: Prisma.XOR<
		Prisma.HighlightUserBlacklistCreateWithoutHighlightInput,
		Prisma.HighlightUserBlacklistUncheckedCreateWithoutHighlightInput
	>;
};

export type HighlightUserBlacklistUpdateWithWhereUniqueWithoutHighlightInput = {
	where: Prisma.HighlightUserBlacklistWhereUniqueInput;
	data: Prisma.XOR<
		Prisma.HighlightUserBlacklistUpdateWithoutHighlightInput,
		Prisma.HighlightUserBlacklistUncheckedUpdateWithoutHighlightInput
	>;
};

export type HighlightUserBlacklistUpdateManyWithWhereWithoutHighlightInput = {
	where: Prisma.HighlightUserBlacklistScalarWhereInput;
	data: Prisma.XOR<
		Prisma.HighlightUserBlacklistUpdateManyMutationInput,
		Prisma.HighlightUserBlacklistUncheckedUpdateManyWithoutHighlightInput
	>;
};

export type HighlightUserBlacklistScalarWhereInput = {
	AND?: Prisma.HighlightUserBlacklistScalarWhereInput | Prisma.HighlightUserBlacklistScalarWhereInput[];
	OR?: Prisma.HighlightUserBlacklistScalarWhereInput[];
	NOT?: Prisma.HighlightUserBlacklistScalarWhereInput | Prisma.HighlightUserBlacklistScalarWhereInput[];
	user_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
	guild_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
	target_id?: Prisma.StringFilter<"HighlightUserBlacklist"> | string;
};

export type HighlightUserBlacklistCreateManyHighlightInput = {
	target_id: string;
};

export type HighlightUserBlacklistUpdateWithoutHighlightInput = {
	target_id?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type HighlightUserBlacklistUncheckedUpdateWithoutHighlightInput = {
	target_id?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type HighlightUserBlacklistUncheckedUpdateManyWithoutHighlightInput = {
	target_id?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type HighlightUserBlacklistSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		target_id?: boolean;
		highlight?: boolean | Prisma.HighlightDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["highlightUserBlacklist"]
>;

export type HighlightUserBlacklistSelectCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		target_id?: boolean;
		highlight?: boolean | Prisma.HighlightDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["highlightUserBlacklist"]
>;

export type HighlightUserBlacklistSelectUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		target_id?: boolean;
		highlight?: boolean | Prisma.HighlightDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["highlightUserBlacklist"]
>;

export type HighlightUserBlacklistSelectScalar = {
	user_id?: boolean;
	guild_id?: boolean;
	target_id?: boolean;
};

export type HighlightUserBlacklistOmit<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<"user_id" | "guild_id" | "target_id", ExtArgs["result"]["highlightUserBlacklist"]>;
export type HighlightUserBlacklistInclude<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	highlight?: boolean | Prisma.HighlightDefaultArgs<ExtArgs>;
};
export type HighlightUserBlacklistIncludeCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	highlight?: boolean | Prisma.HighlightDefaultArgs<ExtArgs>;
};
export type HighlightUserBlacklistIncludeUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	highlight?: boolean | Prisma.HighlightDefaultArgs<ExtArgs>;
};

export type $HighlightUserBlacklistPayload<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	name: "HighlightUserBlacklist";
	objects: {
		highlight: Prisma.$HighlightPayload<ExtArgs>;
	};
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			user_id: string;
			guild_id: string;
			target_id: string;
		},
		ExtArgs["result"]["highlightUserBlacklist"]
	>;
	composites: {};
};

export type HighlightUserBlacklistGetPayload<S extends boolean | null | undefined | HighlightUserBlacklistDefaultArgs> =
	runtime.Types.Result.GetResult<Prisma.$HighlightUserBlacklistPayload, S>;

export type HighlightUserBlacklistCountArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<HighlightUserBlacklistFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
	select?: HighlightUserBlacklistCountAggregateInputType | true;
};

export interface HighlightUserBlacklistDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> {
	[K: symbol]: {
		types: Prisma.TypeMap<ExtArgs>["model"]["HighlightUserBlacklist"];
		meta: { name: "HighlightUserBlacklist" };
	};
	/**
	 * Find zero or one HighlightUserBlacklist that matches the filter.
	 * @param {HighlightUserBlacklistFindUniqueArgs} args - Arguments to find a HighlightUserBlacklist
	 * @example
	 * // Get one HighlightUserBlacklist
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends HighlightUserBlacklistFindUniqueArgs>(
		args: Prisma.SelectSubset<T, HighlightUserBlacklistFindUniqueArgs<ExtArgs>>
	): Prisma.Prisma__HighlightUserBlacklistClient<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"findUnique",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find one HighlightUserBlacklist that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {HighlightUserBlacklistFindUniqueOrThrowArgs} args - Arguments to find a HighlightUserBlacklist
	 * @example
	 * // Get one HighlightUserBlacklist
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends HighlightUserBlacklistFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, HighlightUserBlacklistFindUniqueOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__HighlightUserBlacklistClient<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"findUniqueOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first HighlightUserBlacklist that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightUserBlacklistFindFirstArgs} args - Arguments to find a HighlightUserBlacklist
	 * @example
	 * // Get one HighlightUserBlacklist
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends HighlightUserBlacklistFindFirstArgs>(
		args?: Prisma.SelectSubset<T, HighlightUserBlacklistFindFirstArgs<ExtArgs>>
	): Prisma.Prisma__HighlightUserBlacklistClient<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"findFirst",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first HighlightUserBlacklist that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightUserBlacklistFindFirstOrThrowArgs} args - Arguments to find a HighlightUserBlacklist
	 * @example
	 * // Get one HighlightUserBlacklist
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends HighlightUserBlacklistFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, HighlightUserBlacklistFindFirstOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__HighlightUserBlacklistClient<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"findFirstOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find zero or more HighlightUserBlacklists that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightUserBlacklistFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all HighlightUserBlacklists
	 * const highlightUserBlacklists = await prisma.highlightUserBlacklist.findMany()
	 *
	 * // Get first 10 HighlightUserBlacklists
	 * const highlightUserBlacklists = await prisma.highlightUserBlacklist.findMany({ take: 10 })
	 *
	 * // Only select the `user_id`
	 * const highlightUserBlacklistWithUser_idOnly = await prisma.highlightUserBlacklist.findMany({ select: { user_id: true } })
	 *
	 */
	findMany<T extends HighlightUserBlacklistFindManyArgs>(
		args?: Prisma.SelectSubset<T, HighlightUserBlacklistFindManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"findMany",
			GlobalOmitOptions
		>
	>;

	/**
	 * Create a HighlightUserBlacklist.
	 * @param {HighlightUserBlacklistCreateArgs} args - Arguments to create a HighlightUserBlacklist.
	 * @example
	 * // Create one HighlightUserBlacklist
	 * const HighlightUserBlacklist = await prisma.highlightUserBlacklist.create({
	 *   data: {
	 *     // ... data to create a HighlightUserBlacklist
	 *   }
	 * })
	 *
	 */
	create<T extends HighlightUserBlacklistCreateArgs>(
		args: Prisma.SelectSubset<T, HighlightUserBlacklistCreateArgs<ExtArgs>>
	): Prisma.Prisma__HighlightUserBlacklistClient<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"create",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Create many HighlightUserBlacklists.
	 * @param {HighlightUserBlacklistCreateManyArgs} args - Arguments to create many HighlightUserBlacklists.
	 * @example
	 * // Create many HighlightUserBlacklists
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends HighlightUserBlacklistCreateManyArgs>(
		args?: Prisma.SelectSubset<T, HighlightUserBlacklistCreateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Create many HighlightUserBlacklists and returns the data saved in the database.
	 * @param {HighlightUserBlacklistCreateManyAndReturnArgs} args - Arguments to create many HighlightUserBlacklists.
	 * @example
	 * // Create many HighlightUserBlacklists
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.createManyAndReturn({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Create many HighlightUserBlacklists and only return the `user_id`
	 * const highlightUserBlacklistWithUser_idOnly = await prisma.highlightUserBlacklist.createManyAndReturn({
	 *   select: { user_id: true },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	createManyAndReturn<T extends HighlightUserBlacklistCreateManyAndReturnArgs>(
		args?: Prisma.SelectSubset<T, HighlightUserBlacklistCreateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"createManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Delete a HighlightUserBlacklist.
	 * @param {HighlightUserBlacklistDeleteArgs} args - Arguments to delete one HighlightUserBlacklist.
	 * @example
	 * // Delete one HighlightUserBlacklist
	 * const HighlightUserBlacklist = await prisma.highlightUserBlacklist.delete({
	 *   where: {
	 *     // ... filter to delete one HighlightUserBlacklist
	 *   }
	 * })
	 *
	 */
	delete<T extends HighlightUserBlacklistDeleteArgs>(
		args: Prisma.SelectSubset<T, HighlightUserBlacklistDeleteArgs<ExtArgs>>
	): Prisma.Prisma__HighlightUserBlacklistClient<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"delete",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Update one HighlightUserBlacklist.
	 * @param {HighlightUserBlacklistUpdateArgs} args - Arguments to update one HighlightUserBlacklist.
	 * @example
	 * // Update one HighlightUserBlacklist
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends HighlightUserBlacklistUpdateArgs>(
		args: Prisma.SelectSubset<T, HighlightUserBlacklistUpdateArgs<ExtArgs>>
	): Prisma.Prisma__HighlightUserBlacklistClient<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"update",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Delete zero or more HighlightUserBlacklists.
	 * @param {HighlightUserBlacklistDeleteManyArgs} args - Arguments to filter HighlightUserBlacklists to delete.
	 * @example
	 * // Delete a few HighlightUserBlacklists
	 * const { count } = await prisma.highlightUserBlacklist.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends HighlightUserBlacklistDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, HighlightUserBlacklistDeleteManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more HighlightUserBlacklists.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightUserBlacklistUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many HighlightUserBlacklists
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends HighlightUserBlacklistUpdateManyArgs>(
		args: Prisma.SelectSubset<T, HighlightUserBlacklistUpdateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more HighlightUserBlacklists and returns the data updated in the database.
	 * @param {HighlightUserBlacklistUpdateManyAndReturnArgs} args - Arguments to update many HighlightUserBlacklists.
	 * @example
	 * // Update many HighlightUserBlacklists
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.updateManyAndReturn({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Update zero or more HighlightUserBlacklists and only return the `user_id`
	 * const highlightUserBlacklistWithUser_idOnly = await prisma.highlightUserBlacklist.updateManyAndReturn({
	 *   select: { user_id: true },
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	updateManyAndReturn<T extends HighlightUserBlacklistUpdateManyAndReturnArgs>(
		args: Prisma.SelectSubset<T, HighlightUserBlacklistUpdateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"updateManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Create or update one HighlightUserBlacklist.
	 * @param {HighlightUserBlacklistUpsertArgs} args - Arguments to update or create a HighlightUserBlacklist.
	 * @example
	 * // Update or create a HighlightUserBlacklist
	 * const highlightUserBlacklist = await prisma.highlightUserBlacklist.upsert({
	 *   create: {
	 *     // ... data to create a HighlightUserBlacklist
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the HighlightUserBlacklist we want to update
	 *   }
	 * })
	 */
	upsert<T extends HighlightUserBlacklistUpsertArgs>(
		args: Prisma.SelectSubset<T, HighlightUserBlacklistUpsertArgs<ExtArgs>>
	): Prisma.Prisma__HighlightUserBlacklistClient<
		runtime.Types.Result.GetResult<
			Prisma.$HighlightUserBlacklistPayload<ExtArgs>,
			T,
			"upsert",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Count the number of HighlightUserBlacklists.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightUserBlacklistCountArgs} args - Arguments to filter HighlightUserBlacklists to count.
	 * @example
	 * // Count the number of HighlightUserBlacklists
	 * const count = await prisma.highlightUserBlacklist.count({
	 *   where: {
	 *     // ... the filter for the HighlightUserBlacklists we want to count
	 *   }
	 * })
	 **/
	count<T extends HighlightUserBlacklistCountArgs>(
		args?: Prisma.Subset<T, HighlightUserBlacklistCountArgs>
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<"select", any>
			? T["select"] extends true
				? number
				: Prisma.GetScalarType<T["select"], HighlightUserBlacklistCountAggregateOutputType>
			: number
	>;

	/**
	 * Allows you to perform aggregations operations on a HighlightUserBlacklist.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightUserBlacklistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends HighlightUserBlacklistAggregateArgs>(
		args: Prisma.Subset<T, HighlightUserBlacklistAggregateArgs>
	): Prisma.PrismaPromise<GetHighlightUserBlacklistAggregateType<T>>;

	/**
	 * Group by HighlightUserBlacklist.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightUserBlacklistGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends HighlightUserBlacklistGroupByArgs,
		HasSelectOrTake extends Prisma.Or<
			Prisma.Extends<"skip", Prisma.Keys<T>>,
			Prisma.Extends<"take", Prisma.Keys<T>>
		>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: HighlightUserBlacklistGroupByArgs["orderBy"] }
			: { orderBy?: HighlightUserBlacklistGroupByArgs["orderBy"] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T["having"]>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
					}[HavingFields]
				: "take" extends Prisma.Keys<T>
					? "orderBy" extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: "skip" extends Prisma.Keys<T>
						? "orderBy" extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields
											? never
											: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
	>(
		args: Prisma.SubsetIntersection<T, HighlightUserBlacklistGroupByArgs, OrderByArg> & InputErrors
	): {} extends InputErrors ? GetHighlightUserBlacklistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
	/**
	 * Fields of the HighlightUserBlacklist model
	 */
	readonly fields: HighlightUserBlacklistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HighlightUserBlacklist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HighlightUserBlacklistClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: "PrismaPromise";
	highlight<T extends Prisma.HighlightDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.HighlightDefaultArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		| runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>
		| Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>;
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
	): runtime.Types.Utils.JsPromise<T | TResult>;
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the HighlightUserBlacklist model
 */
export interface HighlightUserBlacklistFieldRefs {
	readonly user_id: Prisma.FieldRef<"HighlightUserBlacklist", "String">;
	readonly guild_id: Prisma.FieldRef<"HighlightUserBlacklist", "String">;
	readonly target_id: Prisma.FieldRef<"HighlightUserBlacklist", "String">;
}

// Custom InputTypes
/**
 * HighlightUserBlacklist findUnique
 */
export type HighlightUserBlacklistFindUniqueArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * Filter, which HighlightUserBlacklist to fetch.
	 */
	where: Prisma.HighlightUserBlacklistWhereUniqueInput;
};

/**
 * HighlightUserBlacklist findUniqueOrThrow
 */
export type HighlightUserBlacklistFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * Filter, which HighlightUserBlacklist to fetch.
	 */
	where: Prisma.HighlightUserBlacklistWhereUniqueInput;
};

/**
 * HighlightUserBlacklist findFirst
 */
export type HighlightUserBlacklistFindFirstArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * Filter, which HighlightUserBlacklist to fetch.
	 */
	where?: Prisma.HighlightUserBlacklistWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of HighlightUserBlacklists to fetch.
	 */
	orderBy?:
		| Prisma.HighlightUserBlacklistOrderByWithRelationInput
		| Prisma.HighlightUserBlacklistOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for HighlightUserBlacklists.
	 */
	cursor?: Prisma.HighlightUserBlacklistWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` HighlightUserBlacklists from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` HighlightUserBlacklists.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of HighlightUserBlacklists.
	 */
	distinct?: Prisma.HighlightUserBlacklistScalarFieldEnum | Prisma.HighlightUserBlacklistScalarFieldEnum[];
};

/**
 * HighlightUserBlacklist findFirstOrThrow
 */
export type HighlightUserBlacklistFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * Filter, which HighlightUserBlacklist to fetch.
	 */
	where?: Prisma.HighlightUserBlacklistWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of HighlightUserBlacklists to fetch.
	 */
	orderBy?:
		| Prisma.HighlightUserBlacklistOrderByWithRelationInput
		| Prisma.HighlightUserBlacklistOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for HighlightUserBlacklists.
	 */
	cursor?: Prisma.HighlightUserBlacklistWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` HighlightUserBlacklists from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` HighlightUserBlacklists.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of HighlightUserBlacklists.
	 */
	distinct?: Prisma.HighlightUserBlacklistScalarFieldEnum | Prisma.HighlightUserBlacklistScalarFieldEnum[];
};

/**
 * HighlightUserBlacklist findMany
 */
export type HighlightUserBlacklistFindManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * Filter, which HighlightUserBlacklists to fetch.
	 */
	where?: Prisma.HighlightUserBlacklistWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of HighlightUserBlacklists to fetch.
	 */
	orderBy?:
		| Prisma.HighlightUserBlacklistOrderByWithRelationInput
		| Prisma.HighlightUserBlacklistOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing HighlightUserBlacklists.
	 */
	cursor?: Prisma.HighlightUserBlacklistWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` HighlightUserBlacklists from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` HighlightUserBlacklists.
	 */
	skip?: number;
	distinct?: Prisma.HighlightUserBlacklistScalarFieldEnum | Prisma.HighlightUserBlacklistScalarFieldEnum[];
};

/**
 * HighlightUserBlacklist create
 */
export type HighlightUserBlacklistCreateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * The data needed to create a HighlightUserBlacklist.
	 */
	data: Prisma.XOR<Prisma.HighlightUserBlacklistCreateInput, Prisma.HighlightUserBlacklistUncheckedCreateInput>;
};

/**
 * HighlightUserBlacklist createMany
 */
export type HighlightUserBlacklistCreateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to create many HighlightUserBlacklists.
	 */
	data: Prisma.HighlightUserBlacklistCreateManyInput | Prisma.HighlightUserBlacklistCreateManyInput[];
	skipDuplicates?: boolean;
};

/**
 * HighlightUserBlacklist createManyAndReturn
 */
export type HighlightUserBlacklistCreateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelectCreateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * The data used to create many HighlightUserBlacklists.
	 */
	data: Prisma.HighlightUserBlacklistCreateManyInput | Prisma.HighlightUserBlacklistCreateManyInput[];
	skipDuplicates?: boolean;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * HighlightUserBlacklist update
 */
export type HighlightUserBlacklistUpdateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * The data needed to update a HighlightUserBlacklist.
	 */
	data: Prisma.XOR<Prisma.HighlightUserBlacklistUpdateInput, Prisma.HighlightUserBlacklistUncheckedUpdateInput>;
	/**
	 * Choose, which HighlightUserBlacklist to update.
	 */
	where: Prisma.HighlightUserBlacklistWhereUniqueInput;
};

/**
 * HighlightUserBlacklist updateMany
 */
export type HighlightUserBlacklistUpdateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to update HighlightUserBlacklists.
	 */
	data: Prisma.XOR<
		Prisma.HighlightUserBlacklistUpdateManyMutationInput,
		Prisma.HighlightUserBlacklistUncheckedUpdateManyInput
	>;
	/**
	 * Filter which HighlightUserBlacklists to update
	 */
	where?: Prisma.HighlightUserBlacklistWhereInput;
	/**
	 * Limit how many HighlightUserBlacklists to update.
	 */
	limit?: number;
};

/**
 * HighlightUserBlacklist updateManyAndReturn
 */
export type HighlightUserBlacklistUpdateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelectUpdateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * The data used to update HighlightUserBlacklists.
	 */
	data: Prisma.XOR<
		Prisma.HighlightUserBlacklistUpdateManyMutationInput,
		Prisma.HighlightUserBlacklistUncheckedUpdateManyInput
	>;
	/**
	 * Filter which HighlightUserBlacklists to update
	 */
	where?: Prisma.HighlightUserBlacklistWhereInput;
	/**
	 * Limit how many HighlightUserBlacklists to update.
	 */
	limit?: number;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * HighlightUserBlacklist upsert
 */
export type HighlightUserBlacklistUpsertArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * The filter to search for the HighlightUserBlacklist to update in case it exists.
	 */
	where: Prisma.HighlightUserBlacklistWhereUniqueInput;
	/**
	 * In case the HighlightUserBlacklist found by the `where` argument doesn't exist, create a new HighlightUserBlacklist with this data.
	 */
	create: Prisma.XOR<Prisma.HighlightUserBlacklistCreateInput, Prisma.HighlightUserBlacklistUncheckedCreateInput>;
	/**
	 * In case the HighlightUserBlacklist was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.HighlightUserBlacklistUpdateInput, Prisma.HighlightUserBlacklistUncheckedUpdateInput>;
};

/**
 * HighlightUserBlacklist delete
 */
export type HighlightUserBlacklistDeleteArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
	/**
	 * Filter which HighlightUserBlacklist to delete.
	 */
	where: Prisma.HighlightUserBlacklistWhereUniqueInput;
};

/**
 * HighlightUserBlacklist deleteMany
 */
export type HighlightUserBlacklistDeleteManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which HighlightUserBlacklists to delete
	 */
	where?: Prisma.HighlightUserBlacklistWhereInput;
	/**
	 * Limit how many HighlightUserBlacklists to delete.
	 */
	limit?: number;
};

/**
 * HighlightUserBlacklist without action
 */
export type HighlightUserBlacklistDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightUserBlacklist
	 */
	select?: Prisma.HighlightUserBlacklistSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightUserBlacklist
	 */
	omit?: Prisma.HighlightUserBlacklistOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightUserBlacklistInclude<ExtArgs> | null;
};
