/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Highlight` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model Highlight
 *
 */
export type HighlightModel = runtime.Types.Result.DefaultSelection<Prisma.$HighlightPayload>;

export type AggregateHighlight = {
	_count: HighlightCountAggregateOutputType | null;
	_min: HighlightMinAggregateOutputType | null;
	_max: HighlightMaxAggregateOutputType | null;
};

export type HighlightMinAggregateOutputType = {
	user_id: string | null;
	guild_id: string | null;
};

export type HighlightMaxAggregateOutputType = {
	user_id: string | null;
	guild_id: string | null;
};

export type HighlightCountAggregateOutputType = {
	user_id: number;
	guild_id: number;
	patterns: number;
	user_blacklist: number;
	_all: number;
};

export type HighlightMinAggregateInputType = {
	user_id?: true;
	guild_id?: true;
};

export type HighlightMaxAggregateInputType = {
	user_id?: true;
	guild_id?: true;
};

export type HighlightCountAggregateInputType = {
	user_id?: true;
	guild_id?: true;
	patterns?: true;
	user_blacklist?: true;
	_all?: true;
};

export type HighlightAggregateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which Highlight to aggregate.
	 */
	where?: Prisma.HighlightWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Highlights to fetch.
	 */
	orderBy?: Prisma.HighlightOrderByWithRelationInput | Prisma.HighlightOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.HighlightWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Highlights from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Highlights.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned Highlights
	 **/
	_count?: true | HighlightCountAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: HighlightMinAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: HighlightMaxAggregateInputType;
};

export type GetHighlightAggregateType<T extends HighlightAggregateArgs> = {
	[P in keyof T & keyof AggregateHighlight]: P extends "_count" | "count"
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateHighlight[P]>
		: Prisma.GetScalarType<T[P], AggregateHighlight[P]>;
};

export type HighlightGroupByArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.HighlightWhereInput;
	orderBy?: Prisma.HighlightOrderByWithAggregationInput | Prisma.HighlightOrderByWithAggregationInput[];
	by: Prisma.HighlightScalarFieldEnum[] | Prisma.HighlightScalarFieldEnum;
	having?: Prisma.HighlightScalarWhereWithAggregatesInput;
	take?: number;
	skip?: number;
	_count?: HighlightCountAggregateInputType | true;
	_min?: HighlightMinAggregateInputType;
	_max?: HighlightMaxAggregateInputType;
};

export type HighlightGroupByOutputType = {
	user_id: string;
	guild_id: string;
	patterns: string[];
	user_blacklist: string[];
	_count: HighlightCountAggregateOutputType | null;
	_min: HighlightMinAggregateOutputType | null;
	_max: HighlightMaxAggregateOutputType | null;
};

type GetHighlightGroupByPayload<T extends HighlightGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<HighlightGroupByOutputType, T["by"]> & {
			[P in keyof T & keyof HighlightGroupByOutputType]: P extends "_count"
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], HighlightGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], HighlightGroupByOutputType[P]>;
		}
	>
>;

export type HighlightWhereInput = {
	AND?: Prisma.HighlightWhereInput | Prisma.HighlightWhereInput[];
	OR?: Prisma.HighlightWhereInput[];
	NOT?: Prisma.HighlightWhereInput | Prisma.HighlightWhereInput[];
	user_id?: Prisma.StringFilter<"Highlight"> | string;
	guild_id?: Prisma.StringFilter<"Highlight"> | string;
	patterns?: Prisma.StringNullableListFilter<"Highlight">;
	user_blacklist?: Prisma.StringNullableListFilter<"Highlight">;
	channel_scoping?: Prisma.HighlightChannelScopingListRelationFilter;
	guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>;
};

export type HighlightOrderByWithRelationInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	patterns?: Prisma.SortOrder;
	user_blacklist?: Prisma.SortOrder;
	channel_scoping?: Prisma.HighlightChannelScopingOrderByRelationAggregateInput;
	guild?: Prisma.GuildOrderByWithRelationInput;
};

export type HighlightWhereUniqueInput = Prisma.AtLeast<
	{
		user_id_guild_id?: Prisma.HighlightUser_idGuild_idCompoundUniqueInput;
		AND?: Prisma.HighlightWhereInput | Prisma.HighlightWhereInput[];
		OR?: Prisma.HighlightWhereInput[];
		NOT?: Prisma.HighlightWhereInput | Prisma.HighlightWhereInput[];
		user_id?: Prisma.StringFilter<"Highlight"> | string;
		guild_id?: Prisma.StringFilter<"Highlight"> | string;
		patterns?: Prisma.StringNullableListFilter<"Highlight">;
		user_blacklist?: Prisma.StringNullableListFilter<"Highlight">;
		channel_scoping?: Prisma.HighlightChannelScopingListRelationFilter;
		guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>;
	},
	"user_id_guild_id"
>;

export type HighlightOrderByWithAggregationInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	patterns?: Prisma.SortOrder;
	user_blacklist?: Prisma.SortOrder;
	_count?: Prisma.HighlightCountOrderByAggregateInput;
	_max?: Prisma.HighlightMaxOrderByAggregateInput;
	_min?: Prisma.HighlightMinOrderByAggregateInput;
};

export type HighlightScalarWhereWithAggregatesInput = {
	AND?: Prisma.HighlightScalarWhereWithAggregatesInput | Prisma.HighlightScalarWhereWithAggregatesInput[];
	OR?: Prisma.HighlightScalarWhereWithAggregatesInput[];
	NOT?: Prisma.HighlightScalarWhereWithAggregatesInput | Prisma.HighlightScalarWhereWithAggregatesInput[];
	user_id?: Prisma.StringWithAggregatesFilter<"Highlight"> | string;
	guild_id?: Prisma.StringWithAggregatesFilter<"Highlight"> | string;
	patterns?: Prisma.StringNullableListFilter<"Highlight">;
	user_blacklist?: Prisma.StringNullableListFilter<"Highlight">;
};

export type HighlightCreateInput = {
	user_id: string;
	patterns?: Prisma.HighlightCreatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightCreateuser_blacklistInput | string[];
	channel_scoping?: Prisma.HighlightChannelScopingCreateNestedManyWithoutHighlightInput;
	guild: Prisma.GuildCreateNestedOneWithoutHighlightsInput;
};

export type HighlightUncheckedCreateInput = {
	user_id: string;
	guild_id: string;
	patterns?: Prisma.HighlightCreatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightCreateuser_blacklistInput | string[];
	channel_scoping?: Prisma.HighlightChannelScopingUncheckedCreateNestedManyWithoutHighlightInput;
};

export type HighlightUpdateInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
	channel_scoping?: Prisma.HighlightChannelScopingUpdateManyWithoutHighlightNestedInput;
	guild?: Prisma.GuildUpdateOneRequiredWithoutHighlightsNestedInput;
};

export type HighlightUncheckedUpdateInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
	channel_scoping?: Prisma.HighlightChannelScopingUncheckedUpdateManyWithoutHighlightNestedInput;
};

export type HighlightCreateManyInput = {
	user_id: string;
	guild_id: string;
	patterns?: Prisma.HighlightCreatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightCreateuser_blacklistInput | string[];
};

export type HighlightUpdateManyMutationInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
};

export type HighlightUncheckedUpdateManyInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
};

export type HighlightListRelationFilter = {
	every?: Prisma.HighlightWhereInput;
	some?: Prisma.HighlightWhereInput;
	none?: Prisma.HighlightWhereInput;
};

export type HighlightOrderByRelationAggregateInput = {
	_count?: Prisma.SortOrder;
};

export type HighlightUser_idGuild_idCompoundUniqueInput = {
	user_id: string;
	guild_id: string;
};

export type HighlightCountOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	patterns?: Prisma.SortOrder;
	user_blacklist?: Prisma.SortOrder;
};

export type HighlightMaxOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
};

export type HighlightMinOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
};

export type HighlightScalarRelationFilter = {
	is?: Prisma.HighlightWhereInput;
	isNot?: Prisma.HighlightWhereInput;
};

export type HighlightCreateNestedManyWithoutGuildInput = {
	create?:
		| Prisma.XOR<Prisma.HighlightCreateWithoutGuildInput, Prisma.HighlightUncheckedCreateWithoutGuildInput>
		| Prisma.HighlightCreateWithoutGuildInput[]
		| Prisma.HighlightUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.HighlightCreateOrConnectWithoutGuildInput
		| Prisma.HighlightCreateOrConnectWithoutGuildInput[];
	createMany?: Prisma.HighlightCreateManyGuildInputEnvelope;
	connect?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
};

export type HighlightUncheckedCreateNestedManyWithoutGuildInput = {
	create?:
		| Prisma.XOR<Prisma.HighlightCreateWithoutGuildInput, Prisma.HighlightUncheckedCreateWithoutGuildInput>
		| Prisma.HighlightCreateWithoutGuildInput[]
		| Prisma.HighlightUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.HighlightCreateOrConnectWithoutGuildInput
		| Prisma.HighlightCreateOrConnectWithoutGuildInput[];
	createMany?: Prisma.HighlightCreateManyGuildInputEnvelope;
	connect?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
};

export type HighlightUpdateManyWithoutGuildNestedInput = {
	create?:
		| Prisma.XOR<Prisma.HighlightCreateWithoutGuildInput, Prisma.HighlightUncheckedCreateWithoutGuildInput>
		| Prisma.HighlightCreateWithoutGuildInput[]
		| Prisma.HighlightUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.HighlightCreateOrConnectWithoutGuildInput
		| Prisma.HighlightCreateOrConnectWithoutGuildInput[];
	upsert?:
		| Prisma.HighlightUpsertWithWhereUniqueWithoutGuildInput
		| Prisma.HighlightUpsertWithWhereUniqueWithoutGuildInput[];
	createMany?: Prisma.HighlightCreateManyGuildInputEnvelope;
	set?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
	disconnect?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
	delete?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
	connect?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
	update?:
		| Prisma.HighlightUpdateWithWhereUniqueWithoutGuildInput
		| Prisma.HighlightUpdateWithWhereUniqueWithoutGuildInput[];
	updateMany?:
		| Prisma.HighlightUpdateManyWithWhereWithoutGuildInput
		| Prisma.HighlightUpdateManyWithWhereWithoutGuildInput[];
	deleteMany?: Prisma.HighlightScalarWhereInput | Prisma.HighlightScalarWhereInput[];
};

export type HighlightUncheckedUpdateManyWithoutGuildNestedInput = {
	create?:
		| Prisma.XOR<Prisma.HighlightCreateWithoutGuildInput, Prisma.HighlightUncheckedCreateWithoutGuildInput>
		| Prisma.HighlightCreateWithoutGuildInput[]
		| Prisma.HighlightUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.HighlightCreateOrConnectWithoutGuildInput
		| Prisma.HighlightCreateOrConnectWithoutGuildInput[];
	upsert?:
		| Prisma.HighlightUpsertWithWhereUniqueWithoutGuildInput
		| Prisma.HighlightUpsertWithWhereUniqueWithoutGuildInput[];
	createMany?: Prisma.HighlightCreateManyGuildInputEnvelope;
	set?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
	disconnect?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
	delete?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
	connect?: Prisma.HighlightWhereUniqueInput | Prisma.HighlightWhereUniqueInput[];
	update?:
		| Prisma.HighlightUpdateWithWhereUniqueWithoutGuildInput
		| Prisma.HighlightUpdateWithWhereUniqueWithoutGuildInput[];
	updateMany?:
		| Prisma.HighlightUpdateManyWithWhereWithoutGuildInput
		| Prisma.HighlightUpdateManyWithWhereWithoutGuildInput[];
	deleteMany?: Prisma.HighlightScalarWhereInput | Prisma.HighlightScalarWhereInput[];
};

export type HighlightCreatepatternsInput = {
	set: string[];
};

export type HighlightCreateuser_blacklistInput = {
	set: string[];
};

export type HighlightUpdatepatternsInput = {
	set?: string[];
	push?: string | string[];
};

export type HighlightUpdateuser_blacklistInput = {
	set?: string[];
	push?: string | string[];
};

export type HighlightCreateNestedOneWithoutChannel_scopingInput = {
	create?: Prisma.XOR<
		Prisma.HighlightCreateWithoutChannel_scopingInput,
		Prisma.HighlightUncheckedCreateWithoutChannel_scopingInput
	>;
	connectOrCreate?: Prisma.HighlightCreateOrConnectWithoutChannel_scopingInput;
	connect?: Prisma.HighlightWhereUniqueInput;
};

export type HighlightUpdateOneRequiredWithoutChannel_scopingNestedInput = {
	create?: Prisma.XOR<
		Prisma.HighlightCreateWithoutChannel_scopingInput,
		Prisma.HighlightUncheckedCreateWithoutChannel_scopingInput
	>;
	connectOrCreate?: Prisma.HighlightCreateOrConnectWithoutChannel_scopingInput;
	upsert?: Prisma.HighlightUpsertWithoutChannel_scopingInput;
	connect?: Prisma.HighlightWhereUniqueInput;
	update?: Prisma.XOR<
		Prisma.XOR<
			Prisma.HighlightUpdateToOneWithWhereWithoutChannel_scopingInput,
			Prisma.HighlightUpdateWithoutChannel_scopingInput
		>,
		Prisma.HighlightUncheckedUpdateWithoutChannel_scopingInput
	>;
};

export type HighlightCreateWithoutGuildInput = {
	user_id: string;
	patterns?: Prisma.HighlightCreatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightCreateuser_blacklistInput | string[];
	channel_scoping?: Prisma.HighlightChannelScopingCreateNestedManyWithoutHighlightInput;
};

export type HighlightUncheckedCreateWithoutGuildInput = {
	user_id: string;
	patterns?: Prisma.HighlightCreatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightCreateuser_blacklistInput | string[];
	channel_scoping?: Prisma.HighlightChannelScopingUncheckedCreateNestedManyWithoutHighlightInput;
};

export type HighlightCreateOrConnectWithoutGuildInput = {
	where: Prisma.HighlightWhereUniqueInput;
	create: Prisma.XOR<Prisma.HighlightCreateWithoutGuildInput, Prisma.HighlightUncheckedCreateWithoutGuildInput>;
};

export type HighlightCreateManyGuildInputEnvelope = {
	data: Prisma.HighlightCreateManyGuildInput | Prisma.HighlightCreateManyGuildInput[];
	skipDuplicates?: boolean;
};

export type HighlightUpsertWithWhereUniqueWithoutGuildInput = {
	where: Prisma.HighlightWhereUniqueInput;
	update: Prisma.XOR<Prisma.HighlightUpdateWithoutGuildInput, Prisma.HighlightUncheckedUpdateWithoutGuildInput>;
	create: Prisma.XOR<Prisma.HighlightCreateWithoutGuildInput, Prisma.HighlightUncheckedCreateWithoutGuildInput>;
};

export type HighlightUpdateWithWhereUniqueWithoutGuildInput = {
	where: Prisma.HighlightWhereUniqueInput;
	data: Prisma.XOR<Prisma.HighlightUpdateWithoutGuildInput, Prisma.HighlightUncheckedUpdateWithoutGuildInput>;
};

export type HighlightUpdateManyWithWhereWithoutGuildInput = {
	where: Prisma.HighlightScalarWhereInput;
	data: Prisma.XOR<Prisma.HighlightUpdateManyMutationInput, Prisma.HighlightUncheckedUpdateManyWithoutGuildInput>;
};

export type HighlightScalarWhereInput = {
	AND?: Prisma.HighlightScalarWhereInput | Prisma.HighlightScalarWhereInput[];
	OR?: Prisma.HighlightScalarWhereInput[];
	NOT?: Prisma.HighlightScalarWhereInput | Prisma.HighlightScalarWhereInput[];
	user_id?: Prisma.StringFilter<"Highlight"> | string;
	guild_id?: Prisma.StringFilter<"Highlight"> | string;
	patterns?: Prisma.StringNullableListFilter<"Highlight">;
	user_blacklist?: Prisma.StringNullableListFilter<"Highlight">;
};

export type HighlightCreateWithoutChannel_scopingInput = {
	user_id: string;
	patterns?: Prisma.HighlightCreatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightCreateuser_blacklistInput | string[];
	guild: Prisma.GuildCreateNestedOneWithoutHighlightsInput;
};

export type HighlightUncheckedCreateWithoutChannel_scopingInput = {
	user_id: string;
	guild_id: string;
	patterns?: Prisma.HighlightCreatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightCreateuser_blacklistInput | string[];
};

export type HighlightCreateOrConnectWithoutChannel_scopingInput = {
	where: Prisma.HighlightWhereUniqueInput;
	create: Prisma.XOR<
		Prisma.HighlightCreateWithoutChannel_scopingInput,
		Prisma.HighlightUncheckedCreateWithoutChannel_scopingInput
	>;
};

export type HighlightUpsertWithoutChannel_scopingInput = {
	update: Prisma.XOR<
		Prisma.HighlightUpdateWithoutChannel_scopingInput,
		Prisma.HighlightUncheckedUpdateWithoutChannel_scopingInput
	>;
	create: Prisma.XOR<
		Prisma.HighlightCreateWithoutChannel_scopingInput,
		Prisma.HighlightUncheckedCreateWithoutChannel_scopingInput
	>;
	where?: Prisma.HighlightWhereInput;
};

export type HighlightUpdateToOneWithWhereWithoutChannel_scopingInput = {
	where?: Prisma.HighlightWhereInput;
	data: Prisma.XOR<
		Prisma.HighlightUpdateWithoutChannel_scopingInput,
		Prisma.HighlightUncheckedUpdateWithoutChannel_scopingInput
	>;
};

export type HighlightUpdateWithoutChannel_scopingInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
	guild?: Prisma.GuildUpdateOneRequiredWithoutHighlightsNestedInput;
};

export type HighlightUncheckedUpdateWithoutChannel_scopingInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
};

export type HighlightCreateManyGuildInput = {
	user_id: string;
	patterns?: Prisma.HighlightCreatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightCreateuser_blacklistInput | string[];
};

export type HighlightUpdateWithoutGuildInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
	channel_scoping?: Prisma.HighlightChannelScopingUpdateManyWithoutHighlightNestedInput;
};

export type HighlightUncheckedUpdateWithoutGuildInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
	channel_scoping?: Prisma.HighlightChannelScopingUncheckedUpdateManyWithoutHighlightNestedInput;
};

export type HighlightUncheckedUpdateManyWithoutGuildInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	patterns?: Prisma.HighlightUpdatepatternsInput | string[];
	user_blacklist?: Prisma.HighlightUpdateuser_blacklistInput | string[];
};

/**
 * Count Type HighlightCountOutputType
 */

export type HighlightCountOutputType = {
	channel_scoping: number;
};

export type HighlightCountOutputTypeSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	channel_scoping?: boolean | HighlightCountOutputTypeCountChannel_scopingArgs;
};

/**
 * HighlightCountOutputType without action
 */
export type HighlightCountOutputTypeDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightCountOutputType
	 */
	select?: Prisma.HighlightCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * HighlightCountOutputType without action
 */
export type HighlightCountOutputTypeCountChannel_scopingArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.HighlightChannelScopingWhereInput;
};

export type HighlightSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		patterns?: boolean;
		user_blacklist?: boolean;
		channel_scoping?: boolean | Prisma.Highlight$channel_scopingArgs<ExtArgs>;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
		_count?: boolean | Prisma.HighlightCountOutputTypeDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["highlight"]
>;

export type HighlightSelectCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		patterns?: boolean;
		user_blacklist?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["highlight"]
>;

export type HighlightSelectUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		patterns?: boolean;
		user_blacklist?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["highlight"]
>;

export type HighlightSelectScalar = {
	user_id?: boolean;
	guild_id?: boolean;
	patterns?: boolean;
	user_blacklist?: boolean;
};

export type HighlightOmit<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<
	"user_id" | "guild_id" | "patterns" | "user_blacklist",
	ExtArgs["result"]["highlight"]
>;
export type HighlightInclude<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	channel_scoping?: boolean | Prisma.Highlight$channel_scopingArgs<ExtArgs>;
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	_count?: boolean | Prisma.HighlightCountOutputTypeDefaultArgs<ExtArgs>;
};
export type HighlightIncludeCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};
export type HighlightIncludeUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};

export type $HighlightPayload<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	name: "Highlight";
	objects: {
		channel_scoping: Prisma.$HighlightChannelScopingPayload<ExtArgs>[];
		guild: Prisma.$GuildPayload<ExtArgs>;
	};
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			user_id: string;
			guild_id: string;
			patterns: string[];
			user_blacklist: string[];
		},
		ExtArgs["result"]["highlight"]
	>;
	composites: {};
};

export type HighlightGetPayload<S extends boolean | null | undefined | HighlightDefaultArgs> =
	runtime.Types.Result.GetResult<Prisma.$HighlightPayload, S>;

export type HighlightCountArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<HighlightFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
	select?: HighlightCountAggregateInputType | true;
};

export interface HighlightDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> {
	[K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["Highlight"]; meta: { name: "Highlight" } };
	/**
	 * Find zero or one Highlight that matches the filter.
	 * @param {HighlightFindUniqueArgs} args - Arguments to find a Highlight
	 * @example
	 * // Get one Highlight
	 * const highlight = await prisma.highlight.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends HighlightFindUniqueArgs>(
		args: Prisma.SelectSubset<T, HighlightFindUniqueArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find one Highlight that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {HighlightFindUniqueOrThrowArgs} args - Arguments to find a Highlight
	 * @example
	 * // Get one Highlight
	 * const highlight = await prisma.highlight.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends HighlightFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, HighlightFindUniqueOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first Highlight that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightFindFirstArgs} args - Arguments to find a Highlight
	 * @example
	 * // Get one Highlight
	 * const highlight = await prisma.highlight.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends HighlightFindFirstArgs>(
		args?: Prisma.SelectSubset<T, HighlightFindFirstArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first Highlight that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightFindFirstOrThrowArgs} args - Arguments to find a Highlight
	 * @example
	 * // Get one Highlight
	 * const highlight = await prisma.highlight.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends HighlightFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, HighlightFindFirstOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find zero or more Highlights that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all Highlights
	 * const highlights = await prisma.highlight.findMany()
	 *
	 * // Get first 10 Highlights
	 * const highlights = await prisma.highlight.findMany({ take: 10 })
	 *
	 * // Only select the `user_id`
	 * const highlightWithUser_idOnly = await prisma.highlight.findMany({ select: { user_id: true } })
	 *
	 */
	findMany<T extends HighlightFindManyArgs>(
		args?: Prisma.SelectSubset<T, HighlightFindManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>
	>;

	/**
	 * Create a Highlight.
	 * @param {HighlightCreateArgs} args - Arguments to create a Highlight.
	 * @example
	 * // Create one Highlight
	 * const Highlight = await prisma.highlight.create({
	 *   data: {
	 *     // ... data to create a Highlight
	 *   }
	 * })
	 *
	 */
	create<T extends HighlightCreateArgs>(
		args: Prisma.SelectSubset<T, HighlightCreateArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "create", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Create many Highlights.
	 * @param {HighlightCreateManyArgs} args - Arguments to create many Highlights.
	 * @example
	 * // Create many Highlights
	 * const highlight = await prisma.highlight.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends HighlightCreateManyArgs>(
		args?: Prisma.SelectSubset<T, HighlightCreateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Create many Highlights and returns the data saved in the database.
	 * @param {HighlightCreateManyAndReturnArgs} args - Arguments to create many Highlights.
	 * @example
	 * // Create many Highlights
	 * const highlight = await prisma.highlight.createManyAndReturn({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Create many Highlights and only return the `user_id`
	 * const highlightWithUser_idOnly = await prisma.highlight.createManyAndReturn({
	 *   select: { user_id: true },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	createManyAndReturn<T extends HighlightCreateManyAndReturnArgs>(
		args?: Prisma.SelectSubset<T, HighlightCreateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>
	>;

	/**
	 * Delete a Highlight.
	 * @param {HighlightDeleteArgs} args - Arguments to delete one Highlight.
	 * @example
	 * // Delete one Highlight
	 * const Highlight = await prisma.highlight.delete({
	 *   where: {
	 *     // ... filter to delete one Highlight
	 *   }
	 * })
	 *
	 */
	delete<T extends HighlightDeleteArgs>(
		args: Prisma.SelectSubset<T, HighlightDeleteArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "delete", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Update one Highlight.
	 * @param {HighlightUpdateArgs} args - Arguments to update one Highlight.
	 * @example
	 * // Update one Highlight
	 * const highlight = await prisma.highlight.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends HighlightUpdateArgs>(
		args: Prisma.SelectSubset<T, HighlightUpdateArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "update", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Delete zero or more Highlights.
	 * @param {HighlightDeleteManyArgs} args - Arguments to filter Highlights to delete.
	 * @example
	 * // Delete a few Highlights
	 * const { count } = await prisma.highlight.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends HighlightDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, HighlightDeleteManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more Highlights.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many Highlights
	 * const highlight = await prisma.highlight.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends HighlightUpdateManyArgs>(
		args: Prisma.SelectSubset<T, HighlightUpdateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more Highlights and returns the data updated in the database.
	 * @param {HighlightUpdateManyAndReturnArgs} args - Arguments to update many Highlights.
	 * @example
	 * // Update many Highlights
	 * const highlight = await prisma.highlight.updateManyAndReturn({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Update zero or more Highlights and only return the `user_id`
	 * const highlightWithUser_idOnly = await prisma.highlight.updateManyAndReturn({
	 *   select: { user_id: true },
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	updateManyAndReturn<T extends HighlightUpdateManyAndReturnArgs>(
		args: Prisma.SelectSubset<T, HighlightUpdateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>
	>;

	/**
	 * Create or update one Highlight.
	 * @param {HighlightUpsertArgs} args - Arguments to update or create a Highlight.
	 * @example
	 * // Update or create a Highlight
	 * const highlight = await prisma.highlight.upsert({
	 *   create: {
	 *     // ... data to create a Highlight
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the Highlight we want to update
	 *   }
	 * })
	 */
	upsert<T extends HighlightUpsertArgs>(
		args: Prisma.SelectSubset<T, HighlightUpsertArgs<ExtArgs>>
	): Prisma.Prisma__HighlightClient<
		runtime.Types.Result.GetResult<Prisma.$HighlightPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Count the number of Highlights.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightCountArgs} args - Arguments to filter Highlights to count.
	 * @example
	 * // Count the number of Highlights
	 * const count = await prisma.highlight.count({
	 *   where: {
	 *     // ... the filter for the Highlights we want to count
	 *   }
	 * })
	 **/
	count<T extends HighlightCountArgs>(
		args?: Prisma.Subset<T, HighlightCountArgs>
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<"select", any>
			? T["select"] extends true
				? number
				: Prisma.GetScalarType<T["select"], HighlightCountAggregateOutputType>
			: number
	>;

	/**
	 * Allows you to perform aggregations operations on a Highlight.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends HighlightAggregateArgs>(
		args: Prisma.Subset<T, HighlightAggregateArgs>
	): Prisma.PrismaPromise<GetHighlightAggregateType<T>>;

	/**
	 * Group by Highlight.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {HighlightGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends HighlightGroupByArgs,
		HasSelectOrTake extends Prisma.Or<
			Prisma.Extends<"skip", Prisma.Keys<T>>,
			Prisma.Extends<"take", Prisma.Keys<T>>
		>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: HighlightGroupByArgs["orderBy"] }
			: { orderBy?: HighlightGroupByArgs["orderBy"] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T["having"]>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
					}[HavingFields]
				: "take" extends Prisma.Keys<T>
					? "orderBy" extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: "skip" extends Prisma.Keys<T>
						? "orderBy" extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields
											? never
											: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
	>(
		args: Prisma.SubsetIntersection<T, HighlightGroupByArgs, OrderByArg> & InputErrors
	): {} extends InputErrors ? GetHighlightGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
	/**
	 * Fields of the Highlight model
	 */
	readonly fields: HighlightFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Highlight.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HighlightClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: "PrismaPromise";
	channel_scoping<T extends Prisma.Highlight$channel_scopingArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.Highlight$channel_scopingArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		| runtime.Types.Result.GetResult<
				Prisma.$HighlightChannelScopingPayload<ExtArgs>,
				T,
				"findMany",
				GlobalOmitOptions
		  >
		| Null
	>;
	guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>
	): Prisma.Prisma__GuildClient<
		| runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>
		| Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>;
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
	): runtime.Types.Utils.JsPromise<T | TResult>;
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Highlight model
 */
export interface HighlightFieldRefs {
	readonly user_id: Prisma.FieldRef<"Highlight", "String">;
	readonly guild_id: Prisma.FieldRef<"Highlight", "String">;
	readonly patterns: Prisma.FieldRef<"Highlight", "String[]">;
	readonly user_blacklist: Prisma.FieldRef<"Highlight", "String[]">;
}

// Custom InputTypes
/**
 * Highlight findUnique
 */
export type HighlightFindUniqueArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * Filter, which Highlight to fetch.
	 */
	where: Prisma.HighlightWhereUniqueInput;
};

/**
 * Highlight findUniqueOrThrow
 */
export type HighlightFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * Filter, which Highlight to fetch.
	 */
	where: Prisma.HighlightWhereUniqueInput;
};

/**
 * Highlight findFirst
 */
export type HighlightFindFirstArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * Filter, which Highlight to fetch.
	 */
	where?: Prisma.HighlightWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Highlights to fetch.
	 */
	orderBy?: Prisma.HighlightOrderByWithRelationInput | Prisma.HighlightOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for Highlights.
	 */
	cursor?: Prisma.HighlightWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Highlights from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Highlights.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of Highlights.
	 */
	distinct?: Prisma.HighlightScalarFieldEnum | Prisma.HighlightScalarFieldEnum[];
};

/**
 * Highlight findFirstOrThrow
 */
export type HighlightFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * Filter, which Highlight to fetch.
	 */
	where?: Prisma.HighlightWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Highlights to fetch.
	 */
	orderBy?: Prisma.HighlightOrderByWithRelationInput | Prisma.HighlightOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for Highlights.
	 */
	cursor?: Prisma.HighlightWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Highlights from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Highlights.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of Highlights.
	 */
	distinct?: Prisma.HighlightScalarFieldEnum | Prisma.HighlightScalarFieldEnum[];
};

/**
 * Highlight findMany
 */
export type HighlightFindManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * Filter, which Highlights to fetch.
	 */
	where?: Prisma.HighlightWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Highlights to fetch.
	 */
	orderBy?: Prisma.HighlightOrderByWithRelationInput | Prisma.HighlightOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing Highlights.
	 */
	cursor?: Prisma.HighlightWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Highlights from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Highlights.
	 */
	skip?: number;
	distinct?: Prisma.HighlightScalarFieldEnum | Prisma.HighlightScalarFieldEnum[];
};

/**
 * Highlight create
 */
export type HighlightCreateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * The data needed to create a Highlight.
	 */
	data: Prisma.XOR<Prisma.HighlightCreateInput, Prisma.HighlightUncheckedCreateInput>;
};

/**
 * Highlight createMany
 */
export type HighlightCreateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to create many Highlights.
	 */
	data: Prisma.HighlightCreateManyInput | Prisma.HighlightCreateManyInput[];
	skipDuplicates?: boolean;
};

/**
 * Highlight createManyAndReturn
 */
export type HighlightCreateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelectCreateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * The data used to create many Highlights.
	 */
	data: Prisma.HighlightCreateManyInput | Prisma.HighlightCreateManyInput[];
	skipDuplicates?: boolean;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * Highlight update
 */
export type HighlightUpdateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * The data needed to update a Highlight.
	 */
	data: Prisma.XOR<Prisma.HighlightUpdateInput, Prisma.HighlightUncheckedUpdateInput>;
	/**
	 * Choose, which Highlight to update.
	 */
	where: Prisma.HighlightWhereUniqueInput;
};

/**
 * Highlight updateMany
 */
export type HighlightUpdateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to update Highlights.
	 */
	data: Prisma.XOR<Prisma.HighlightUpdateManyMutationInput, Prisma.HighlightUncheckedUpdateManyInput>;
	/**
	 * Filter which Highlights to update
	 */
	where?: Prisma.HighlightWhereInput;
	/**
	 * Limit how many Highlights to update.
	 */
	limit?: number;
};

/**
 * Highlight updateManyAndReturn
 */
export type HighlightUpdateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelectUpdateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * The data used to update Highlights.
	 */
	data: Prisma.XOR<Prisma.HighlightUpdateManyMutationInput, Prisma.HighlightUncheckedUpdateManyInput>;
	/**
	 * Filter which Highlights to update
	 */
	where?: Prisma.HighlightWhereInput;
	/**
	 * Limit how many Highlights to update.
	 */
	limit?: number;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * Highlight upsert
 */
export type HighlightUpsertArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * The filter to search for the Highlight to update in case it exists.
	 */
	where: Prisma.HighlightWhereUniqueInput;
	/**
	 * In case the Highlight found by the `where` argument doesn't exist, create a new Highlight with this data.
	 */
	create: Prisma.XOR<Prisma.HighlightCreateInput, Prisma.HighlightUncheckedCreateInput>;
	/**
	 * In case the Highlight was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.HighlightUpdateInput, Prisma.HighlightUncheckedUpdateInput>;
};

/**
 * Highlight delete
 */
export type HighlightDeleteArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
	/**
	 * Filter which Highlight to delete.
	 */
	where: Prisma.HighlightWhereUniqueInput;
};

/**
 * Highlight deleteMany
 */
export type HighlightDeleteManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which Highlights to delete
	 */
	where?: Prisma.HighlightWhereInput;
	/**
	 * Limit how many Highlights to delete.
	 */
	limit?: number;
};

/**
 * Highlight.channel_scoping
 */
export type Highlight$channel_scopingArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the HighlightChannelScoping
	 */
	select?: Prisma.HighlightChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the HighlightChannelScoping
	 */
	omit?: Prisma.HighlightChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightChannelScopingInclude<ExtArgs> | null;
	where?: Prisma.HighlightChannelScopingWhereInput;
	orderBy?:
		| Prisma.HighlightChannelScopingOrderByWithRelationInput
		| Prisma.HighlightChannelScopingOrderByWithRelationInput[];
	cursor?: Prisma.HighlightChannelScopingWhereUniqueInput;
	take?: number;
	skip?: number;
	distinct?: Prisma.HighlightChannelScopingScalarFieldEnum | Prisma.HighlightChannelScopingScalarFieldEnum[];
};

/**
 * Highlight without action
 */
export type HighlightDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the Highlight
	 */
	select?: Prisma.HighlightSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the Highlight
	 */
	omit?: Prisma.HighlightOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.HighlightInclude<ExtArgs> | null;
};
