/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `QuickMuteChannelScoping` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model QuickMuteChannelScoping
 *
 */
export type QuickMuteChannelScopingModel =
	runtime.Types.Result.DefaultSelection<Prisma.$QuickMuteChannelScopingPayload>;

export type AggregateQuickMuteChannelScoping = {
	_count: QuickMuteChannelScopingCountAggregateOutputType | null;
	_avg: QuickMuteChannelScopingAvgAggregateOutputType | null;
	_sum: QuickMuteChannelScopingSumAggregateOutputType | null;
	_min: QuickMuteChannelScopingMinAggregateOutputType | null;
	_max: QuickMuteChannelScopingMaxAggregateOutputType | null;
};

export type QuickMuteChannelScopingAvgAggregateOutputType = {
	type: number | null;
};

export type QuickMuteChannelScopingSumAggregateOutputType = {
	type: number | null;
};

export type QuickMuteChannelScopingMinAggregateOutputType = {
	guild_id: string | null;
	channel_id: string | null;
	type: number | null;
};

export type QuickMuteChannelScopingMaxAggregateOutputType = {
	guild_id: string | null;
	channel_id: string | null;
	type: number | null;
};

export type QuickMuteChannelScopingCountAggregateOutputType = {
	guild_id: number;
	channel_id: number;
	type: number;
	_all: number;
};

export type QuickMuteChannelScopingAvgAggregateInputType = {
	type?: true;
};

export type QuickMuteChannelScopingSumAggregateInputType = {
	type?: true;
};

export type QuickMuteChannelScopingMinAggregateInputType = {
	guild_id?: true;
	channel_id?: true;
	type?: true;
};

export type QuickMuteChannelScopingMaxAggregateInputType = {
	guild_id?: true;
	channel_id?: true;
	type?: true;
};

export type QuickMuteChannelScopingCountAggregateInputType = {
	guild_id?: true;
	channel_id?: true;
	type?: true;
	_all?: true;
};

export type QuickMuteChannelScopingAggregateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which QuickMuteChannelScoping to aggregate.
	 */
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMuteChannelScopings to fetch.
	 */
	orderBy?:
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMuteChannelScopings from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMuteChannelScopings.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned QuickMuteChannelScopings
	 **/
	_count?: true | QuickMuteChannelScopingCountAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to average
	 **/
	_avg?: QuickMuteChannelScopingAvgAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to sum
	 **/
	_sum?: QuickMuteChannelScopingSumAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: QuickMuteChannelScopingMinAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: QuickMuteChannelScopingMaxAggregateInputType;
};

export type GetQuickMuteChannelScopingAggregateType<T extends QuickMuteChannelScopingAggregateArgs> = {
	[P in keyof T & keyof AggregateQuickMuteChannelScoping]: P extends "_count" | "count"
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateQuickMuteChannelScoping[P]>
		: Prisma.GetScalarType<T[P], AggregateQuickMuteChannelScoping[P]>;
};

export type QuickMuteChannelScopingGroupByArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	orderBy?:
		| Prisma.QuickMuteChannelScopingOrderByWithAggregationInput
		| Prisma.QuickMuteChannelScopingOrderByWithAggregationInput[];
	by: Prisma.QuickMuteChannelScopingScalarFieldEnum[] | Prisma.QuickMuteChannelScopingScalarFieldEnum;
	having?: Prisma.QuickMuteChannelScopingScalarWhereWithAggregatesInput;
	take?: number;
	skip?: number;
	_count?: QuickMuteChannelScopingCountAggregateInputType | true;
	_avg?: QuickMuteChannelScopingAvgAggregateInputType;
	_sum?: QuickMuteChannelScopingSumAggregateInputType;
	_min?: QuickMuteChannelScopingMinAggregateInputType;
	_max?: QuickMuteChannelScopingMaxAggregateInputType;
};

export type QuickMuteChannelScopingGroupByOutputType = {
	guild_id: string;
	channel_id: string;
	type: number;
	_count: QuickMuteChannelScopingCountAggregateOutputType | null;
	_avg: QuickMuteChannelScopingAvgAggregateOutputType | null;
	_sum: QuickMuteChannelScopingSumAggregateOutputType | null;
	_min: QuickMuteChannelScopingMinAggregateOutputType | null;
	_max: QuickMuteChannelScopingMaxAggregateOutputType | null;
};

type GetQuickMuteChannelScopingGroupByPayload<T extends QuickMuteChannelScopingGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<QuickMuteChannelScopingGroupByOutputType, T["by"]> & {
			[P in keyof T & keyof QuickMuteChannelScopingGroupByOutputType]: P extends "_count"
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], QuickMuteChannelScopingGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], QuickMuteChannelScopingGroupByOutputType[P]>;
		}
	>
>;

export type QuickMuteChannelScopingWhereInput = {
	AND?: Prisma.QuickMuteChannelScopingWhereInput | Prisma.QuickMuteChannelScopingWhereInput[];
	OR?: Prisma.QuickMuteChannelScopingWhereInput[];
	NOT?: Prisma.QuickMuteChannelScopingWhereInput | Prisma.QuickMuteChannelScopingWhereInput[];
	guild_id?: Prisma.StringFilter<"QuickMuteChannelScoping"> | string;
	channel_id?: Prisma.StringFilter<"QuickMuteChannelScoping"> | string;
	type?: Prisma.IntFilter<"QuickMuteChannelScoping"> | number;
	quick_mute_config?: Prisma.XOR<Prisma.QuickMuteConfigScalarRelationFilter, Prisma.QuickMuteConfigWhereInput>;
};

export type QuickMuteChannelScopingOrderByWithRelationInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
	quick_mute_config?: Prisma.QuickMuteConfigOrderByWithRelationInput;
};

export type QuickMuteChannelScopingWhereUniqueInput = Prisma.AtLeast<
	{
		guild_id_channel_id?: Prisma.QuickMuteChannelScopingGuild_idChannel_idCompoundUniqueInput;
		AND?: Prisma.QuickMuteChannelScopingWhereInput | Prisma.QuickMuteChannelScopingWhereInput[];
		OR?: Prisma.QuickMuteChannelScopingWhereInput[];
		NOT?: Prisma.QuickMuteChannelScopingWhereInput | Prisma.QuickMuteChannelScopingWhereInput[];
		guild_id?: Prisma.StringFilter<"QuickMuteChannelScoping"> | string;
		channel_id?: Prisma.StringFilter<"QuickMuteChannelScoping"> | string;
		type?: Prisma.IntFilter<"QuickMuteChannelScoping"> | number;
		quick_mute_config?: Prisma.XOR<Prisma.QuickMuteConfigScalarRelationFilter, Prisma.QuickMuteConfigWhereInput>;
	},
	"guild_id_channel_id"
>;

export type QuickMuteChannelScopingOrderByWithAggregationInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
	_count?: Prisma.QuickMuteChannelScopingCountOrderByAggregateInput;
	_avg?: Prisma.QuickMuteChannelScopingAvgOrderByAggregateInput;
	_max?: Prisma.QuickMuteChannelScopingMaxOrderByAggregateInput;
	_min?: Prisma.QuickMuteChannelScopingMinOrderByAggregateInput;
	_sum?: Prisma.QuickMuteChannelScopingSumOrderByAggregateInput;
};

export type QuickMuteChannelScopingScalarWhereWithAggregatesInput = {
	AND?:
		| Prisma.QuickMuteChannelScopingScalarWhereWithAggregatesInput
		| Prisma.QuickMuteChannelScopingScalarWhereWithAggregatesInput[];
	OR?: Prisma.QuickMuteChannelScopingScalarWhereWithAggregatesInput[];
	NOT?:
		| Prisma.QuickMuteChannelScopingScalarWhereWithAggregatesInput
		| Prisma.QuickMuteChannelScopingScalarWhereWithAggregatesInput[];
	guild_id?: Prisma.StringWithAggregatesFilter<"QuickMuteChannelScoping"> | string;
	channel_id?: Prisma.StringWithAggregatesFilter<"QuickMuteChannelScoping"> | string;
	type?: Prisma.IntWithAggregatesFilter<"QuickMuteChannelScoping"> | number;
};

export type QuickMuteChannelScopingCreateInput = {
	channel_id: string;
	type: number;
	quick_mute_config: Prisma.QuickMuteConfigCreateNestedOneWithoutChannel_scopingInput;
};

export type QuickMuteChannelScopingUncheckedCreateInput = {
	guild_id: string;
	channel_id: string;
	type: number;
};

export type QuickMuteChannelScopingUpdateInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
	quick_mute_config?: Prisma.QuickMuteConfigUpdateOneRequiredWithoutChannel_scopingNestedInput;
};

export type QuickMuteChannelScopingUncheckedUpdateInput = {
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteChannelScopingCreateManyInput = {
	guild_id: string;
	channel_id: string;
	type: number;
};

export type QuickMuteChannelScopingUpdateManyMutationInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteChannelScopingUncheckedUpdateManyInput = {
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteChannelScopingListRelationFilter = {
	every?: Prisma.QuickMuteChannelScopingWhereInput;
	some?: Prisma.QuickMuteChannelScopingWhereInput;
	none?: Prisma.QuickMuteChannelScopingWhereInput;
};

export type QuickMuteChannelScopingOrderByRelationAggregateInput = {
	_count?: Prisma.SortOrder;
};

export type QuickMuteChannelScopingGuild_idChannel_idCompoundUniqueInput = {
	guild_id: string;
	channel_id: string;
};

export type QuickMuteChannelScopingCountOrderByAggregateInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
};

export type QuickMuteChannelScopingAvgOrderByAggregateInput = {
	type?: Prisma.SortOrder;
};

export type QuickMuteChannelScopingMaxOrderByAggregateInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
};

export type QuickMuteChannelScopingMinOrderByAggregateInput = {
	guild_id?: Prisma.SortOrder;
	channel_id?: Prisma.SortOrder;
	type?: Prisma.SortOrder;
};

export type QuickMuteChannelScopingSumOrderByAggregateInput = {
	type?: Prisma.SortOrder;
};

export type QuickMuteChannelScopingCreateNestedManyWithoutQuick_mute_configInput = {
	create?:
		| Prisma.XOR<
				Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput,
				Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput
		  >
		| Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput[]
		| Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput[];
	connectOrCreate?:
		| Prisma.QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput[];
	createMany?: Prisma.QuickMuteChannelScopingCreateManyQuick_mute_configInputEnvelope;
	connect?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
};

export type QuickMuteChannelScopingUncheckedCreateNestedManyWithoutQuick_mute_configInput = {
	create?:
		| Prisma.XOR<
				Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput,
				Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput
		  >
		| Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput[]
		| Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput[];
	connectOrCreate?:
		| Prisma.QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput[];
	createMany?: Prisma.QuickMuteChannelScopingCreateManyQuick_mute_configInputEnvelope;
	connect?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
};

export type QuickMuteChannelScopingUpdateManyWithoutQuick_mute_configNestedInput = {
	create?:
		| Prisma.XOR<
				Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput,
				Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput
		  >
		| Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput[]
		| Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput[];
	connectOrCreate?:
		| Prisma.QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput[];
	upsert?:
		| Prisma.QuickMuteChannelScopingUpsertWithWhereUniqueWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingUpsertWithWhereUniqueWithoutQuick_mute_configInput[];
	createMany?: Prisma.QuickMuteChannelScopingCreateManyQuick_mute_configInputEnvelope;
	set?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
	disconnect?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
	delete?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
	connect?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
	update?:
		| Prisma.QuickMuteChannelScopingUpdateWithWhereUniqueWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingUpdateWithWhereUniqueWithoutQuick_mute_configInput[];
	updateMany?:
		| Prisma.QuickMuteChannelScopingUpdateManyWithWhereWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingUpdateManyWithWhereWithoutQuick_mute_configInput[];
	deleteMany?: Prisma.QuickMuteChannelScopingScalarWhereInput | Prisma.QuickMuteChannelScopingScalarWhereInput[];
};

export type QuickMuteChannelScopingUncheckedUpdateManyWithoutQuick_mute_configNestedInput = {
	create?:
		| Prisma.XOR<
				Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput,
				Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput
		  >
		| Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput[]
		| Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput[];
	connectOrCreate?:
		| Prisma.QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput[];
	upsert?:
		| Prisma.QuickMuteChannelScopingUpsertWithWhereUniqueWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingUpsertWithWhereUniqueWithoutQuick_mute_configInput[];
	createMany?: Prisma.QuickMuteChannelScopingCreateManyQuick_mute_configInputEnvelope;
	set?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
	disconnect?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
	delete?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
	connect?: Prisma.QuickMuteChannelScopingWhereUniqueInput | Prisma.QuickMuteChannelScopingWhereUniqueInput[];
	update?:
		| Prisma.QuickMuteChannelScopingUpdateWithWhereUniqueWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingUpdateWithWhereUniqueWithoutQuick_mute_configInput[];
	updateMany?:
		| Prisma.QuickMuteChannelScopingUpdateManyWithWhereWithoutQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingUpdateManyWithWhereWithoutQuick_mute_configInput[];
	deleteMany?: Prisma.QuickMuteChannelScopingScalarWhereInput | Prisma.QuickMuteChannelScopingScalarWhereInput[];
};

export type QuickMuteChannelScopingCreateWithoutQuick_mute_configInput = {
	channel_id: string;
	type: number;
};

export type QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput = {
	channel_id: string;
	type: number;
};

export type QuickMuteChannelScopingCreateOrConnectWithoutQuick_mute_configInput = {
	where: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	create: Prisma.XOR<
		Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput,
		Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput
	>;
};

export type QuickMuteChannelScopingCreateManyQuick_mute_configInputEnvelope = {
	data:
		| Prisma.QuickMuteChannelScopingCreateManyQuick_mute_configInput
		| Prisma.QuickMuteChannelScopingCreateManyQuick_mute_configInput[];
	skipDuplicates?: boolean;
};

export type QuickMuteChannelScopingUpsertWithWhereUniqueWithoutQuick_mute_configInput = {
	where: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	update: Prisma.XOR<
		Prisma.QuickMuteChannelScopingUpdateWithoutQuick_mute_configInput,
		Prisma.QuickMuteChannelScopingUncheckedUpdateWithoutQuick_mute_configInput
	>;
	create: Prisma.XOR<
		Prisma.QuickMuteChannelScopingCreateWithoutQuick_mute_configInput,
		Prisma.QuickMuteChannelScopingUncheckedCreateWithoutQuick_mute_configInput
	>;
};

export type QuickMuteChannelScopingUpdateWithWhereUniqueWithoutQuick_mute_configInput = {
	where: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	data: Prisma.XOR<
		Prisma.QuickMuteChannelScopingUpdateWithoutQuick_mute_configInput,
		Prisma.QuickMuteChannelScopingUncheckedUpdateWithoutQuick_mute_configInput
	>;
};

export type QuickMuteChannelScopingUpdateManyWithWhereWithoutQuick_mute_configInput = {
	where: Prisma.QuickMuteChannelScopingScalarWhereInput;
	data: Prisma.XOR<
		Prisma.QuickMuteChannelScopingUpdateManyMutationInput,
		Prisma.QuickMuteChannelScopingUncheckedUpdateManyWithoutQuick_mute_configInput
	>;
};

export type QuickMuteChannelScopingScalarWhereInput = {
	AND?: Prisma.QuickMuteChannelScopingScalarWhereInput | Prisma.QuickMuteChannelScopingScalarWhereInput[];
	OR?: Prisma.QuickMuteChannelScopingScalarWhereInput[];
	NOT?: Prisma.QuickMuteChannelScopingScalarWhereInput | Prisma.QuickMuteChannelScopingScalarWhereInput[];
	guild_id?: Prisma.StringFilter<"QuickMuteChannelScoping"> | string;
	channel_id?: Prisma.StringFilter<"QuickMuteChannelScoping"> | string;
	type?: Prisma.IntFilter<"QuickMuteChannelScoping"> | number;
};

export type QuickMuteChannelScopingCreateManyQuick_mute_configInput = {
	channel_id: string;
	type: number;
};

export type QuickMuteChannelScopingUpdateWithoutQuick_mute_configInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteChannelScopingUncheckedUpdateWithoutQuick_mute_configInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteChannelScopingUncheckedUpdateManyWithoutQuick_mute_configInput = {
	channel_id?: Prisma.StringFieldUpdateOperationsInput | string;
	type?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteChannelScopingSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		guild_id?: boolean;
		channel_id?: boolean;
		type?: boolean;
		quick_mute_config?: boolean | Prisma.QuickMuteConfigDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMuteChannelScoping"]
>;

export type QuickMuteChannelScopingSelectCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		guild_id?: boolean;
		channel_id?: boolean;
		type?: boolean;
		quick_mute_config?: boolean | Prisma.QuickMuteConfigDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMuteChannelScoping"]
>;

export type QuickMuteChannelScopingSelectUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		guild_id?: boolean;
		channel_id?: boolean;
		type?: boolean;
		quick_mute_config?: boolean | Prisma.QuickMuteConfigDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMuteChannelScoping"]
>;

export type QuickMuteChannelScopingSelectScalar = {
	guild_id?: boolean;
	channel_id?: boolean;
	type?: boolean;
};

export type QuickMuteChannelScopingOmit<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<"guild_id" | "channel_id" | "type", ExtArgs["result"]["quickMuteChannelScoping"]>;
export type QuickMuteChannelScopingInclude<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	quick_mute_config?: boolean | Prisma.QuickMuteConfigDefaultArgs<ExtArgs>;
};
export type QuickMuteChannelScopingIncludeCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	quick_mute_config?: boolean | Prisma.QuickMuteConfigDefaultArgs<ExtArgs>;
};
export type QuickMuteChannelScopingIncludeUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	quick_mute_config?: boolean | Prisma.QuickMuteConfigDefaultArgs<ExtArgs>;
};

export type $QuickMuteChannelScopingPayload<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	name: "QuickMuteChannelScoping";
	objects: {
		quick_mute_config: Prisma.$QuickMuteConfigPayload<ExtArgs>;
	};
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			guild_id: string;
			channel_id: string;
			/**
			 * Include [`0`] or Exclude [`1`]
			 */
			type: number;
		},
		ExtArgs["result"]["quickMuteChannelScoping"]
	>;
	composites: {};
};

export type QuickMuteChannelScopingGetPayload<
	S extends boolean | null | undefined | QuickMuteChannelScopingDefaultArgs
> = runtime.Types.Result.GetResult<Prisma.$QuickMuteChannelScopingPayload, S>;

export type QuickMuteChannelScopingCountArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<QuickMuteChannelScopingFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
	select?: QuickMuteChannelScopingCountAggregateInputType | true;
};

export interface QuickMuteChannelScopingDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> {
	[K: symbol]: {
		types: Prisma.TypeMap<ExtArgs>["model"]["QuickMuteChannelScoping"];
		meta: { name: "QuickMuteChannelScoping" };
	};
	/**
	 * Find zero or one QuickMuteChannelScoping that matches the filter.
	 * @param {QuickMuteChannelScopingFindUniqueArgs} args - Arguments to find a QuickMuteChannelScoping
	 * @example
	 * // Get one QuickMuteChannelScoping
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends QuickMuteChannelScopingFindUniqueArgs>(
		args: Prisma.SelectSubset<T, QuickMuteChannelScopingFindUniqueArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"findUnique",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find one QuickMuteChannelScoping that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {QuickMuteChannelScopingFindUniqueOrThrowArgs} args - Arguments to find a QuickMuteChannelScoping
	 * @example
	 * // Get one QuickMuteChannelScoping
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends QuickMuteChannelScopingFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, QuickMuteChannelScopingFindUniqueOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"findUniqueOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first QuickMuteChannelScoping that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteChannelScopingFindFirstArgs} args - Arguments to find a QuickMuteChannelScoping
	 * @example
	 * // Get one QuickMuteChannelScoping
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends QuickMuteChannelScopingFindFirstArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteChannelScopingFindFirstArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"findFirst",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first QuickMuteChannelScoping that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteChannelScopingFindFirstOrThrowArgs} args - Arguments to find a QuickMuteChannelScoping
	 * @example
	 * // Get one QuickMuteChannelScoping
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends QuickMuteChannelScopingFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteChannelScopingFindFirstOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"findFirstOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find zero or more QuickMuteChannelScopings that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteChannelScopingFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all QuickMuteChannelScopings
	 * const quickMuteChannelScopings = await prisma.quickMuteChannelScoping.findMany()
	 *
	 * // Get first 10 QuickMuteChannelScopings
	 * const quickMuteChannelScopings = await prisma.quickMuteChannelScoping.findMany({ take: 10 })
	 *
	 * // Only select the `guild_id`
	 * const quickMuteChannelScopingWithGuild_idOnly = await prisma.quickMuteChannelScoping.findMany({ select: { guild_id: true } })
	 *
	 */
	findMany<T extends QuickMuteChannelScopingFindManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteChannelScopingFindManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"findMany",
			GlobalOmitOptions
		>
	>;

	/**
	 * Create a QuickMuteChannelScoping.
	 * @param {QuickMuteChannelScopingCreateArgs} args - Arguments to create a QuickMuteChannelScoping.
	 * @example
	 * // Create one QuickMuteChannelScoping
	 * const QuickMuteChannelScoping = await prisma.quickMuteChannelScoping.create({
	 *   data: {
	 *     // ... data to create a QuickMuteChannelScoping
	 *   }
	 * })
	 *
	 */
	create<T extends QuickMuteChannelScopingCreateArgs>(
		args: Prisma.SelectSubset<T, QuickMuteChannelScopingCreateArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"create",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Create many QuickMuteChannelScopings.
	 * @param {QuickMuteChannelScopingCreateManyArgs} args - Arguments to create many QuickMuteChannelScopings.
	 * @example
	 * // Create many QuickMuteChannelScopings
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends QuickMuteChannelScopingCreateManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteChannelScopingCreateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Create many QuickMuteChannelScopings and returns the data saved in the database.
	 * @param {QuickMuteChannelScopingCreateManyAndReturnArgs} args - Arguments to create many QuickMuteChannelScopings.
	 * @example
	 * // Create many QuickMuteChannelScopings
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.createManyAndReturn({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Create many QuickMuteChannelScopings and only return the `guild_id`
	 * const quickMuteChannelScopingWithGuild_idOnly = await prisma.quickMuteChannelScoping.createManyAndReturn({
	 *   select: { guild_id: true },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	createManyAndReturn<T extends QuickMuteChannelScopingCreateManyAndReturnArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteChannelScopingCreateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"createManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Delete a QuickMuteChannelScoping.
	 * @param {QuickMuteChannelScopingDeleteArgs} args - Arguments to delete one QuickMuteChannelScoping.
	 * @example
	 * // Delete one QuickMuteChannelScoping
	 * const QuickMuteChannelScoping = await prisma.quickMuteChannelScoping.delete({
	 *   where: {
	 *     // ... filter to delete one QuickMuteChannelScoping
	 *   }
	 * })
	 *
	 */
	delete<T extends QuickMuteChannelScopingDeleteArgs>(
		args: Prisma.SelectSubset<T, QuickMuteChannelScopingDeleteArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"delete",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Update one QuickMuteChannelScoping.
	 * @param {QuickMuteChannelScopingUpdateArgs} args - Arguments to update one QuickMuteChannelScoping.
	 * @example
	 * // Update one QuickMuteChannelScoping
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends QuickMuteChannelScopingUpdateArgs>(
		args: Prisma.SelectSubset<T, QuickMuteChannelScopingUpdateArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"update",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Delete zero or more QuickMuteChannelScopings.
	 * @param {QuickMuteChannelScopingDeleteManyArgs} args - Arguments to filter QuickMuteChannelScopings to delete.
	 * @example
	 * // Delete a few QuickMuteChannelScopings
	 * const { count } = await prisma.quickMuteChannelScoping.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends QuickMuteChannelScopingDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteChannelScopingDeleteManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more QuickMuteChannelScopings.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteChannelScopingUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many QuickMuteChannelScopings
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends QuickMuteChannelScopingUpdateManyArgs>(
		args: Prisma.SelectSubset<T, QuickMuteChannelScopingUpdateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more QuickMuteChannelScopings and returns the data updated in the database.
	 * @param {QuickMuteChannelScopingUpdateManyAndReturnArgs} args - Arguments to update many QuickMuteChannelScopings.
	 * @example
	 * // Update many QuickMuteChannelScopings
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.updateManyAndReturn({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Update zero or more QuickMuteChannelScopings and only return the `guild_id`
	 * const quickMuteChannelScopingWithGuild_idOnly = await prisma.quickMuteChannelScoping.updateManyAndReturn({
	 *   select: { guild_id: true },
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	updateManyAndReturn<T extends QuickMuteChannelScopingUpdateManyAndReturnArgs>(
		args: Prisma.SelectSubset<T, QuickMuteChannelScopingUpdateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"updateManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Create or update one QuickMuteChannelScoping.
	 * @param {QuickMuteChannelScopingUpsertArgs} args - Arguments to update or create a QuickMuteChannelScoping.
	 * @example
	 * // Update or create a QuickMuteChannelScoping
	 * const quickMuteChannelScoping = await prisma.quickMuteChannelScoping.upsert({
	 *   create: {
	 *     // ... data to create a QuickMuteChannelScoping
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the QuickMuteChannelScoping we want to update
	 *   }
	 * })
	 */
	upsert<T extends QuickMuteChannelScopingUpsertArgs>(
		args: Prisma.SelectSubset<T, QuickMuteChannelScopingUpsertArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteChannelScopingClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
			T,
			"upsert",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Count the number of QuickMuteChannelScopings.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteChannelScopingCountArgs} args - Arguments to filter QuickMuteChannelScopings to count.
	 * @example
	 * // Count the number of QuickMuteChannelScopings
	 * const count = await prisma.quickMuteChannelScoping.count({
	 *   where: {
	 *     // ... the filter for the QuickMuteChannelScopings we want to count
	 *   }
	 * })
	 **/
	count<T extends QuickMuteChannelScopingCountArgs>(
		args?: Prisma.Subset<T, QuickMuteChannelScopingCountArgs>
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<"select", any>
			? T["select"] extends true
				? number
				: Prisma.GetScalarType<T["select"], QuickMuteChannelScopingCountAggregateOutputType>
			: number
	>;

	/**
	 * Allows you to perform aggregations operations on a QuickMuteChannelScoping.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteChannelScopingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends QuickMuteChannelScopingAggregateArgs>(
		args: Prisma.Subset<T, QuickMuteChannelScopingAggregateArgs>
	): Prisma.PrismaPromise<GetQuickMuteChannelScopingAggregateType<T>>;

	/**
	 * Group by QuickMuteChannelScoping.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteChannelScopingGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends QuickMuteChannelScopingGroupByArgs,
		HasSelectOrTake extends Prisma.Or<
			Prisma.Extends<"skip", Prisma.Keys<T>>,
			Prisma.Extends<"take", Prisma.Keys<T>>
		>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: QuickMuteChannelScopingGroupByArgs["orderBy"] }
			: { orderBy?: QuickMuteChannelScopingGroupByArgs["orderBy"] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T["having"]>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
					}[HavingFields]
				: "take" extends Prisma.Keys<T>
					? "orderBy" extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: "skip" extends Prisma.Keys<T>
						? "orderBy" extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields
											? never
											: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
	>(
		args: Prisma.SubsetIntersection<T, QuickMuteChannelScopingGroupByArgs, OrderByArg> & InputErrors
	): {} extends InputErrors ? GetQuickMuteChannelScopingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
	/**
	 * Fields of the QuickMuteChannelScoping model
	 */
	readonly fields: QuickMuteChannelScopingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuickMuteChannelScoping.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuickMuteChannelScopingClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: "PrismaPromise";
	quick_mute_config<T extends Prisma.QuickMuteConfigDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.QuickMuteConfigDefaultArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		| runtime.Types.Result.GetResult<
				Prisma.$QuickMuteConfigPayload<ExtArgs>,
				T,
				"findUniqueOrThrow",
				GlobalOmitOptions
		  >
		| Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>;
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
	): runtime.Types.Utils.JsPromise<T | TResult>;
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the QuickMuteChannelScoping model
 */
export interface QuickMuteChannelScopingFieldRefs {
	readonly guild_id: Prisma.FieldRef<"QuickMuteChannelScoping", "String">;
	readonly channel_id: Prisma.FieldRef<"QuickMuteChannelScoping", "String">;
	readonly type: Prisma.FieldRef<"QuickMuteChannelScoping", "Int">;
}

// Custom InputTypes
/**
 * QuickMuteChannelScoping findUnique
 */
export type QuickMuteChannelScopingFindUniqueArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteChannelScoping to fetch.
	 */
	where: Prisma.QuickMuteChannelScopingWhereUniqueInput;
};

/**
 * QuickMuteChannelScoping findUniqueOrThrow
 */
export type QuickMuteChannelScopingFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteChannelScoping to fetch.
	 */
	where: Prisma.QuickMuteChannelScopingWhereUniqueInput;
};

/**
 * QuickMuteChannelScoping findFirst
 */
export type QuickMuteChannelScopingFindFirstArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteChannelScoping to fetch.
	 */
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMuteChannelScopings to fetch.
	 */
	orderBy?:
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for QuickMuteChannelScopings.
	 */
	cursor?: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMuteChannelScopings from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMuteChannelScopings.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of QuickMuteChannelScopings.
	 */
	distinct?: Prisma.QuickMuteChannelScopingScalarFieldEnum | Prisma.QuickMuteChannelScopingScalarFieldEnum[];
};

/**
 * QuickMuteChannelScoping findFirstOrThrow
 */
export type QuickMuteChannelScopingFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteChannelScoping to fetch.
	 */
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMuteChannelScopings to fetch.
	 */
	orderBy?:
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for QuickMuteChannelScopings.
	 */
	cursor?: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMuteChannelScopings from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMuteChannelScopings.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of QuickMuteChannelScopings.
	 */
	distinct?: Prisma.QuickMuteChannelScopingScalarFieldEnum | Prisma.QuickMuteChannelScopingScalarFieldEnum[];
};

/**
 * QuickMuteChannelScoping findMany
 */
export type QuickMuteChannelScopingFindManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteChannelScopings to fetch.
	 */
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMuteChannelScopings to fetch.
	 */
	orderBy?:
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing QuickMuteChannelScopings.
	 */
	cursor?: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMuteChannelScopings from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMuteChannelScopings.
	 */
	skip?: number;
	distinct?: Prisma.QuickMuteChannelScopingScalarFieldEnum | Prisma.QuickMuteChannelScopingScalarFieldEnum[];
};

/**
 * QuickMuteChannelScoping create
 */
export type QuickMuteChannelScopingCreateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * The data needed to create a QuickMuteChannelScoping.
	 */
	data: Prisma.XOR<Prisma.QuickMuteChannelScopingCreateInput, Prisma.QuickMuteChannelScopingUncheckedCreateInput>;
};

/**
 * QuickMuteChannelScoping createMany
 */
export type QuickMuteChannelScopingCreateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to create many QuickMuteChannelScopings.
	 */
	data: Prisma.QuickMuteChannelScopingCreateManyInput | Prisma.QuickMuteChannelScopingCreateManyInput[];
	skipDuplicates?: boolean;
};

/**
 * QuickMuteChannelScoping createManyAndReturn
 */
export type QuickMuteChannelScopingCreateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelectCreateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * The data used to create many QuickMuteChannelScopings.
	 */
	data: Prisma.QuickMuteChannelScopingCreateManyInput | Prisma.QuickMuteChannelScopingCreateManyInput[];
	skipDuplicates?: boolean;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * QuickMuteChannelScoping update
 */
export type QuickMuteChannelScopingUpdateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * The data needed to update a QuickMuteChannelScoping.
	 */
	data: Prisma.XOR<Prisma.QuickMuteChannelScopingUpdateInput, Prisma.QuickMuteChannelScopingUncheckedUpdateInput>;
	/**
	 * Choose, which QuickMuteChannelScoping to update.
	 */
	where: Prisma.QuickMuteChannelScopingWhereUniqueInput;
};

/**
 * QuickMuteChannelScoping updateMany
 */
export type QuickMuteChannelScopingUpdateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to update QuickMuteChannelScopings.
	 */
	data: Prisma.XOR<
		Prisma.QuickMuteChannelScopingUpdateManyMutationInput,
		Prisma.QuickMuteChannelScopingUncheckedUpdateManyInput
	>;
	/**
	 * Filter which QuickMuteChannelScopings to update
	 */
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	/**
	 * Limit how many QuickMuteChannelScopings to update.
	 */
	limit?: number;
};

/**
 * QuickMuteChannelScoping updateManyAndReturn
 */
export type QuickMuteChannelScopingUpdateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelectUpdateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * The data used to update QuickMuteChannelScopings.
	 */
	data: Prisma.XOR<
		Prisma.QuickMuteChannelScopingUpdateManyMutationInput,
		Prisma.QuickMuteChannelScopingUncheckedUpdateManyInput
	>;
	/**
	 * Filter which QuickMuteChannelScopings to update
	 */
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	/**
	 * Limit how many QuickMuteChannelScopings to update.
	 */
	limit?: number;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * QuickMuteChannelScoping upsert
 */
export type QuickMuteChannelScopingUpsertArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * The filter to search for the QuickMuteChannelScoping to update in case it exists.
	 */
	where: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	/**
	 * In case the QuickMuteChannelScoping found by the `where` argument doesn't exist, create a new QuickMuteChannelScoping with this data.
	 */
	create: Prisma.XOR<Prisma.QuickMuteChannelScopingCreateInput, Prisma.QuickMuteChannelScopingUncheckedCreateInput>;
	/**
	 * In case the QuickMuteChannelScoping was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.QuickMuteChannelScopingUpdateInput, Prisma.QuickMuteChannelScopingUncheckedUpdateInput>;
};

/**
 * QuickMuteChannelScoping delete
 */
export type QuickMuteChannelScopingDeleteArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	/**
	 * Filter which QuickMuteChannelScoping to delete.
	 */
	where: Prisma.QuickMuteChannelScopingWhereUniqueInput;
};

/**
 * QuickMuteChannelScoping deleteMany
 */
export type QuickMuteChannelScopingDeleteManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which QuickMuteChannelScopings to delete
	 */
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	/**
	 * Limit how many QuickMuteChannelScopings to delete.
	 */
	limit?: number;
};

/**
 * QuickMuteChannelScoping without action
 */
export type QuickMuteChannelScopingDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
};
