/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `QuickMute` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model QuickMute
 *
 */
export type QuickMuteModel = runtime.Types.Result.DefaultSelection<Prisma.$QuickMutePayload>;

export type AggregateQuickMute = {
	_count: QuickMuteCountAggregateOutputType | null;
	_avg: QuickMuteAvgAggregateOutputType | null;
	_sum: QuickMuteSumAggregateOutputType | null;
	_min: QuickMuteMinAggregateOutputType | null;
	_max: QuickMuteMaxAggregateOutputType | null;
};

export type QuickMuteAvgAggregateOutputType = {
	duration: number | null;
	purge_amount: number | null;
};

export type QuickMuteSumAggregateOutputType = {
	duration: bigint | null;
	purge_amount: number | null;
};

export type QuickMuteMinAggregateOutputType = {
	user_id: string | null;
	guild_id: string | null;
	reaction: string | null;
	duration: bigint | null;
	reason: string | null;
	purge_amount: number | null;
};

export type QuickMuteMaxAggregateOutputType = {
	user_id: string | null;
	guild_id: string | null;
	reaction: string | null;
	duration: bigint | null;
	reason: string | null;
	purge_amount: number | null;
};

export type QuickMuteCountAggregateOutputType = {
	user_id: number;
	guild_id: number;
	reaction: number;
	duration: number;
	reason: number;
	purge_amount: number;
	_all: number;
};

export type QuickMuteAvgAggregateInputType = {
	duration?: true;
	purge_amount?: true;
};

export type QuickMuteSumAggregateInputType = {
	duration?: true;
	purge_amount?: true;
};

export type QuickMuteMinAggregateInputType = {
	user_id?: true;
	guild_id?: true;
	reaction?: true;
	duration?: true;
	reason?: true;
	purge_amount?: true;
};

export type QuickMuteMaxAggregateInputType = {
	user_id?: true;
	guild_id?: true;
	reaction?: true;
	duration?: true;
	reason?: true;
	purge_amount?: true;
};

export type QuickMuteCountAggregateInputType = {
	user_id?: true;
	guild_id?: true;
	reaction?: true;
	duration?: true;
	reason?: true;
	purge_amount?: true;
	_all?: true;
};

export type QuickMuteAggregateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which QuickMute to aggregate.
	 */
	where?: Prisma.QuickMuteWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMutes to fetch.
	 */
	orderBy?: Prisma.QuickMuteOrderByWithRelationInput | Prisma.QuickMuteOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.QuickMuteWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMutes from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMutes.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned QuickMutes
	 **/
	_count?: true | QuickMuteCountAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to average
	 **/
	_avg?: QuickMuteAvgAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to sum
	 **/
	_sum?: QuickMuteSumAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: QuickMuteMinAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: QuickMuteMaxAggregateInputType;
};

export type GetQuickMuteAggregateType<T extends QuickMuteAggregateArgs> = {
	[P in keyof T & keyof AggregateQuickMute]: P extends "_count" | "count"
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateQuickMute[P]>
		: Prisma.GetScalarType<T[P], AggregateQuickMute[P]>;
};

export type QuickMuteGroupByArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.QuickMuteWhereInput;
	orderBy?: Prisma.QuickMuteOrderByWithAggregationInput | Prisma.QuickMuteOrderByWithAggregationInput[];
	by: Prisma.QuickMuteScalarFieldEnum[] | Prisma.QuickMuteScalarFieldEnum;
	having?: Prisma.QuickMuteScalarWhereWithAggregatesInput;
	take?: number;
	skip?: number;
	_count?: QuickMuteCountAggregateInputType | true;
	_avg?: QuickMuteAvgAggregateInputType;
	_sum?: QuickMuteSumAggregateInputType;
	_min?: QuickMuteMinAggregateInputType;
	_max?: QuickMuteMaxAggregateInputType;
};

export type QuickMuteGroupByOutputType = {
	user_id: string;
	guild_id: string;
	reaction: string;
	duration: bigint;
	reason: string;
	purge_amount: number;
	_count: QuickMuteCountAggregateOutputType | null;
	_avg: QuickMuteAvgAggregateOutputType | null;
	_sum: QuickMuteSumAggregateOutputType | null;
	_min: QuickMuteMinAggregateOutputType | null;
	_max: QuickMuteMaxAggregateOutputType | null;
};

type GetQuickMuteGroupByPayload<T extends QuickMuteGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<QuickMuteGroupByOutputType, T["by"]> & {
			[P in keyof T & keyof QuickMuteGroupByOutputType]: P extends "_count"
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], QuickMuteGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], QuickMuteGroupByOutputType[P]>;
		}
	>
>;

export type QuickMuteWhereInput = {
	AND?: Prisma.QuickMuteWhereInput | Prisma.QuickMuteWhereInput[];
	OR?: Prisma.QuickMuteWhereInput[];
	NOT?: Prisma.QuickMuteWhereInput | Prisma.QuickMuteWhereInput[];
	user_id?: Prisma.StringFilter<"QuickMute"> | string;
	guild_id?: Prisma.StringFilter<"QuickMute"> | string;
	reaction?: Prisma.StringFilter<"QuickMute"> | string;
	duration?: Prisma.BigIntFilter<"QuickMute"> | bigint | number;
	reason?: Prisma.StringFilter<"QuickMute"> | string;
	purge_amount?: Prisma.IntFilter<"QuickMute"> | number;
	guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>;
};

export type QuickMuteOrderByWithRelationInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	reaction?: Prisma.SortOrder;
	duration?: Prisma.SortOrder;
	reason?: Prisma.SortOrder;
	purge_amount?: Prisma.SortOrder;
	guild?: Prisma.GuildOrderByWithRelationInput;
};

export type QuickMuteWhereUniqueInput = Prisma.AtLeast<
	{
		user_id_guild_id_reaction?: Prisma.QuickMuteUser_idGuild_idReactionCompoundUniqueInput;
		AND?: Prisma.QuickMuteWhereInput | Prisma.QuickMuteWhereInput[];
		OR?: Prisma.QuickMuteWhereInput[];
		NOT?: Prisma.QuickMuteWhereInput | Prisma.QuickMuteWhereInput[];
		user_id?: Prisma.StringFilter<"QuickMute"> | string;
		guild_id?: Prisma.StringFilter<"QuickMute"> | string;
		reaction?: Prisma.StringFilter<"QuickMute"> | string;
		duration?: Prisma.BigIntFilter<"QuickMute"> | bigint | number;
		reason?: Prisma.StringFilter<"QuickMute"> | string;
		purge_amount?: Prisma.IntFilter<"QuickMute"> | number;
		guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>;
	},
	"user_id_guild_id_reaction"
>;

export type QuickMuteOrderByWithAggregationInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	reaction?: Prisma.SortOrder;
	duration?: Prisma.SortOrder;
	reason?: Prisma.SortOrder;
	purge_amount?: Prisma.SortOrder;
	_count?: Prisma.QuickMuteCountOrderByAggregateInput;
	_avg?: Prisma.QuickMuteAvgOrderByAggregateInput;
	_max?: Prisma.QuickMuteMaxOrderByAggregateInput;
	_min?: Prisma.QuickMuteMinOrderByAggregateInput;
	_sum?: Prisma.QuickMuteSumOrderByAggregateInput;
};

export type QuickMuteScalarWhereWithAggregatesInput = {
	AND?: Prisma.QuickMuteScalarWhereWithAggregatesInput | Prisma.QuickMuteScalarWhereWithAggregatesInput[];
	OR?: Prisma.QuickMuteScalarWhereWithAggregatesInput[];
	NOT?: Prisma.QuickMuteScalarWhereWithAggregatesInput | Prisma.QuickMuteScalarWhereWithAggregatesInput[];
	user_id?: Prisma.StringWithAggregatesFilter<"QuickMute"> | string;
	guild_id?: Prisma.StringWithAggregatesFilter<"QuickMute"> | string;
	reaction?: Prisma.StringWithAggregatesFilter<"QuickMute"> | string;
	duration?: Prisma.BigIntWithAggregatesFilter<"QuickMute"> | bigint | number;
	reason?: Prisma.StringWithAggregatesFilter<"QuickMute"> | string;
	purge_amount?: Prisma.IntWithAggregatesFilter<"QuickMute"> | number;
};

export type QuickMuteCreateInput = {
	user_id: string;
	reaction: string;
	duration: bigint | number;
	reason: string;
	purge_amount?: number;
	guild: Prisma.GuildCreateNestedOneWithoutQuick_mutesInput;
};

export type QuickMuteUncheckedCreateInput = {
	user_id: string;
	guild_id: string;
	reaction: string;
	duration: bigint | number;
	reason: string;
	purge_amount?: number;
};

export type QuickMuteUpdateInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	reaction?: Prisma.StringFieldUpdateOperationsInput | string;
	duration?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
	reason?: Prisma.StringFieldUpdateOperationsInput | string;
	purge_amount?: Prisma.IntFieldUpdateOperationsInput | number;
	guild?: Prisma.GuildUpdateOneRequiredWithoutQuick_mutesNestedInput;
};

export type QuickMuteUncheckedUpdateInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	reaction?: Prisma.StringFieldUpdateOperationsInput | string;
	duration?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
	reason?: Prisma.StringFieldUpdateOperationsInput | string;
	purge_amount?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteCreateManyInput = {
	user_id: string;
	guild_id: string;
	reaction: string;
	duration: bigint | number;
	reason: string;
	purge_amount?: number;
};

export type QuickMuteUpdateManyMutationInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	reaction?: Prisma.StringFieldUpdateOperationsInput | string;
	duration?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
	reason?: Prisma.StringFieldUpdateOperationsInput | string;
	purge_amount?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteUncheckedUpdateManyInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	guild_id?: Prisma.StringFieldUpdateOperationsInput | string;
	reaction?: Prisma.StringFieldUpdateOperationsInput | string;
	duration?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
	reason?: Prisma.StringFieldUpdateOperationsInput | string;
	purge_amount?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteListRelationFilter = {
	every?: Prisma.QuickMuteWhereInput;
	some?: Prisma.QuickMuteWhereInput;
	none?: Prisma.QuickMuteWhereInput;
};

export type QuickMuteOrderByRelationAggregateInput = {
	_count?: Prisma.SortOrder;
};

export type QuickMuteUser_idGuild_idReactionCompoundUniqueInput = {
	user_id: string;
	guild_id: string;
	reaction: string;
};

export type QuickMuteCountOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	reaction?: Prisma.SortOrder;
	duration?: Prisma.SortOrder;
	reason?: Prisma.SortOrder;
	purge_amount?: Prisma.SortOrder;
};

export type QuickMuteAvgOrderByAggregateInput = {
	duration?: Prisma.SortOrder;
	purge_amount?: Prisma.SortOrder;
};

export type QuickMuteMaxOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	reaction?: Prisma.SortOrder;
	duration?: Prisma.SortOrder;
	reason?: Prisma.SortOrder;
	purge_amount?: Prisma.SortOrder;
};

export type QuickMuteMinOrderByAggregateInput = {
	user_id?: Prisma.SortOrder;
	guild_id?: Prisma.SortOrder;
	reaction?: Prisma.SortOrder;
	duration?: Prisma.SortOrder;
	reason?: Prisma.SortOrder;
	purge_amount?: Prisma.SortOrder;
};

export type QuickMuteSumOrderByAggregateInput = {
	duration?: Prisma.SortOrder;
	purge_amount?: Prisma.SortOrder;
};

export type QuickMuteCreateNestedManyWithoutGuildInput = {
	create?:
		| Prisma.XOR<Prisma.QuickMuteCreateWithoutGuildInput, Prisma.QuickMuteUncheckedCreateWithoutGuildInput>
		| Prisma.QuickMuteCreateWithoutGuildInput[]
		| Prisma.QuickMuteUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.QuickMuteCreateOrConnectWithoutGuildInput
		| Prisma.QuickMuteCreateOrConnectWithoutGuildInput[];
	createMany?: Prisma.QuickMuteCreateManyGuildInputEnvelope;
	connect?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
};

export type QuickMuteUncheckedCreateNestedManyWithoutGuildInput = {
	create?:
		| Prisma.XOR<Prisma.QuickMuteCreateWithoutGuildInput, Prisma.QuickMuteUncheckedCreateWithoutGuildInput>
		| Prisma.QuickMuteCreateWithoutGuildInput[]
		| Prisma.QuickMuteUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.QuickMuteCreateOrConnectWithoutGuildInput
		| Prisma.QuickMuteCreateOrConnectWithoutGuildInput[];
	createMany?: Prisma.QuickMuteCreateManyGuildInputEnvelope;
	connect?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
};

export type QuickMuteUpdateManyWithoutGuildNestedInput = {
	create?:
		| Prisma.XOR<Prisma.QuickMuteCreateWithoutGuildInput, Prisma.QuickMuteUncheckedCreateWithoutGuildInput>
		| Prisma.QuickMuteCreateWithoutGuildInput[]
		| Prisma.QuickMuteUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.QuickMuteCreateOrConnectWithoutGuildInput
		| Prisma.QuickMuteCreateOrConnectWithoutGuildInput[];
	upsert?:
		| Prisma.QuickMuteUpsertWithWhereUniqueWithoutGuildInput
		| Prisma.QuickMuteUpsertWithWhereUniqueWithoutGuildInput[];
	createMany?: Prisma.QuickMuteCreateManyGuildInputEnvelope;
	set?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
	disconnect?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
	delete?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
	connect?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
	update?:
		| Prisma.QuickMuteUpdateWithWhereUniqueWithoutGuildInput
		| Prisma.QuickMuteUpdateWithWhereUniqueWithoutGuildInput[];
	updateMany?:
		| Prisma.QuickMuteUpdateManyWithWhereWithoutGuildInput
		| Prisma.QuickMuteUpdateManyWithWhereWithoutGuildInput[];
	deleteMany?: Prisma.QuickMuteScalarWhereInput | Prisma.QuickMuteScalarWhereInput[];
};

export type QuickMuteUncheckedUpdateManyWithoutGuildNestedInput = {
	create?:
		| Prisma.XOR<Prisma.QuickMuteCreateWithoutGuildInput, Prisma.QuickMuteUncheckedCreateWithoutGuildInput>
		| Prisma.QuickMuteCreateWithoutGuildInput[]
		| Prisma.QuickMuteUncheckedCreateWithoutGuildInput[];
	connectOrCreate?:
		| Prisma.QuickMuteCreateOrConnectWithoutGuildInput
		| Prisma.QuickMuteCreateOrConnectWithoutGuildInput[];
	upsert?:
		| Prisma.QuickMuteUpsertWithWhereUniqueWithoutGuildInput
		| Prisma.QuickMuteUpsertWithWhereUniqueWithoutGuildInput[];
	createMany?: Prisma.QuickMuteCreateManyGuildInputEnvelope;
	set?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
	disconnect?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
	delete?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
	connect?: Prisma.QuickMuteWhereUniqueInput | Prisma.QuickMuteWhereUniqueInput[];
	update?:
		| Prisma.QuickMuteUpdateWithWhereUniqueWithoutGuildInput
		| Prisma.QuickMuteUpdateWithWhereUniqueWithoutGuildInput[];
	updateMany?:
		| Prisma.QuickMuteUpdateManyWithWhereWithoutGuildInput
		| Prisma.QuickMuteUpdateManyWithWhereWithoutGuildInput[];
	deleteMany?: Prisma.QuickMuteScalarWhereInput | Prisma.QuickMuteScalarWhereInput[];
};

export type QuickMuteCreateWithoutGuildInput = {
	user_id: string;
	reaction: string;
	duration: bigint | number;
	reason: string;
	purge_amount?: number;
};

export type QuickMuteUncheckedCreateWithoutGuildInput = {
	user_id: string;
	reaction: string;
	duration: bigint | number;
	reason: string;
	purge_amount?: number;
};

export type QuickMuteCreateOrConnectWithoutGuildInput = {
	where: Prisma.QuickMuteWhereUniqueInput;
	create: Prisma.XOR<Prisma.QuickMuteCreateWithoutGuildInput, Prisma.QuickMuteUncheckedCreateWithoutGuildInput>;
};

export type QuickMuteCreateManyGuildInputEnvelope = {
	data: Prisma.QuickMuteCreateManyGuildInput | Prisma.QuickMuteCreateManyGuildInput[];
	skipDuplicates?: boolean;
};

export type QuickMuteUpsertWithWhereUniqueWithoutGuildInput = {
	where: Prisma.QuickMuteWhereUniqueInput;
	update: Prisma.XOR<Prisma.QuickMuteUpdateWithoutGuildInput, Prisma.QuickMuteUncheckedUpdateWithoutGuildInput>;
	create: Prisma.XOR<Prisma.QuickMuteCreateWithoutGuildInput, Prisma.QuickMuteUncheckedCreateWithoutGuildInput>;
};

export type QuickMuteUpdateWithWhereUniqueWithoutGuildInput = {
	where: Prisma.QuickMuteWhereUniqueInput;
	data: Prisma.XOR<Prisma.QuickMuteUpdateWithoutGuildInput, Prisma.QuickMuteUncheckedUpdateWithoutGuildInput>;
};

export type QuickMuteUpdateManyWithWhereWithoutGuildInput = {
	where: Prisma.QuickMuteScalarWhereInput;
	data: Prisma.XOR<Prisma.QuickMuteUpdateManyMutationInput, Prisma.QuickMuteUncheckedUpdateManyWithoutGuildInput>;
};

export type QuickMuteScalarWhereInput = {
	AND?: Prisma.QuickMuteScalarWhereInput | Prisma.QuickMuteScalarWhereInput[];
	OR?: Prisma.QuickMuteScalarWhereInput[];
	NOT?: Prisma.QuickMuteScalarWhereInput | Prisma.QuickMuteScalarWhereInput[];
	user_id?: Prisma.StringFilter<"QuickMute"> | string;
	guild_id?: Prisma.StringFilter<"QuickMute"> | string;
	reaction?: Prisma.StringFilter<"QuickMute"> | string;
	duration?: Prisma.BigIntFilter<"QuickMute"> | bigint | number;
	reason?: Prisma.StringFilter<"QuickMute"> | string;
	purge_amount?: Prisma.IntFilter<"QuickMute"> | number;
};

export type QuickMuteCreateManyGuildInput = {
	user_id: string;
	reaction: string;
	duration: bigint | number;
	reason: string;
	purge_amount?: number;
};

export type QuickMuteUpdateWithoutGuildInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	reaction?: Prisma.StringFieldUpdateOperationsInput | string;
	duration?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
	reason?: Prisma.StringFieldUpdateOperationsInput | string;
	purge_amount?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteUncheckedUpdateWithoutGuildInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	reaction?: Prisma.StringFieldUpdateOperationsInput | string;
	duration?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
	reason?: Prisma.StringFieldUpdateOperationsInput | string;
	purge_amount?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteUncheckedUpdateManyWithoutGuildInput = {
	user_id?: Prisma.StringFieldUpdateOperationsInput | string;
	reaction?: Prisma.StringFieldUpdateOperationsInput | string;
	duration?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
	reason?: Prisma.StringFieldUpdateOperationsInput | string;
	purge_amount?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type QuickMuteSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		reaction?: boolean;
		duration?: boolean;
		reason?: boolean;
		purge_amount?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMute"]
>;

export type QuickMuteSelectCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		reaction?: boolean;
		duration?: boolean;
		reason?: boolean;
		purge_amount?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMute"]
>;

export type QuickMuteSelectUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		user_id?: boolean;
		guild_id?: boolean;
		reaction?: boolean;
		duration?: boolean;
		reason?: boolean;
		purge_amount?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMute"]
>;

export type QuickMuteSelectScalar = {
	user_id?: boolean;
	guild_id?: boolean;
	reaction?: boolean;
	duration?: boolean;
	reason?: boolean;
	purge_amount?: boolean;
};

export type QuickMuteOmit<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<
	"user_id" | "guild_id" | "reaction" | "duration" | "reason" | "purge_amount",
	ExtArgs["result"]["quickMute"]
>;
export type QuickMuteInclude<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};
export type QuickMuteIncludeCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};
export type QuickMuteIncludeUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};

export type $QuickMutePayload<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	name: "QuickMute";
	objects: {
		guild: Prisma.$GuildPayload<ExtArgs>;
	};
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			user_id: string;
			guild_id: string;
			reaction: string;
			duration: bigint;
			reason: string;
			purge_amount: number;
		},
		ExtArgs["result"]["quickMute"]
	>;
	composites: {};
};

export type QuickMuteGetPayload<S extends boolean | null | undefined | QuickMuteDefaultArgs> =
	runtime.Types.Result.GetResult<Prisma.$QuickMutePayload, S>;

export type QuickMuteCountArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<QuickMuteFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
	select?: QuickMuteCountAggregateInputType | true;
};

export interface QuickMuteDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> {
	[K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["QuickMute"]; meta: { name: "QuickMute" } };
	/**
	 * Find zero or one QuickMute that matches the filter.
	 * @param {QuickMuteFindUniqueArgs} args - Arguments to find a QuickMute
	 * @example
	 * // Get one QuickMute
	 * const quickMute = await prisma.quickMute.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends QuickMuteFindUniqueArgs>(
		args: Prisma.SelectSubset<T, QuickMuteFindUniqueArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find one QuickMute that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {QuickMuteFindUniqueOrThrowArgs} args - Arguments to find a QuickMute
	 * @example
	 * // Get one QuickMute
	 * const quickMute = await prisma.quickMute.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends QuickMuteFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, QuickMuteFindUniqueOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first QuickMute that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteFindFirstArgs} args - Arguments to find a QuickMute
	 * @example
	 * // Get one QuickMute
	 * const quickMute = await prisma.quickMute.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends QuickMuteFindFirstArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteFindFirstArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first QuickMute that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteFindFirstOrThrowArgs} args - Arguments to find a QuickMute
	 * @example
	 * // Get one QuickMute
	 * const quickMute = await prisma.quickMute.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends QuickMuteFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteFindFirstOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find zero or more QuickMutes that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all QuickMutes
	 * const quickMutes = await prisma.quickMute.findMany()
	 *
	 * // Get first 10 QuickMutes
	 * const quickMutes = await prisma.quickMute.findMany({ take: 10 })
	 *
	 * // Only select the `user_id`
	 * const quickMuteWithUser_idOnly = await prisma.quickMute.findMany({ select: { user_id: true } })
	 *
	 */
	findMany<T extends QuickMuteFindManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteFindManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>
	>;

	/**
	 * Create a QuickMute.
	 * @param {QuickMuteCreateArgs} args - Arguments to create a QuickMute.
	 * @example
	 * // Create one QuickMute
	 * const QuickMute = await prisma.quickMute.create({
	 *   data: {
	 *     // ... data to create a QuickMute
	 *   }
	 * })
	 *
	 */
	create<T extends QuickMuteCreateArgs>(
		args: Prisma.SelectSubset<T, QuickMuteCreateArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "create", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Create many QuickMutes.
	 * @param {QuickMuteCreateManyArgs} args - Arguments to create many QuickMutes.
	 * @example
	 * // Create many QuickMutes
	 * const quickMute = await prisma.quickMute.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends QuickMuteCreateManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteCreateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Create many QuickMutes and returns the data saved in the database.
	 * @param {QuickMuteCreateManyAndReturnArgs} args - Arguments to create many QuickMutes.
	 * @example
	 * // Create many QuickMutes
	 * const quickMute = await prisma.quickMute.createManyAndReturn({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Create many QuickMutes and only return the `user_id`
	 * const quickMuteWithUser_idOnly = await prisma.quickMute.createManyAndReturn({
	 *   select: { user_id: true },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	createManyAndReturn<T extends QuickMuteCreateManyAndReturnArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteCreateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>
	>;

	/**
	 * Delete a QuickMute.
	 * @param {QuickMuteDeleteArgs} args - Arguments to delete one QuickMute.
	 * @example
	 * // Delete one QuickMute
	 * const QuickMute = await prisma.quickMute.delete({
	 *   where: {
	 *     // ... filter to delete one QuickMute
	 *   }
	 * })
	 *
	 */
	delete<T extends QuickMuteDeleteArgs>(
		args: Prisma.SelectSubset<T, QuickMuteDeleteArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "delete", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Update one QuickMute.
	 * @param {QuickMuteUpdateArgs} args - Arguments to update one QuickMute.
	 * @example
	 * // Update one QuickMute
	 * const quickMute = await prisma.quickMute.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends QuickMuteUpdateArgs>(
		args: Prisma.SelectSubset<T, QuickMuteUpdateArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "update", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Delete zero or more QuickMutes.
	 * @param {QuickMuteDeleteManyArgs} args - Arguments to filter QuickMutes to delete.
	 * @example
	 * // Delete a few QuickMutes
	 * const { count } = await prisma.quickMute.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends QuickMuteDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteDeleteManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more QuickMutes.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many QuickMutes
	 * const quickMute = await prisma.quickMute.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends QuickMuteUpdateManyArgs>(
		args: Prisma.SelectSubset<T, QuickMuteUpdateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more QuickMutes and returns the data updated in the database.
	 * @param {QuickMuteUpdateManyAndReturnArgs} args - Arguments to update many QuickMutes.
	 * @example
	 * // Update many QuickMutes
	 * const quickMute = await prisma.quickMute.updateManyAndReturn({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Update zero or more QuickMutes and only return the `user_id`
	 * const quickMuteWithUser_idOnly = await prisma.quickMute.updateManyAndReturn({
	 *   select: { user_id: true },
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	updateManyAndReturn<T extends QuickMuteUpdateManyAndReturnArgs>(
		args: Prisma.SelectSubset<T, QuickMuteUpdateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>
	>;

	/**
	 * Create or update one QuickMute.
	 * @param {QuickMuteUpsertArgs} args - Arguments to update or create a QuickMute.
	 * @example
	 * // Update or create a QuickMute
	 * const quickMute = await prisma.quickMute.upsert({
	 *   create: {
	 *     // ... data to create a QuickMute
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the QuickMute we want to update
	 *   }
	 * })
	 */
	upsert<T extends QuickMuteUpsertArgs>(
		args: Prisma.SelectSubset<T, QuickMuteUpsertArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMutePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Count the number of QuickMutes.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteCountArgs} args - Arguments to filter QuickMutes to count.
	 * @example
	 * // Count the number of QuickMutes
	 * const count = await prisma.quickMute.count({
	 *   where: {
	 *     // ... the filter for the QuickMutes we want to count
	 *   }
	 * })
	 **/
	count<T extends QuickMuteCountArgs>(
		args?: Prisma.Subset<T, QuickMuteCountArgs>
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<"select", any>
			? T["select"] extends true
				? number
				: Prisma.GetScalarType<T["select"], QuickMuteCountAggregateOutputType>
			: number
	>;

	/**
	 * Allows you to perform aggregations operations on a QuickMute.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends QuickMuteAggregateArgs>(
		args: Prisma.Subset<T, QuickMuteAggregateArgs>
	): Prisma.PrismaPromise<GetQuickMuteAggregateType<T>>;

	/**
	 * Group by QuickMute.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends QuickMuteGroupByArgs,
		HasSelectOrTake extends Prisma.Or<
			Prisma.Extends<"skip", Prisma.Keys<T>>,
			Prisma.Extends<"take", Prisma.Keys<T>>
		>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: QuickMuteGroupByArgs["orderBy"] }
			: { orderBy?: QuickMuteGroupByArgs["orderBy"] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T["having"]>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
					}[HavingFields]
				: "take" extends Prisma.Keys<T>
					? "orderBy" extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: "skip" extends Prisma.Keys<T>
						? "orderBy" extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields
											? never
											: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
	>(
		args: Prisma.SubsetIntersection<T, QuickMuteGroupByArgs, OrderByArg> & InputErrors
	): {} extends InputErrors ? GetQuickMuteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
	/**
	 * Fields of the QuickMute model
	 */
	readonly fields: QuickMuteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuickMute.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuickMuteClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: "PrismaPromise";
	guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>
	): Prisma.Prisma__GuildClient<
		| runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>
		| Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>;
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
	): runtime.Types.Utils.JsPromise<T | TResult>;
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the QuickMute model
 */
export interface QuickMuteFieldRefs {
	readonly user_id: Prisma.FieldRef<"QuickMute", "String">;
	readonly guild_id: Prisma.FieldRef<"QuickMute", "String">;
	readonly reaction: Prisma.FieldRef<"QuickMute", "String">;
	readonly duration: Prisma.FieldRef<"QuickMute", "BigInt">;
	readonly reason: Prisma.FieldRef<"QuickMute", "String">;
	readonly purge_amount: Prisma.FieldRef<"QuickMute", "Int">;
}

// Custom InputTypes
/**
 * QuickMute findUnique
 */
export type QuickMuteFindUniqueArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMute to fetch.
	 */
	where: Prisma.QuickMuteWhereUniqueInput;
};

/**
 * QuickMute findUniqueOrThrow
 */
export type QuickMuteFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMute to fetch.
	 */
	where: Prisma.QuickMuteWhereUniqueInput;
};

/**
 * QuickMute findFirst
 */
export type QuickMuteFindFirstArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMute to fetch.
	 */
	where?: Prisma.QuickMuteWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMutes to fetch.
	 */
	orderBy?: Prisma.QuickMuteOrderByWithRelationInput | Prisma.QuickMuteOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for QuickMutes.
	 */
	cursor?: Prisma.QuickMuteWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMutes from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMutes.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of QuickMutes.
	 */
	distinct?: Prisma.QuickMuteScalarFieldEnum | Prisma.QuickMuteScalarFieldEnum[];
};

/**
 * QuickMute findFirstOrThrow
 */
export type QuickMuteFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMute to fetch.
	 */
	where?: Prisma.QuickMuteWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMutes to fetch.
	 */
	orderBy?: Prisma.QuickMuteOrderByWithRelationInput | Prisma.QuickMuteOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for QuickMutes.
	 */
	cursor?: Prisma.QuickMuteWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMutes from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMutes.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of QuickMutes.
	 */
	distinct?: Prisma.QuickMuteScalarFieldEnum | Prisma.QuickMuteScalarFieldEnum[];
};

/**
 * QuickMute findMany
 */
export type QuickMuteFindManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMutes to fetch.
	 */
	where?: Prisma.QuickMuteWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMutes to fetch.
	 */
	orderBy?: Prisma.QuickMuteOrderByWithRelationInput | Prisma.QuickMuteOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing QuickMutes.
	 */
	cursor?: Prisma.QuickMuteWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMutes from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMutes.
	 */
	skip?: number;
	distinct?: Prisma.QuickMuteScalarFieldEnum | Prisma.QuickMuteScalarFieldEnum[];
};

/**
 * QuickMute create
 */
export type QuickMuteCreateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * The data needed to create a QuickMute.
	 */
	data: Prisma.XOR<Prisma.QuickMuteCreateInput, Prisma.QuickMuteUncheckedCreateInput>;
};

/**
 * QuickMute createMany
 */
export type QuickMuteCreateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to create many QuickMutes.
	 */
	data: Prisma.QuickMuteCreateManyInput | Prisma.QuickMuteCreateManyInput[];
	skipDuplicates?: boolean;
};

/**
 * QuickMute createManyAndReturn
 */
export type QuickMuteCreateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelectCreateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * The data used to create many QuickMutes.
	 */
	data: Prisma.QuickMuteCreateManyInput | Prisma.QuickMuteCreateManyInput[];
	skipDuplicates?: boolean;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * QuickMute update
 */
export type QuickMuteUpdateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * The data needed to update a QuickMute.
	 */
	data: Prisma.XOR<Prisma.QuickMuteUpdateInput, Prisma.QuickMuteUncheckedUpdateInput>;
	/**
	 * Choose, which QuickMute to update.
	 */
	where: Prisma.QuickMuteWhereUniqueInput;
};

/**
 * QuickMute updateMany
 */
export type QuickMuteUpdateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to update QuickMutes.
	 */
	data: Prisma.XOR<Prisma.QuickMuteUpdateManyMutationInput, Prisma.QuickMuteUncheckedUpdateManyInput>;
	/**
	 * Filter which QuickMutes to update
	 */
	where?: Prisma.QuickMuteWhereInput;
	/**
	 * Limit how many QuickMutes to update.
	 */
	limit?: number;
};

/**
 * QuickMute updateManyAndReturn
 */
export type QuickMuteUpdateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelectUpdateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * The data used to update QuickMutes.
	 */
	data: Prisma.XOR<Prisma.QuickMuteUpdateManyMutationInput, Prisma.QuickMuteUncheckedUpdateManyInput>;
	/**
	 * Filter which QuickMutes to update
	 */
	where?: Prisma.QuickMuteWhereInput;
	/**
	 * Limit how many QuickMutes to update.
	 */
	limit?: number;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * QuickMute upsert
 */
export type QuickMuteUpsertArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * The filter to search for the QuickMute to update in case it exists.
	 */
	where: Prisma.QuickMuteWhereUniqueInput;
	/**
	 * In case the QuickMute found by the `where` argument doesn't exist, create a new QuickMute with this data.
	 */
	create: Prisma.XOR<Prisma.QuickMuteCreateInput, Prisma.QuickMuteUncheckedCreateInput>;
	/**
	 * In case the QuickMute was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.QuickMuteUpdateInput, Prisma.QuickMuteUncheckedUpdateInput>;
};

/**
 * QuickMute delete
 */
export type QuickMuteDeleteArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
	/**
	 * Filter which QuickMute to delete.
	 */
	where: Prisma.QuickMuteWhereUniqueInput;
};

/**
 * QuickMute deleteMany
 */
export type QuickMuteDeleteManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which QuickMutes to delete
	 */
	where?: Prisma.QuickMuteWhereInput;
	/**
	 * Limit how many QuickMutes to delete.
	 */
	limit?: number;
};

/**
 * QuickMute without action
 */
export type QuickMuteDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMute
	 */
	select?: Prisma.QuickMuteSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMute
	 */
	omit?: Prisma.QuickMuteOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteInclude<ExtArgs> | null;
};
