/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `QuickMuteConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model QuickMuteConfig
 *
 */
export type QuickMuteConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$QuickMuteConfigPayload>;

export type AggregateQuickMuteConfig = {
	_count: QuickMuteConfigCountAggregateOutputType | null;
	_avg: QuickMuteConfigAvgAggregateOutputType | null;
	_sum: QuickMuteConfigSumAggregateOutputType | null;
	_min: QuickMuteConfigMinAggregateOutputType | null;
	_max: QuickMuteConfigMaxAggregateOutputType | null;
};

export type QuickMuteConfigAvgAggregateOutputType = {
	purge_limit: number | null;
};

export type QuickMuteConfigSumAggregateOutputType = {
	purge_limit: number | null;
};

export type QuickMuteConfigMinAggregateOutputType = {
	id: string | null;
	enabled: boolean | null;
	purge_limit: number | null;
	webhook_url: string | null;
	result_webhook_url: string | null;
};

export type QuickMuteConfigMaxAggregateOutputType = {
	id: string | null;
	enabled: boolean | null;
	purge_limit: number | null;
	webhook_url: string | null;
	result_webhook_url: string | null;
};

export type QuickMuteConfigCountAggregateOutputType = {
	id: number;
	enabled: number;
	purge_limit: number;
	webhook_url: number;
	result_webhook_url: number;
	_all: number;
};

export type QuickMuteConfigAvgAggregateInputType = {
	purge_limit?: true;
};

export type QuickMuteConfigSumAggregateInputType = {
	purge_limit?: true;
};

export type QuickMuteConfigMinAggregateInputType = {
	id?: true;
	enabled?: true;
	purge_limit?: true;
	webhook_url?: true;
	result_webhook_url?: true;
};

export type QuickMuteConfigMaxAggregateInputType = {
	id?: true;
	enabled?: true;
	purge_limit?: true;
	webhook_url?: true;
	result_webhook_url?: true;
};

export type QuickMuteConfigCountAggregateInputType = {
	id?: true;
	enabled?: true;
	purge_limit?: true;
	webhook_url?: true;
	result_webhook_url?: true;
	_all?: true;
};

export type QuickMuteConfigAggregateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which QuickMuteConfig to aggregate.
	 */
	where?: Prisma.QuickMuteConfigWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMuteConfigs to fetch.
	 */
	orderBy?: Prisma.QuickMuteConfigOrderByWithRelationInput | Prisma.QuickMuteConfigOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.QuickMuteConfigWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMuteConfigs from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMuteConfigs.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned QuickMuteConfigs
	 **/
	_count?: true | QuickMuteConfigCountAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to average
	 **/
	_avg?: QuickMuteConfigAvgAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to sum
	 **/
	_sum?: QuickMuteConfigSumAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: QuickMuteConfigMinAggregateInputType;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: QuickMuteConfigMaxAggregateInputType;
};

export type GetQuickMuteConfigAggregateType<T extends QuickMuteConfigAggregateArgs> = {
	[P in keyof T & keyof AggregateQuickMuteConfig]: P extends "_count" | "count"
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateQuickMuteConfig[P]>
		: Prisma.GetScalarType<T[P], AggregateQuickMuteConfig[P]>;
};

export type QuickMuteConfigGroupByArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.QuickMuteConfigWhereInput;
	orderBy?: Prisma.QuickMuteConfigOrderByWithAggregationInput | Prisma.QuickMuteConfigOrderByWithAggregationInput[];
	by: Prisma.QuickMuteConfigScalarFieldEnum[] | Prisma.QuickMuteConfigScalarFieldEnum;
	having?: Prisma.QuickMuteConfigScalarWhereWithAggregatesInput;
	take?: number;
	skip?: number;
	_count?: QuickMuteConfigCountAggregateInputType | true;
	_avg?: QuickMuteConfigAvgAggregateInputType;
	_sum?: QuickMuteConfigSumAggregateInputType;
	_min?: QuickMuteConfigMinAggregateInputType;
	_max?: QuickMuteConfigMaxAggregateInputType;
};

export type QuickMuteConfigGroupByOutputType = {
	id: string;
	enabled: boolean;
	purge_limit: number;
	webhook_url: string | null;
	result_webhook_url: string | null;
	_count: QuickMuteConfigCountAggregateOutputType | null;
	_avg: QuickMuteConfigAvgAggregateOutputType | null;
	_sum: QuickMuteConfigSumAggregateOutputType | null;
	_min: QuickMuteConfigMinAggregateOutputType | null;
	_max: QuickMuteConfigMaxAggregateOutputType | null;
};

type GetQuickMuteConfigGroupByPayload<T extends QuickMuteConfigGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<QuickMuteConfigGroupByOutputType, T["by"]> & {
			[P in keyof T & keyof QuickMuteConfigGroupByOutputType]: P extends "_count"
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], QuickMuteConfigGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], QuickMuteConfigGroupByOutputType[P]>;
		}
	>
>;

export type QuickMuteConfigWhereInput = {
	AND?: Prisma.QuickMuteConfigWhereInput | Prisma.QuickMuteConfigWhereInput[];
	OR?: Prisma.QuickMuteConfigWhereInput[];
	NOT?: Prisma.QuickMuteConfigWhereInput | Prisma.QuickMuteConfigWhereInput[];
	id?: Prisma.StringFilter<"QuickMuteConfig"> | string;
	enabled?: Prisma.BoolFilter<"QuickMuteConfig"> | boolean;
	purge_limit?: Prisma.IntFilter<"QuickMuteConfig"> | number;
	webhook_url?: Prisma.StringNullableFilter<"QuickMuteConfig"> | string | null;
	result_webhook_url?: Prisma.StringNullableFilter<"QuickMuteConfig"> | string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingListRelationFilter;
	guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>;
};

export type QuickMuteConfigOrderByWithRelationInput = {
	id?: Prisma.SortOrder;
	enabled?: Prisma.SortOrder;
	purge_limit?: Prisma.SortOrder;
	webhook_url?: Prisma.SortOrderInput | Prisma.SortOrder;
	result_webhook_url?: Prisma.SortOrderInput | Prisma.SortOrder;
	channel_scoping?: Prisma.QuickMuteChannelScopingOrderByRelationAggregateInput;
	guild?: Prisma.GuildOrderByWithRelationInput;
};

export type QuickMuteConfigWhereUniqueInput = Prisma.AtLeast<
	{
		id?: string;
		AND?: Prisma.QuickMuteConfigWhereInput | Prisma.QuickMuteConfigWhereInput[];
		OR?: Prisma.QuickMuteConfigWhereInput[];
		NOT?: Prisma.QuickMuteConfigWhereInput | Prisma.QuickMuteConfigWhereInput[];
		enabled?: Prisma.BoolFilter<"QuickMuteConfig"> | boolean;
		purge_limit?: Prisma.IntFilter<"QuickMuteConfig"> | number;
		webhook_url?: Prisma.StringNullableFilter<"QuickMuteConfig"> | string | null;
		result_webhook_url?: Prisma.StringNullableFilter<"QuickMuteConfig"> | string | null;
		channel_scoping?: Prisma.QuickMuteChannelScopingListRelationFilter;
		guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>;
	},
	"id"
>;

export type QuickMuteConfigOrderByWithAggregationInput = {
	id?: Prisma.SortOrder;
	enabled?: Prisma.SortOrder;
	purge_limit?: Prisma.SortOrder;
	webhook_url?: Prisma.SortOrderInput | Prisma.SortOrder;
	result_webhook_url?: Prisma.SortOrderInput | Prisma.SortOrder;
	_count?: Prisma.QuickMuteConfigCountOrderByAggregateInput;
	_avg?: Prisma.QuickMuteConfigAvgOrderByAggregateInput;
	_max?: Prisma.QuickMuteConfigMaxOrderByAggregateInput;
	_min?: Prisma.QuickMuteConfigMinOrderByAggregateInput;
	_sum?: Prisma.QuickMuteConfigSumOrderByAggregateInput;
};

export type QuickMuteConfigScalarWhereWithAggregatesInput = {
	AND?:
		| Prisma.QuickMuteConfigScalarWhereWithAggregatesInput
		| Prisma.QuickMuteConfigScalarWhereWithAggregatesInput[];
	OR?: Prisma.QuickMuteConfigScalarWhereWithAggregatesInput[];
	NOT?:
		| Prisma.QuickMuteConfigScalarWhereWithAggregatesInput
		| Prisma.QuickMuteConfigScalarWhereWithAggregatesInput[];
	id?: Prisma.StringWithAggregatesFilter<"QuickMuteConfig"> | string;
	enabled?: Prisma.BoolWithAggregatesFilter<"QuickMuteConfig"> | boolean;
	purge_limit?: Prisma.IntWithAggregatesFilter<"QuickMuteConfig"> | number;
	webhook_url?: Prisma.StringNullableWithAggregatesFilter<"QuickMuteConfig"> | string | null;
	result_webhook_url?: Prisma.StringNullableWithAggregatesFilter<"QuickMuteConfig"> | string | null;
};

export type QuickMuteConfigCreateInput = {
	enabled?: boolean;
	purge_limit?: number;
	webhook_url?: string | null;
	result_webhook_url?: string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingCreateNestedManyWithoutQuick_mute_configInput;
	guild: Prisma.GuildCreateNestedOneWithoutQuick_mute_configInput;
};

export type QuickMuteConfigUncheckedCreateInput = {
	id: string;
	enabled?: boolean;
	purge_limit?: number;
	webhook_url?: string | null;
	result_webhook_url?: string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingUncheckedCreateNestedManyWithoutQuick_mute_configInput;
};

export type QuickMuteConfigUpdateInput = {
	enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
	purge_limit?: Prisma.IntFieldUpdateOperationsInput | number;
	webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	result_webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingUpdateManyWithoutQuick_mute_configNestedInput;
	guild?: Prisma.GuildUpdateOneRequiredWithoutQuick_mute_configNestedInput;
};

export type QuickMuteConfigUncheckedUpdateInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
	purge_limit?: Prisma.IntFieldUpdateOperationsInput | number;
	webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	result_webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingUncheckedUpdateManyWithoutQuick_mute_configNestedInput;
};

export type QuickMuteConfigCreateManyInput = {
	id: string;
	enabled?: boolean;
	purge_limit?: number;
	webhook_url?: string | null;
	result_webhook_url?: string | null;
};

export type QuickMuteConfigUpdateManyMutationInput = {
	enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
	purge_limit?: Prisma.IntFieldUpdateOperationsInput | number;
	webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	result_webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type QuickMuteConfigUncheckedUpdateManyInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
	purge_limit?: Prisma.IntFieldUpdateOperationsInput | number;
	webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	result_webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type QuickMuteConfigNullableScalarRelationFilter = {
	is?: Prisma.QuickMuteConfigWhereInput | null;
	isNot?: Prisma.QuickMuteConfigWhereInput | null;
};

export type QuickMuteConfigCountOrderByAggregateInput = {
	id?: Prisma.SortOrder;
	enabled?: Prisma.SortOrder;
	purge_limit?: Prisma.SortOrder;
	webhook_url?: Prisma.SortOrder;
	result_webhook_url?: Prisma.SortOrder;
};

export type QuickMuteConfigAvgOrderByAggregateInput = {
	purge_limit?: Prisma.SortOrder;
};

export type QuickMuteConfigMaxOrderByAggregateInput = {
	id?: Prisma.SortOrder;
	enabled?: Prisma.SortOrder;
	purge_limit?: Prisma.SortOrder;
	webhook_url?: Prisma.SortOrder;
	result_webhook_url?: Prisma.SortOrder;
};

export type QuickMuteConfigMinOrderByAggregateInput = {
	id?: Prisma.SortOrder;
	enabled?: Prisma.SortOrder;
	purge_limit?: Prisma.SortOrder;
	webhook_url?: Prisma.SortOrder;
	result_webhook_url?: Prisma.SortOrder;
};

export type QuickMuteConfigSumOrderByAggregateInput = {
	purge_limit?: Prisma.SortOrder;
};

export type QuickMuteConfigScalarRelationFilter = {
	is?: Prisma.QuickMuteConfigWhereInput;
	isNot?: Prisma.QuickMuteConfigWhereInput;
};

export type QuickMuteConfigCreateNestedOneWithoutGuildInput = {
	create?: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutGuildInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutGuildInput
	>;
	connectOrCreate?: Prisma.QuickMuteConfigCreateOrConnectWithoutGuildInput;
	connect?: Prisma.QuickMuteConfigWhereUniqueInput;
};

export type QuickMuteConfigUncheckedCreateNestedOneWithoutGuildInput = {
	create?: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutGuildInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutGuildInput
	>;
	connectOrCreate?: Prisma.QuickMuteConfigCreateOrConnectWithoutGuildInput;
	connect?: Prisma.QuickMuteConfigWhereUniqueInput;
};

export type QuickMuteConfigUpdateOneWithoutGuildNestedInput = {
	create?: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutGuildInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutGuildInput
	>;
	connectOrCreate?: Prisma.QuickMuteConfigCreateOrConnectWithoutGuildInput;
	upsert?: Prisma.QuickMuteConfigUpsertWithoutGuildInput;
	disconnect?: Prisma.QuickMuteConfigWhereInput | boolean;
	delete?: Prisma.QuickMuteConfigWhereInput | boolean;
	connect?: Prisma.QuickMuteConfigWhereUniqueInput;
	update?: Prisma.XOR<
		Prisma.XOR<
			Prisma.QuickMuteConfigUpdateToOneWithWhereWithoutGuildInput,
			Prisma.QuickMuteConfigUpdateWithoutGuildInput
		>,
		Prisma.QuickMuteConfigUncheckedUpdateWithoutGuildInput
	>;
};

export type QuickMuteConfigUncheckedUpdateOneWithoutGuildNestedInput = {
	create?: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutGuildInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutGuildInput
	>;
	connectOrCreate?: Prisma.QuickMuteConfigCreateOrConnectWithoutGuildInput;
	upsert?: Prisma.QuickMuteConfigUpsertWithoutGuildInput;
	disconnect?: Prisma.QuickMuteConfigWhereInput | boolean;
	delete?: Prisma.QuickMuteConfigWhereInput | boolean;
	connect?: Prisma.QuickMuteConfigWhereUniqueInput;
	update?: Prisma.XOR<
		Prisma.XOR<
			Prisma.QuickMuteConfigUpdateToOneWithWhereWithoutGuildInput,
			Prisma.QuickMuteConfigUpdateWithoutGuildInput
		>,
		Prisma.QuickMuteConfigUncheckedUpdateWithoutGuildInput
	>;
};

export type QuickMuteConfigCreateNestedOneWithoutChannel_scopingInput = {
	create?: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutChannel_scopingInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutChannel_scopingInput
	>;
	connectOrCreate?: Prisma.QuickMuteConfigCreateOrConnectWithoutChannel_scopingInput;
	connect?: Prisma.QuickMuteConfigWhereUniqueInput;
};

export type QuickMuteConfigUpdateOneRequiredWithoutChannel_scopingNestedInput = {
	create?: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutChannel_scopingInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutChannel_scopingInput
	>;
	connectOrCreate?: Prisma.QuickMuteConfigCreateOrConnectWithoutChannel_scopingInput;
	upsert?: Prisma.QuickMuteConfigUpsertWithoutChannel_scopingInput;
	connect?: Prisma.QuickMuteConfigWhereUniqueInput;
	update?: Prisma.XOR<
		Prisma.XOR<
			Prisma.QuickMuteConfigUpdateToOneWithWhereWithoutChannel_scopingInput,
			Prisma.QuickMuteConfigUpdateWithoutChannel_scopingInput
		>,
		Prisma.QuickMuteConfigUncheckedUpdateWithoutChannel_scopingInput
	>;
};

export type QuickMuteConfigCreateWithoutGuildInput = {
	enabled?: boolean;
	purge_limit?: number;
	webhook_url?: string | null;
	result_webhook_url?: string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingCreateNestedManyWithoutQuick_mute_configInput;
};

export type QuickMuteConfigUncheckedCreateWithoutGuildInput = {
	enabled?: boolean;
	purge_limit?: number;
	webhook_url?: string | null;
	result_webhook_url?: string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingUncheckedCreateNestedManyWithoutQuick_mute_configInput;
};

export type QuickMuteConfigCreateOrConnectWithoutGuildInput = {
	where: Prisma.QuickMuteConfigWhereUniqueInput;
	create: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutGuildInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutGuildInput
	>;
};

export type QuickMuteConfigUpsertWithoutGuildInput = {
	update: Prisma.XOR<
		Prisma.QuickMuteConfigUpdateWithoutGuildInput,
		Prisma.QuickMuteConfigUncheckedUpdateWithoutGuildInput
	>;
	create: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutGuildInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutGuildInput
	>;
	where?: Prisma.QuickMuteConfigWhereInput;
};

export type QuickMuteConfigUpdateToOneWithWhereWithoutGuildInput = {
	where?: Prisma.QuickMuteConfigWhereInput;
	data: Prisma.XOR<
		Prisma.QuickMuteConfigUpdateWithoutGuildInput,
		Prisma.QuickMuteConfigUncheckedUpdateWithoutGuildInput
	>;
};

export type QuickMuteConfigUpdateWithoutGuildInput = {
	enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
	purge_limit?: Prisma.IntFieldUpdateOperationsInput | number;
	webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	result_webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingUpdateManyWithoutQuick_mute_configNestedInput;
};

export type QuickMuteConfigUncheckedUpdateWithoutGuildInput = {
	enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
	purge_limit?: Prisma.IntFieldUpdateOperationsInput | number;
	webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	result_webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	channel_scoping?: Prisma.QuickMuteChannelScopingUncheckedUpdateManyWithoutQuick_mute_configNestedInput;
};

export type QuickMuteConfigCreateWithoutChannel_scopingInput = {
	enabled?: boolean;
	purge_limit?: number;
	webhook_url?: string | null;
	result_webhook_url?: string | null;
	guild: Prisma.GuildCreateNestedOneWithoutQuick_mute_configInput;
};

export type QuickMuteConfigUncheckedCreateWithoutChannel_scopingInput = {
	id: string;
	enabled?: boolean;
	purge_limit?: number;
	webhook_url?: string | null;
	result_webhook_url?: string | null;
};

export type QuickMuteConfigCreateOrConnectWithoutChannel_scopingInput = {
	where: Prisma.QuickMuteConfigWhereUniqueInput;
	create: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutChannel_scopingInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutChannel_scopingInput
	>;
};

export type QuickMuteConfigUpsertWithoutChannel_scopingInput = {
	update: Prisma.XOR<
		Prisma.QuickMuteConfigUpdateWithoutChannel_scopingInput,
		Prisma.QuickMuteConfigUncheckedUpdateWithoutChannel_scopingInput
	>;
	create: Prisma.XOR<
		Prisma.QuickMuteConfigCreateWithoutChannel_scopingInput,
		Prisma.QuickMuteConfigUncheckedCreateWithoutChannel_scopingInput
	>;
	where?: Prisma.QuickMuteConfigWhereInput;
};

export type QuickMuteConfigUpdateToOneWithWhereWithoutChannel_scopingInput = {
	where?: Prisma.QuickMuteConfigWhereInput;
	data: Prisma.XOR<
		Prisma.QuickMuteConfigUpdateWithoutChannel_scopingInput,
		Prisma.QuickMuteConfigUncheckedUpdateWithoutChannel_scopingInput
	>;
};

export type QuickMuteConfigUpdateWithoutChannel_scopingInput = {
	enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
	purge_limit?: Prisma.IntFieldUpdateOperationsInput | number;
	webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	result_webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	guild?: Prisma.GuildUpdateOneRequiredWithoutQuick_mute_configNestedInput;
};

export type QuickMuteConfigUncheckedUpdateWithoutChannel_scopingInput = {
	id?: Prisma.StringFieldUpdateOperationsInput | string;
	enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
	purge_limit?: Prisma.IntFieldUpdateOperationsInput | number;
	webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
	result_webhook_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

/**
 * Count Type QuickMuteConfigCountOutputType
 */

export type QuickMuteConfigCountOutputType = {
	channel_scoping: number;
};

export type QuickMuteConfigCountOutputTypeSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	channel_scoping?: boolean | QuickMuteConfigCountOutputTypeCountChannel_scopingArgs;
};

/**
 * QuickMuteConfigCountOutputType without action
 */
export type QuickMuteConfigCountOutputTypeDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfigCountOutputType
	 */
	select?: Prisma.QuickMuteConfigCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * QuickMuteConfigCountOutputType without action
 */
export type QuickMuteConfigCountOutputTypeCountChannel_scopingArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	where?: Prisma.QuickMuteChannelScopingWhereInput;
};

export type QuickMuteConfigSelect<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		id?: boolean;
		enabled?: boolean;
		purge_limit?: boolean;
		webhook_url?: boolean;
		result_webhook_url?: boolean;
		channel_scoping?: boolean | Prisma.QuickMuteConfig$channel_scopingArgs<ExtArgs>;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
		_count?: boolean | Prisma.QuickMuteConfigCountOutputTypeDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMuteConfig"]
>;

export type QuickMuteConfigSelectCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		id?: boolean;
		enabled?: boolean;
		purge_limit?: boolean;
		webhook_url?: boolean;
		result_webhook_url?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMuteConfig"]
>;

export type QuickMuteConfigSelectUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
	{
		id?: boolean;
		enabled?: boolean;
		purge_limit?: boolean;
		webhook_url?: boolean;
		result_webhook_url?: boolean;
		guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	},
	ExtArgs["result"]["quickMuteConfig"]
>;

export type QuickMuteConfigSelectScalar = {
	id?: boolean;
	enabled?: boolean;
	purge_limit?: boolean;
	webhook_url?: boolean;
	result_webhook_url?: boolean;
};

export type QuickMuteConfigOmit<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<
	"id" | "enabled" | "purge_limit" | "webhook_url" | "result_webhook_url",
	ExtArgs["result"]["quickMuteConfig"]
>;
export type QuickMuteConfigInclude<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	channel_scoping?: boolean | Prisma.QuickMuteConfig$channel_scopingArgs<ExtArgs>;
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
	_count?: boolean | Prisma.QuickMuteConfigCountOutputTypeDefaultArgs<ExtArgs>;
};
export type QuickMuteConfigIncludeCreateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};
export type QuickMuteConfigIncludeUpdateManyAndReturn<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>;
};

export type $QuickMuteConfigPayload<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	name: "QuickMuteConfig";
	objects: {
		channel_scoping: Prisma.$QuickMuteChannelScopingPayload<ExtArgs>[];
		guild: Prisma.$GuildPayload<ExtArgs>;
	};
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			id: string;
			enabled: boolean;
			purge_limit: number;
			webhook_url: string | null;
			result_webhook_url: string | null;
		},
		ExtArgs["result"]["quickMuteConfig"]
	>;
	composites: {};
};

export type QuickMuteConfigGetPayload<S extends boolean | null | undefined | QuickMuteConfigDefaultArgs> =
	runtime.Types.Result.GetResult<Prisma.$QuickMuteConfigPayload, S>;

export type QuickMuteConfigCountArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<QuickMuteConfigFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
	select?: QuickMuteConfigCountAggregateInputType | true;
};

export interface QuickMuteConfigDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> {
	[K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["QuickMuteConfig"]; meta: { name: "QuickMuteConfig" } };
	/**
	 * Find zero or one QuickMuteConfig that matches the filter.
	 * @param {QuickMuteConfigFindUniqueArgs} args - Arguments to find a QuickMuteConfig
	 * @example
	 * // Get one QuickMuteConfig
	 * const quickMuteConfig = await prisma.quickMuteConfig.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends QuickMuteConfigFindUniqueArgs>(
		args: Prisma.SelectSubset<T, QuickMuteConfigFindUniqueArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteConfigPayload<ExtArgs>,
			T,
			"findUnique",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find one QuickMuteConfig that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {QuickMuteConfigFindUniqueOrThrowArgs} args - Arguments to find a QuickMuteConfig
	 * @example
	 * // Get one QuickMuteConfig
	 * const quickMuteConfig = await prisma.quickMuteConfig.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends QuickMuteConfigFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, QuickMuteConfigFindUniqueOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteConfigPayload<ExtArgs>,
			T,
			"findUniqueOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first QuickMuteConfig that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteConfigFindFirstArgs} args - Arguments to find a QuickMuteConfig
	 * @example
	 * // Get one QuickMuteConfig
	 * const quickMuteConfig = await prisma.quickMuteConfig.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends QuickMuteConfigFindFirstArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteConfigFindFirstArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteConfigPayload<ExtArgs>,
			T,
			"findFirst",
			GlobalOmitOptions
		> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find the first QuickMuteConfig that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteConfigFindFirstOrThrowArgs} args - Arguments to find a QuickMuteConfig
	 * @example
	 * // Get one QuickMuteConfig
	 * const quickMuteConfig = await prisma.quickMuteConfig.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends QuickMuteConfigFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteConfigFindFirstOrThrowArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteConfigPayload<ExtArgs>,
			T,
			"findFirstOrThrow",
			GlobalOmitOptions
		>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Find zero or more QuickMuteConfigs that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteConfigFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all QuickMuteConfigs
	 * const quickMuteConfigs = await prisma.quickMuteConfig.findMany()
	 *
	 * // Get first 10 QuickMuteConfigs
	 * const quickMuteConfigs = await prisma.quickMuteConfig.findMany({ take: 10 })
	 *
	 * // Only select the `id`
	 * const quickMuteConfigWithIdOnly = await prisma.quickMuteConfig.findMany({ select: { id: true } })
	 *
	 */
	findMany<T extends QuickMuteConfigFindManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteConfigFindManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$QuickMuteConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>
	>;

	/**
	 * Create a QuickMuteConfig.
	 * @param {QuickMuteConfigCreateArgs} args - Arguments to create a QuickMuteConfig.
	 * @example
	 * // Create one QuickMuteConfig
	 * const QuickMuteConfig = await prisma.quickMuteConfig.create({
	 *   data: {
	 *     // ... data to create a QuickMuteConfig
	 *   }
	 * })
	 *
	 */
	create<T extends QuickMuteConfigCreateArgs>(
		args: Prisma.SelectSubset<T, QuickMuteConfigCreateArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMuteConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Create many QuickMuteConfigs.
	 * @param {QuickMuteConfigCreateManyArgs} args - Arguments to create many QuickMuteConfigs.
	 * @example
	 * // Create many QuickMuteConfigs
	 * const quickMuteConfig = await prisma.quickMuteConfig.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends QuickMuteConfigCreateManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteConfigCreateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Create many QuickMuteConfigs and returns the data saved in the database.
	 * @param {QuickMuteConfigCreateManyAndReturnArgs} args - Arguments to create many QuickMuteConfigs.
	 * @example
	 * // Create many QuickMuteConfigs
	 * const quickMuteConfig = await prisma.quickMuteConfig.createManyAndReturn({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Create many QuickMuteConfigs and only return the `id`
	 * const quickMuteConfigWithIdOnly = await prisma.quickMuteConfig.createManyAndReturn({
	 *   select: { id: true },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	createManyAndReturn<T extends QuickMuteConfigCreateManyAndReturnArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteConfigCreateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteConfigPayload<ExtArgs>,
			T,
			"createManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Delete a QuickMuteConfig.
	 * @param {QuickMuteConfigDeleteArgs} args - Arguments to delete one QuickMuteConfig.
	 * @example
	 * // Delete one QuickMuteConfig
	 * const QuickMuteConfig = await prisma.quickMuteConfig.delete({
	 *   where: {
	 *     // ... filter to delete one QuickMuteConfig
	 *   }
	 * })
	 *
	 */
	delete<T extends QuickMuteConfigDeleteArgs>(
		args: Prisma.SelectSubset<T, QuickMuteConfigDeleteArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMuteConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Update one QuickMuteConfig.
	 * @param {QuickMuteConfigUpdateArgs} args - Arguments to update one QuickMuteConfig.
	 * @example
	 * // Update one QuickMuteConfig
	 * const quickMuteConfig = await prisma.quickMuteConfig.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends QuickMuteConfigUpdateArgs>(
		args: Prisma.SelectSubset<T, QuickMuteConfigUpdateArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMuteConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Delete zero or more QuickMuteConfigs.
	 * @param {QuickMuteConfigDeleteManyArgs} args - Arguments to filter QuickMuteConfigs to delete.
	 * @example
	 * // Delete a few QuickMuteConfigs
	 * const { count } = await prisma.quickMuteConfig.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends QuickMuteConfigDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, QuickMuteConfigDeleteManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more QuickMuteConfigs.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteConfigUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many QuickMuteConfigs
	 * const quickMuteConfig = await prisma.quickMuteConfig.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends QuickMuteConfigUpdateManyArgs>(
		args: Prisma.SelectSubset<T, QuickMuteConfigUpdateManyArgs<ExtArgs>>
	): Prisma.PrismaPromise<Prisma.BatchPayload>;

	/**
	 * Update zero or more QuickMuteConfigs and returns the data updated in the database.
	 * @param {QuickMuteConfigUpdateManyAndReturnArgs} args - Arguments to update many QuickMuteConfigs.
	 * @example
	 * // Update many QuickMuteConfigs
	 * const quickMuteConfig = await prisma.quickMuteConfig.updateManyAndReturn({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 * // Update zero or more QuickMuteConfigs and only return the `id`
	 * const quickMuteConfigWithIdOnly = await prisma.quickMuteConfig.updateManyAndReturn({
	 *   select: { id: true },
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 *
	 */
	updateManyAndReturn<T extends QuickMuteConfigUpdateManyAndReturnArgs>(
		args: Prisma.SelectSubset<T, QuickMuteConfigUpdateManyAndReturnArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<
			Prisma.$QuickMuteConfigPayload<ExtArgs>,
			T,
			"updateManyAndReturn",
			GlobalOmitOptions
		>
	>;

	/**
	 * Create or update one QuickMuteConfig.
	 * @param {QuickMuteConfigUpsertArgs} args - Arguments to update or create a QuickMuteConfig.
	 * @example
	 * // Update or create a QuickMuteConfig
	 * const quickMuteConfig = await prisma.quickMuteConfig.upsert({
	 *   create: {
	 *     // ... data to create a QuickMuteConfig
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the QuickMuteConfig we want to update
	 *   }
	 * })
	 */
	upsert<T extends QuickMuteConfigUpsertArgs>(
		args: Prisma.SelectSubset<T, QuickMuteConfigUpsertArgs<ExtArgs>>
	): Prisma.Prisma__QuickMuteConfigClient<
		runtime.Types.Result.GetResult<Prisma.$QuickMuteConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>;

	/**
	 * Count the number of QuickMuteConfigs.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteConfigCountArgs} args - Arguments to filter QuickMuteConfigs to count.
	 * @example
	 * // Count the number of QuickMuteConfigs
	 * const count = await prisma.quickMuteConfig.count({
	 *   where: {
	 *     // ... the filter for the QuickMuteConfigs we want to count
	 *   }
	 * })
	 **/
	count<T extends QuickMuteConfigCountArgs>(
		args?: Prisma.Subset<T, QuickMuteConfigCountArgs>
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<"select", any>
			? T["select"] extends true
				? number
				: Prisma.GetScalarType<T["select"], QuickMuteConfigCountAggregateOutputType>
			: number
	>;

	/**
	 * Allows you to perform aggregations operations on a QuickMuteConfig.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends QuickMuteConfigAggregateArgs>(
		args: Prisma.Subset<T, QuickMuteConfigAggregateArgs>
	): Prisma.PrismaPromise<GetQuickMuteConfigAggregateType<T>>;

	/**
	 * Group by QuickMuteConfig.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {QuickMuteConfigGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends QuickMuteConfigGroupByArgs,
		HasSelectOrTake extends Prisma.Or<
			Prisma.Extends<"skip", Prisma.Keys<T>>,
			Prisma.Extends<"take", Prisma.Keys<T>>
		>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: QuickMuteConfigGroupByArgs["orderBy"] }
			: { orderBy?: QuickMuteConfigGroupByArgs["orderBy"] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T["having"]>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
					}[HavingFields]
				: "take" extends Prisma.Keys<T>
					? "orderBy" extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: "skip" extends Prisma.Keys<T>
						? "orderBy" extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields
											? never
											: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields
										? never
										: `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
								}[OrderFields]
	>(
		args: Prisma.SubsetIntersection<T, QuickMuteConfigGroupByArgs, OrderByArg> & InputErrors
	): {} extends InputErrors ? GetQuickMuteConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
	/**
	 * Fields of the QuickMuteConfig model
	 */
	readonly fields: QuickMuteConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuickMuteConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuickMuteConfigClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: "PrismaPromise";
	channel_scoping<T extends Prisma.QuickMuteConfig$channel_scopingArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.QuickMuteConfig$channel_scopingArgs<ExtArgs>>
	): Prisma.PrismaPromise<
		| runtime.Types.Result.GetResult<
				Prisma.$QuickMuteChannelScopingPayload<ExtArgs>,
				T,
				"findMany",
				GlobalOmitOptions
		  >
		| Null
	>;
	guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>
	): Prisma.Prisma__GuildClient<
		| runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>
		| Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>;
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
	): runtime.Types.Utils.JsPromise<T | TResult>;
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the QuickMuteConfig model
 */
export interface QuickMuteConfigFieldRefs {
	readonly id: Prisma.FieldRef<"QuickMuteConfig", "String">;
	readonly enabled: Prisma.FieldRef<"QuickMuteConfig", "Boolean">;
	readonly purge_limit: Prisma.FieldRef<"QuickMuteConfig", "Int">;
	readonly webhook_url: Prisma.FieldRef<"QuickMuteConfig", "String">;
	readonly result_webhook_url: Prisma.FieldRef<"QuickMuteConfig", "String">;
}

// Custom InputTypes
/**
 * QuickMuteConfig findUnique
 */
export type QuickMuteConfigFindUniqueArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteConfig to fetch.
	 */
	where: Prisma.QuickMuteConfigWhereUniqueInput;
};

/**
 * QuickMuteConfig findUniqueOrThrow
 */
export type QuickMuteConfigFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteConfig to fetch.
	 */
	where: Prisma.QuickMuteConfigWhereUniqueInput;
};

/**
 * QuickMuteConfig findFirst
 */
export type QuickMuteConfigFindFirstArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteConfig to fetch.
	 */
	where?: Prisma.QuickMuteConfigWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMuteConfigs to fetch.
	 */
	orderBy?: Prisma.QuickMuteConfigOrderByWithRelationInput | Prisma.QuickMuteConfigOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for QuickMuteConfigs.
	 */
	cursor?: Prisma.QuickMuteConfigWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMuteConfigs from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMuteConfigs.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of QuickMuteConfigs.
	 */
	distinct?: Prisma.QuickMuteConfigScalarFieldEnum | Prisma.QuickMuteConfigScalarFieldEnum[];
};

/**
 * QuickMuteConfig findFirstOrThrow
 */
export type QuickMuteConfigFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteConfig to fetch.
	 */
	where?: Prisma.QuickMuteConfigWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMuteConfigs to fetch.
	 */
	orderBy?: Prisma.QuickMuteConfigOrderByWithRelationInput | Prisma.QuickMuteConfigOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for QuickMuteConfigs.
	 */
	cursor?: Prisma.QuickMuteConfigWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMuteConfigs from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMuteConfigs.
	 */
	skip?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of QuickMuteConfigs.
	 */
	distinct?: Prisma.QuickMuteConfigScalarFieldEnum | Prisma.QuickMuteConfigScalarFieldEnum[];
};

/**
 * QuickMuteConfig findMany
 */
export type QuickMuteConfigFindManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * Filter, which QuickMuteConfigs to fetch.
	 */
	where?: Prisma.QuickMuteConfigWhereInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of QuickMuteConfigs to fetch.
	 */
	orderBy?: Prisma.QuickMuteConfigOrderByWithRelationInput | Prisma.QuickMuteConfigOrderByWithRelationInput[];
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing QuickMuteConfigs.
	 */
	cursor?: Prisma.QuickMuteConfigWhereUniqueInput;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` QuickMuteConfigs from the position of the cursor.
	 */
	take?: number;
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` QuickMuteConfigs.
	 */
	skip?: number;
	distinct?: Prisma.QuickMuteConfigScalarFieldEnum | Prisma.QuickMuteConfigScalarFieldEnum[];
};

/**
 * QuickMuteConfig create
 */
export type QuickMuteConfigCreateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * The data needed to create a QuickMuteConfig.
	 */
	data: Prisma.XOR<Prisma.QuickMuteConfigCreateInput, Prisma.QuickMuteConfigUncheckedCreateInput>;
};

/**
 * QuickMuteConfig createMany
 */
export type QuickMuteConfigCreateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to create many QuickMuteConfigs.
	 */
	data: Prisma.QuickMuteConfigCreateManyInput | Prisma.QuickMuteConfigCreateManyInput[];
	skipDuplicates?: boolean;
};

/**
 * QuickMuteConfig createManyAndReturn
 */
export type QuickMuteConfigCreateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelectCreateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * The data used to create many QuickMuteConfigs.
	 */
	data: Prisma.QuickMuteConfigCreateManyInput | Prisma.QuickMuteConfigCreateManyInput[];
	skipDuplicates?: boolean;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * QuickMuteConfig update
 */
export type QuickMuteConfigUpdateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * The data needed to update a QuickMuteConfig.
	 */
	data: Prisma.XOR<Prisma.QuickMuteConfigUpdateInput, Prisma.QuickMuteConfigUncheckedUpdateInput>;
	/**
	 * Choose, which QuickMuteConfig to update.
	 */
	where: Prisma.QuickMuteConfigWhereUniqueInput;
};

/**
 * QuickMuteConfig updateMany
 */
export type QuickMuteConfigUpdateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * The data used to update QuickMuteConfigs.
	 */
	data: Prisma.XOR<Prisma.QuickMuteConfigUpdateManyMutationInput, Prisma.QuickMuteConfigUncheckedUpdateManyInput>;
	/**
	 * Filter which QuickMuteConfigs to update
	 */
	where?: Prisma.QuickMuteConfigWhereInput;
	/**
	 * Limit how many QuickMuteConfigs to update.
	 */
	limit?: number;
};

/**
 * QuickMuteConfig updateManyAndReturn
 */
export type QuickMuteConfigUpdateManyAndReturnArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelectUpdateManyAndReturn<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * The data used to update QuickMuteConfigs.
	 */
	data: Prisma.XOR<Prisma.QuickMuteConfigUpdateManyMutationInput, Prisma.QuickMuteConfigUncheckedUpdateManyInput>;
	/**
	 * Filter which QuickMuteConfigs to update
	 */
	where?: Prisma.QuickMuteConfigWhereInput;
	/**
	 * Limit how many QuickMuteConfigs to update.
	 */
	limit?: number;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * QuickMuteConfig upsert
 */
export type QuickMuteConfigUpsertArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * The filter to search for the QuickMuteConfig to update in case it exists.
	 */
	where: Prisma.QuickMuteConfigWhereUniqueInput;
	/**
	 * In case the QuickMuteConfig found by the `where` argument doesn't exist, create a new QuickMuteConfig with this data.
	 */
	create: Prisma.XOR<Prisma.QuickMuteConfigCreateInput, Prisma.QuickMuteConfigUncheckedCreateInput>;
	/**
	 * In case the QuickMuteConfig was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.QuickMuteConfigUpdateInput, Prisma.QuickMuteConfigUncheckedUpdateInput>;
};

/**
 * QuickMuteConfig delete
 */
export type QuickMuteConfigDeleteArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
	/**
	 * Filter which QuickMuteConfig to delete.
	 */
	where: Prisma.QuickMuteConfigWhereUniqueInput;
};

/**
 * QuickMuteConfig deleteMany
 */
export type QuickMuteConfigDeleteManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Filter which QuickMuteConfigs to delete
	 */
	where?: Prisma.QuickMuteConfigWhereInput;
	/**
	 * Limit how many QuickMuteConfigs to delete.
	 */
	limit?: number;
};

/**
 * QuickMuteConfig.channel_scoping
 */
export type QuickMuteConfig$channel_scopingArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteChannelScoping
	 */
	select?: Prisma.QuickMuteChannelScopingSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteChannelScoping
	 */
	omit?: Prisma.QuickMuteChannelScopingOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteChannelScopingInclude<ExtArgs> | null;
	where?: Prisma.QuickMuteChannelScopingWhereInput;
	orderBy?:
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput
		| Prisma.QuickMuteChannelScopingOrderByWithRelationInput[];
	cursor?: Prisma.QuickMuteChannelScopingWhereUniqueInput;
	take?: number;
	skip?: number;
	distinct?: Prisma.QuickMuteChannelScopingScalarFieldEnum | Prisma.QuickMuteChannelScopingScalarFieldEnum[];
};

/**
 * QuickMuteConfig without action
 */
export type QuickMuteConfigDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
	/**
	 * Select specific fields to fetch from the QuickMuteConfig
	 */
	select?: Prisma.QuickMuteConfigSelect<ExtArgs> | null;
	/**
	 * Omit specific fields from the QuickMuteConfig
	 */
	omit?: Prisma.QuickMuteConfigOmit<ExtArgs> | null;
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.QuickMuteConfigInclude<ExtArgs> | null;
};
